// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshacl"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshaclrevision"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshnode"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshrelay"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshservice"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshsetting"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MeshACL is the client for interacting with the MeshACL builders.
	MeshACL *MeshACLClient
	// MeshACLRevision is the client for interacting with the MeshACLRevision builders.
	MeshACLRevision *MeshACLRevisionClient
	// MeshNode is the client for interacting with the MeshNode builders.
	MeshNode *MeshNodeClient
	// MeshRelay is the client for interacting with the MeshRelay builders.
	MeshRelay *MeshRelayClient
	// MeshService is the client for interacting with the MeshService builders.
	MeshService *MeshServiceClient
	// MeshSetting is the client for interacting with the MeshSetting builders.
	MeshSetting *MeshSettingClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MeshACL = NewMeshACLClient(c.config)
	c.MeshACLRevision = NewMeshACLRevisionClient(c.config)
	c.MeshNode = NewMeshNodeClient(c.config)
	c.MeshRelay = NewMeshRelayClient(c.config)
	c.MeshService = NewMeshServiceClient(c.config)
	c.MeshSetting = NewMeshSettingClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		MeshACL:         NewMeshACLClient(cfg),
		MeshACLRevision: NewMeshACLRevisionClient(cfg),
		MeshNode:        NewMeshNodeClient(cfg),
		MeshRelay:       NewMeshRelayClient(cfg),
		MeshService:     NewMeshServiceClient(cfg),
		MeshSetting:     NewMeshSettingClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		MeshACL:         NewMeshACLClient(cfg),
		MeshACLRevision: NewMeshACLRevisionClient(cfg),
		MeshNode:        NewMeshNodeClient(cfg),
		MeshRelay:       NewMeshRelayClient(cfg),
		MeshService:     NewMeshServiceClient(cfg),
		MeshSetting:     NewMeshSettingClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MeshACL.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.MeshACL, c.MeshACLRevision, c.MeshNode, c.MeshRelay, c.MeshService,
		c.MeshSetting,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.MeshACL, c.MeshACLRevision, c.MeshNode, c.MeshRelay, c.MeshService,
		c.MeshSetting,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *MeshACLMutation:
		return c.MeshACL.mutate(ctx, m)
	case *MeshACLRevisionMutation:
		return c.MeshACLRevision.mutate(ctx, m)
	case *MeshNodeMutation:
		return c.MeshNode.mutate(ctx, m)
	case *MeshRelayMutation:
		return c.MeshRelay.mutate(ctx, m)
	case *MeshServiceMutation:
		return c.MeshService.mutate(ctx, m)
	case *MeshSettingMutation:
		return c.MeshSetting.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// MeshACLClient is a client for the MeshACL schema.
type MeshACLClient struct {
	config
}

// NewMeshACLClient returns a client for the MeshACL from the given config.
func NewMeshACLClient(c config) *MeshACLClient {
	return &MeshACLClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `meshacl.Hooks(f(g(h())))`.
func (c *MeshACLClient) Use(hooks ...Hook) {
	c.hooks.MeshACL = append(c.hooks.MeshACL, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `meshacl.Intercept(f(g(h())))`.
func (c *MeshACLClient) Intercept(interceptors ...Interceptor) {
	c.inters.MeshACL = append(c.inters.MeshACL, interceptors...)
}

// Create returns a builder for creating a MeshACL entity.
func (c *MeshACLClient) Create() *MeshACLCreate {
	mutation := newMeshACLMutation(c.config, OpCreate)
	return &MeshACLCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MeshACL entities.
func (c *MeshACLClient) CreateBulk(builders ...*MeshACLCreate) *MeshACLCreateBulk {
	return &MeshACLCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MeshACLClient) MapCreateBulk(slice any, setFunc func(*MeshACLCreate, int)) *MeshACLCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MeshACLCreateBulk{err: fmt.Errorf("calling to MeshACLClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MeshACLCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MeshACLCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MeshACL.
func (c *MeshACLClient) Update() *MeshACLUpdate {
	mutation := newMeshACLMutation(c.config, OpUpdate)
	return &MeshACLUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MeshACLClient) UpdateOne(_m *MeshACL) *MeshACLUpdateOne {
	mutation := newMeshACLMutation(c.config, OpUpdateOne, withMeshACL(_m))
	return &MeshACLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MeshACLClient) UpdateOneID(id int) *MeshACLUpdateOne {
	mutation := newMeshACLMutation(c.config, OpUpdateOne, withMeshACLID(id))
	return &MeshACLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MeshACL.
func (c *MeshACLClient) Delete() *MeshACLDelete {
	mutation := newMeshACLMutation(c.config, OpDelete)
	return &MeshACLDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MeshACLClient) DeleteOne(_m *MeshACL) *MeshACLDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MeshACLClient) DeleteOneID(id int) *MeshACLDeleteOne {
	builder := c.Delete().Where(meshacl.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MeshACLDeleteOne{builder}
}

// Query returns a query builder for MeshACL.
func (c *MeshACLClient) Query() *MeshACLQuery {
	return &MeshACLQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMeshACL},
		inters: c.Interceptors(),
	}
}

// Get returns a MeshACL entity by its id.
func (c *MeshACLClient) Get(ctx context.Context, id int) (*MeshACL, error) {
	return c.Query().Where(meshacl.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MeshACLClient) GetX(ctx context.Context, id int) *MeshACL {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MeshACLClient) Hooks() []Hook {
	return c.hooks.MeshACL
}

// Interceptors returns the client interceptors.
func (c *MeshACLClient) Interceptors() []Interceptor {
	return c.inters.MeshACL
}

func (c *MeshACLClient) mutate(ctx context.Context, m *MeshACLMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MeshACLCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MeshACLUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MeshACLUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MeshACLDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MeshACL mutation op: %q", m.Op())
	}
}

// MeshACLRevisionClient is a client for the MeshACLRevision schema.
type MeshACLRevisionClient struct {
	config
}

// NewMeshACLRevisionClient returns a client for the MeshACLRevision from the given config.
func NewMeshACLRevisionClient(c config) *MeshACLRevisionClient {
	return &MeshACLRevisionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `meshaclrevision.Hooks(f(g(h())))`.
func (c *MeshACLRevisionClient) Use(hooks ...Hook) {
	c.hooks.MeshACLRevision = append(c.hooks.MeshACLRevision, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `meshaclrevision.Intercept(f(g(h())))`.
func (c *MeshACLRevisionClient) Intercept(interceptors ...Interceptor) {
	c.inters.MeshACLRevision = append(c.inters.MeshACLRevision, interceptors...)
}

// Create returns a builder for creating a MeshACLRevision entity.
func (c *MeshACLRevisionClient) Create() *MeshACLRevisionCreate {
	mutation := newMeshACLRevisionMutation(c.config, OpCreate)
	return &MeshACLRevisionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MeshACLRevision entities.
func (c *MeshACLRevisionClient) CreateBulk(builders ...*MeshACLRevisionCreate) *MeshACLRevisionCreateBulk {
	return &MeshACLRevisionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MeshACLRevisionClient) MapCreateBulk(slice any, setFunc func(*MeshACLRevisionCreate, int)) *MeshACLRevisionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MeshACLRevisionCreateBulk{err: fmt.Errorf("calling to MeshACLRevisionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MeshACLRevisionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MeshACLRevisionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MeshACLRevision.
func (c *MeshACLRevisionClient) Update() *MeshACLRevisionUpdate {
	mutation := newMeshACLRevisionMutation(c.config, OpUpdate)
	return &MeshACLRevisionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MeshACLRevisionClient) UpdateOne(_m *MeshACLRevision) *MeshACLRevisionUpdateOne {
	mutation := newMeshACLRevisionMutation(c.config, OpUpdateOne, withMeshACLRevision(_m))
	return &MeshACLRevisionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MeshACLRevisionClient) UpdateOneID(id int) *MeshACLRevisionUpdateOne {
	mutation := newMeshACLRevisionMutation(c.config, OpUpdateOne, withMeshACLRevisionID(id))
	return &MeshACLRevisionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MeshACLRevision.
func (c *MeshACLRevisionClient) Delete() *MeshACLRevisionDelete {
	mutation := newMeshACLRevisionMutation(c.config, OpDelete)
	return &MeshACLRevisionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MeshACLRevisionClient) DeleteOne(_m *MeshACLRevision) *MeshACLRevisionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MeshACLRevisionClient) DeleteOneID(id int) *MeshACLRevisionDeleteOne {
	builder := c.Delete().Where(meshaclrevision.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MeshACLRevisionDeleteOne{builder}
}

// Query returns a query builder for MeshACLRevision.
func (c *MeshACLRevisionClient) Query() *MeshACLRevisionQuery {
	return &MeshACLRevisionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMeshACLRevision},
		inters: c.Interceptors(),
	}
}

// Get returns a MeshACLRevision entity by its id.
func (c *MeshACLRevisionClient) Get(ctx context.Context, id int) (*MeshACLRevision, error) {
	return c.Query().Where(meshaclrevision.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MeshACLRevisionClient) GetX(ctx context.Context, id int) *MeshACLRevision {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MeshACLRevisionClient) Hooks() []Hook {
	return c.hooks.MeshACLRevision
}

// Interceptors returns the client interceptors.
func (c *MeshACLRevisionClient) Interceptors() []Interceptor {
	return c.inters.MeshACLRevision
}

func (c *MeshACLRevisionClient) mutate(ctx context.Context, m *MeshACLRevisionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MeshACLRevisionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MeshACLRevisionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MeshACLRevisionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MeshACLRevisionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MeshACLRevision mutation op: %q", m.Op())
	}
}

// MeshNodeClient is a client for the MeshNode schema.
type MeshNodeClient struct {
	config
}

// NewMeshNodeClient returns a client for the MeshNode from the given config.
func NewMeshNodeClient(c config) *MeshNodeClient {
	return &MeshNodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `meshnode.Hooks(f(g(h())))`.
func (c *MeshNodeClient) Use(hooks ...Hook) {
	c.hooks.MeshNode = append(c.hooks.MeshNode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `meshnode.Intercept(f(g(h())))`.
func (c *MeshNodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.MeshNode = append(c.inters.MeshNode, interceptors...)
}

// Create returns a builder for creating a MeshNode entity.
func (c *MeshNodeClient) Create() *MeshNodeCreate {
	mutation := newMeshNodeMutation(c.config, OpCreate)
	return &MeshNodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MeshNode entities.
func (c *MeshNodeClient) CreateBulk(builders ...*MeshNodeCreate) *MeshNodeCreateBulk {
	return &MeshNodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MeshNodeClient) MapCreateBulk(slice any, setFunc func(*MeshNodeCreate, int)) *MeshNodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MeshNodeCreateBulk{err: fmt.Errorf("calling to MeshNodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MeshNodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MeshNodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MeshNode.
func (c *MeshNodeClient) Update() *MeshNodeUpdate {
	mutation := newMeshNodeMutation(c.config, OpUpdate)
	return &MeshNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MeshNodeClient) UpdateOne(_m *MeshNode) *MeshNodeUpdateOne {
	mutation := newMeshNodeMutation(c.config, OpUpdateOne, withMeshNode(_m))
	return &MeshNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MeshNodeClient) UpdateOneID(id int) *MeshNodeUpdateOne {
	mutation := newMeshNodeMutation(c.config, OpUpdateOne, withMeshNodeID(id))
	return &MeshNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MeshNode.
func (c *MeshNodeClient) Delete() *MeshNodeDelete {
	mutation := newMeshNodeMutation(c.config, OpDelete)
	return &MeshNodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MeshNodeClient) DeleteOne(_m *MeshNode) *MeshNodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MeshNodeClient) DeleteOneID(id int) *MeshNodeDeleteOne {
	builder := c.Delete().Where(meshnode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MeshNodeDeleteOne{builder}
}

// Query returns a query builder for MeshNode.
func (c *MeshNodeClient) Query() *MeshNodeQuery {
	return &MeshNodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMeshNode},
		inters: c.Interceptors(),
	}
}

// Get returns a MeshNode entity by its id.
func (c *MeshNodeClient) Get(ctx context.Context, id int) (*MeshNode, error) {
	return c.Query().Where(meshnode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MeshNodeClient) GetX(ctx context.Context, id int) *MeshNode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MeshNodeClient) Hooks() []Hook {
	return c.hooks.MeshNode
}

// Interceptors returns the client interceptors.
func (c *MeshNodeClient) Interceptors() []Interceptor {
	return c.inters.MeshNode
}

func (c *MeshNodeClient) mutate(ctx context.Context, m *MeshNodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MeshNodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MeshNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MeshNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MeshNodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MeshNode mutation op: %q", m.Op())
	}
}

// MeshRelayClient is a client for the MeshRelay schema.
type MeshRelayClient struct {
	config
}

// NewMeshRelayClient returns a client for the MeshRelay from the given config.
func NewMeshRelayClient(c config) *MeshRelayClient {
	return &MeshRelayClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `meshrelay.Hooks(f(g(h())))`.
func (c *MeshRelayClient) Use(hooks ...Hook) {
	c.hooks.MeshRelay = append(c.hooks.MeshRelay, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `meshrelay.Intercept(f(g(h())))`.
func (c *MeshRelayClient) Intercept(interceptors ...Interceptor) {
	c.inters.MeshRelay = append(c.inters.MeshRelay, interceptors...)
}

// Create returns a builder for creating a MeshRelay entity.
func (c *MeshRelayClient) Create() *MeshRelayCreate {
	mutation := newMeshRelayMutation(c.config, OpCreate)
	return &MeshRelayCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MeshRelay entities.
func (c *MeshRelayClient) CreateBulk(builders ...*MeshRelayCreate) *MeshRelayCreateBulk {
	return &MeshRelayCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MeshRelayClient) MapCreateBulk(slice any, setFunc func(*MeshRelayCreate, int)) *MeshRelayCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MeshRelayCreateBulk{err: fmt.Errorf("calling to MeshRelayClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MeshRelayCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MeshRelayCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MeshRelay.
func (c *MeshRelayClient) Update() *MeshRelayUpdate {
	mutation := newMeshRelayMutation(c.config, OpUpdate)
	return &MeshRelayUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MeshRelayClient) UpdateOne(_m *MeshRelay) *MeshRelayUpdateOne {
	mutation := newMeshRelayMutation(c.config, OpUpdateOne, withMeshRelay(_m))
	return &MeshRelayUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MeshRelayClient) UpdateOneID(id int) *MeshRelayUpdateOne {
	mutation := newMeshRelayMutation(c.config, OpUpdateOne, withMeshRelayID(id))
	return &MeshRelayUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MeshRelay.
func (c *MeshRelayClient) Delete() *MeshRelayDelete {
	mutation := newMeshRelayMutation(c.config, OpDelete)
	return &MeshRelayDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MeshRelayClient) DeleteOne(_m *MeshRelay) *MeshRelayDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MeshRelayClient) DeleteOneID(id int) *MeshRelayDeleteOne {
	builder := c.Delete().Where(meshrelay.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MeshRelayDeleteOne{builder}
}

// Query returns a query builder for MeshRelay.
func (c *MeshRelayClient) Query() *MeshRelayQuery {
	return &MeshRelayQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMeshRelay},
		inters: c.Interceptors(),
	}
}

// Get returns a MeshRelay entity by its id.
func (c *MeshRelayClient) Get(ctx context.Context, id int) (*MeshRelay, error) {
	return c.Query().Where(meshrelay.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MeshRelayClient) GetX(ctx context.Context, id int) *MeshRelay {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MeshRelayClient) Hooks() []Hook {
	return c.hooks.MeshRelay
}

// Interceptors returns the client interceptors.
func (c *MeshRelayClient) Interceptors() []Interceptor {
	return c.inters.MeshRelay
}

func (c *MeshRelayClient) mutate(ctx context.Context, m *MeshRelayMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MeshRelayCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MeshRelayUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MeshRelayUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MeshRelayDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MeshRelay mutation op: %q", m.Op())
	}
}

// MeshServiceClient is a client for the MeshService schema.
type MeshServiceClient struct {
	config
}

// NewMeshServiceClient returns a client for the MeshService from the given config.
func NewMeshServiceClient(c config) *MeshServiceClient {
	return &MeshServiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `meshservice.Hooks(f(g(h())))`.
func (c *MeshServiceClient) Use(hooks ...Hook) {
	c.hooks.MeshService = append(c.hooks.MeshService, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `meshservice.Intercept(f(g(h())))`.
func (c *MeshServiceClient) Intercept(interceptors ...Interceptor) {
	c.inters.MeshService = append(c.inters.MeshService, interceptors...)
}

// Create returns a builder for creating a MeshService entity.
func (c *MeshServiceClient) Create() *MeshServiceCreate {
	mutation := newMeshServiceMutation(c.config, OpCreate)
	return &MeshServiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MeshService entities.
func (c *MeshServiceClient) CreateBulk(builders ...*MeshServiceCreate) *MeshServiceCreateBulk {
	return &MeshServiceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MeshServiceClient) MapCreateBulk(slice any, setFunc func(*MeshServiceCreate, int)) *MeshServiceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MeshServiceCreateBulk{err: fmt.Errorf("calling to MeshServiceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MeshServiceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MeshServiceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MeshService.
func (c *MeshServiceClient) Update() *MeshServiceUpdate {
	mutation := newMeshServiceMutation(c.config, OpUpdate)
	return &MeshServiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MeshServiceClient) UpdateOne(_m *MeshService) *MeshServiceUpdateOne {
	mutation := newMeshServiceMutation(c.config, OpUpdateOne, withMeshService(_m))
	return &MeshServiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MeshServiceClient) UpdateOneID(id int) *MeshServiceUpdateOne {
	mutation := newMeshServiceMutation(c.config, OpUpdateOne, withMeshServiceID(id))
	return &MeshServiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MeshService.
func (c *MeshServiceClient) Delete() *MeshServiceDelete {
	mutation := newMeshServiceMutation(c.config, OpDelete)
	return &MeshServiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MeshServiceClient) DeleteOne(_m *MeshService) *MeshServiceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MeshServiceClient) DeleteOneID(id int) *MeshServiceDeleteOne {
	builder := c.Delete().Where(meshservice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MeshServiceDeleteOne{builder}
}

// Query returns a query builder for MeshService.
func (c *MeshServiceClient) Query() *MeshServiceQuery {
	return &MeshServiceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMeshService},
		inters: c.Interceptors(),
	}
}

// Get returns a MeshService entity by its id.
func (c *MeshServiceClient) Get(ctx context.Context, id int) (*MeshService, error) {
	return c.Query().Where(meshservice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MeshServiceClient) GetX(ctx context.Context, id int) *MeshService {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MeshServiceClient) Hooks() []Hook {
	return c.hooks.MeshService
}

// Interceptors returns the client interceptors.
func (c *MeshServiceClient) Interceptors() []Interceptor {
	return c.inters.MeshService
}

func (c *MeshServiceClient) mutate(ctx context.Context, m *MeshServiceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MeshServiceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MeshServiceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MeshServiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MeshServiceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MeshService mutation op: %q", m.Op())
	}
}

// MeshSettingClient is a client for the MeshSetting schema.
type MeshSettingClient struct {
	config
}

// NewMeshSettingClient returns a client for the MeshSetting from the given config.
func NewMeshSettingClient(c config) *MeshSettingClient {
	return &MeshSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `meshsetting.Hooks(f(g(h())))`.
func (c *MeshSettingClient) Use(hooks ...Hook) {
	c.hooks.MeshSetting = append(c.hooks.MeshSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `meshsetting.Intercept(f(g(h())))`.
func (c *MeshSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.MeshSetting = append(c.inters.MeshSetting, interceptors...)
}

// Create returns a builder for creating a MeshSetting entity.
func (c *MeshSettingClient) Create() *MeshSettingCreate {
	mutation := newMeshSettingMutation(c.config, OpCreate)
	return &MeshSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MeshSetting entities.
func (c *MeshSettingClient) CreateBulk(builders ...*MeshSettingCreate) *MeshSettingCreateBulk {
	return &MeshSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MeshSettingClient) MapCreateBulk(slice any, setFunc func(*MeshSettingCreate, int)) *MeshSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MeshSettingCreateBulk{err: fmt.Errorf("calling to MeshSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MeshSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MeshSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MeshSetting.
func (c *MeshSettingClient) Update() *MeshSettingUpdate {
	mutation := newMeshSettingMutation(c.config, OpUpdate)
	return &MeshSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MeshSettingClient) UpdateOne(_m *MeshSetting) *MeshSettingUpdateOne {
	mutation := newMeshSettingMutation(c.config, OpUpdateOne, withMeshSetting(_m))
	return &MeshSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MeshSettingClient) UpdateOneID(id int) *MeshSettingUpdateOne {
	mutation := newMeshSettingMutation(c.config, OpUpdateOne, withMeshSettingID(id))
	return &MeshSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MeshSetting.
func (c *MeshSettingClient) Delete() *MeshSettingDelete {
	mutation := newMeshSettingMutation(c.config, OpDelete)
	return &MeshSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MeshSettingClient) DeleteOne(_m *MeshSetting) *MeshSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MeshSettingClient) DeleteOneID(id int) *MeshSettingDeleteOne {
	builder := c.Delete().Where(meshsetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MeshSettingDeleteOne{builder}
}

// Query returns a query builder for MeshSetting.
func (c *MeshSettingClient) Query() *MeshSettingQuery {
	return &MeshSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMeshSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a MeshSetting entity by its id.
func (c *MeshSettingClient) Get(ctx context.Context, id int) (*MeshSetting, error) {
	return c.Query().Where(meshsetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MeshSettingClient) GetX(ctx context.Context, id int) *MeshSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MeshSettingClient) Hooks() []Hook {
	return c.hooks.MeshSetting
}

// Interceptors returns the client interceptors.
func (c *MeshSettingClient) Interceptors() []Interceptor {
	return c.inters.MeshSetting
}

func (c *MeshSettingClient) mutate(ctx context.Context, m *MeshSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MeshSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MeshSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MeshSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MeshSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MeshSetting mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		MeshACL, MeshACLRevision, MeshNode, MeshRelay, MeshService,
		MeshSetting []ent.Hook
	}
	inters struct {
		MeshACL, MeshACLRevision, MeshNode, MeshRelay, MeshService,
		MeshSetting []ent.Interceptor
	}
)
