// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshacl"
)

// MeshACLCreate is the builder for creating a MeshACL entity.
type MeshACLCreate struct {
	config
	mutation *MeshACLMutation
	hooks    []Hook
}

// SetMeshnetID sets the "meshnet_id" field.
func (_c *MeshACLCreate) SetMeshnetID(v int64) *MeshACLCreate {
	_c.mutation.SetMeshnetID(v)
	return _c
}

// SetPolicyJSON sets the "policy_json" field.
func (_c *MeshACLCreate) SetPolicyJSON(v string) *MeshACLCreate {
	_c.mutation.SetPolicyJSON(v)
	return _c
}

// SetNillablePolicyJSON sets the "policy_json" field if the given value is not nil.
func (_c *MeshACLCreate) SetNillablePolicyJSON(v *string) *MeshACLCreate {
	if v != nil {
		_c.SetPolicyJSON(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MeshACLCreate) SetUpdatedAt(v time.Time) *MeshACLCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MeshACLCreate) SetNillableUpdatedAt(v *time.Time) *MeshACLCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the MeshACLMutation object of the builder.
func (_c *MeshACLCreate) Mutation() *MeshACLMutation {
	return _c.mutation
}

// Save creates the MeshACL in the database.
func (_c *MeshACLCreate) Save(ctx context.Context) (*MeshACL, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MeshACLCreate) SaveX(ctx context.Context) *MeshACL {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MeshACLCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MeshACLCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MeshACLCreate) defaults() {
	if _, ok := _c.mutation.PolicyJSON(); !ok {
		v := meshacl.DefaultPolicyJSON
		_c.mutation.SetPolicyJSON(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := meshacl.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MeshACLCreate) check() error {
	if _, ok := _c.mutation.MeshnetID(); !ok {
		return &ValidationError{Name: "meshnet_id", err: errors.New(`ent: missing required field "MeshACL.meshnet_id"`)}
	}
	if _, ok := _c.mutation.PolicyJSON(); !ok {
		return &ValidationError{Name: "policy_json", err: errors.New(`ent: missing required field "MeshACL.policy_json"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MeshACL.updated_at"`)}
	}
	return nil
}

func (_c *MeshACLCreate) sqlSave(ctx context.Context) (*MeshACL, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MeshACLCreate) createSpec() (*MeshACL, *sqlgraph.CreateSpec) {
	var (
		_node = &MeshACL{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(meshacl.Table, sqlgraph.NewFieldSpec(meshacl.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MeshnetID(); ok {
		_spec.SetField(meshacl.FieldMeshnetID, field.TypeInt64, value)
		_node.MeshnetID = value
	}
	if value, ok := _c.mutation.PolicyJSON(); ok {
		_spec.SetField(meshacl.FieldPolicyJSON, field.TypeString, value)
		_node.PolicyJSON = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(meshacl.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MeshACLCreateBulk is the builder for creating many MeshACL entities in bulk.
type MeshACLCreateBulk struct {
	config
	err      error
	builders []*MeshACLCreate
}

// Save creates the MeshACL entities in the database.
func (_c *MeshACLCreateBulk) Save(ctx context.Context) ([]*MeshACL, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MeshACL, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshACLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MeshACLCreateBulk) SaveX(ctx context.Context) []*MeshACL {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MeshACLCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MeshACLCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
