// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshauthkey"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshAuthKeyQuery is the builder for querying MeshAuthKey entities.
type MeshAuthKeyQuery struct {
	config
	ctx        *QueryContext
	order      []meshauthkey.OrderOption
	inters     []Interceptor
	predicates []predicate.MeshAuthKey
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeshAuthKeyQuery builder.
func (makq *MeshAuthKeyQuery) Where(ps ...predicate.MeshAuthKey) *MeshAuthKeyQuery {
	makq.predicates = append(makq.predicates, ps...)
	return makq
}

// Limit the number of records to be returned by this query.
func (makq *MeshAuthKeyQuery) Limit(limit int) *MeshAuthKeyQuery {
	makq.ctx.Limit = &limit
	return makq
}

// Offset to start from.
func (makq *MeshAuthKeyQuery) Offset(offset int) *MeshAuthKeyQuery {
	makq.ctx.Offset = &offset
	return makq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (makq *MeshAuthKeyQuery) Unique(unique bool) *MeshAuthKeyQuery {
	makq.ctx.Unique = &unique
	return makq
}

// Order specifies how the records should be ordered.
func (makq *MeshAuthKeyQuery) Order(o ...meshauthkey.OrderOption) *MeshAuthKeyQuery {
	makq.order = append(makq.order, o...)
	return makq
}

// First returns the first MeshAuthKey entity from the query.
// Returns a *NotFoundError when no MeshAuthKey was found.
func (makq *MeshAuthKeyQuery) First(ctx context.Context) (*MeshAuthKey, error) {
	nodes, err := makq.Limit(1).All(setContextOp(ctx, makq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meshauthkey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) FirstX(ctx context.Context) *MeshAuthKey {
	node, err := makq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MeshAuthKey ID from the query.
// Returns a *NotFoundError when no MeshAuthKey ID was found.
func (makq *MeshAuthKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = makq.Limit(1).IDs(setContextOp(ctx, makq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meshauthkey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := makq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MeshAuthKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MeshAuthKey entity is found.
// Returns a *NotFoundError when no MeshAuthKey entities are found.
func (makq *MeshAuthKeyQuery) Only(ctx context.Context) (*MeshAuthKey, error) {
	nodes, err := makq.Limit(2).All(setContextOp(ctx, makq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meshauthkey.Label}
	default:
		return nil, &NotSingularError{meshauthkey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) OnlyX(ctx context.Context) *MeshAuthKey {
	node, err := makq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MeshAuthKey ID in the query.
// Returns a *NotSingularError when more than one MeshAuthKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (makq *MeshAuthKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = makq.Limit(2).IDs(setContextOp(ctx, makq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meshauthkey.Label}
	default:
		err = &NotSingularError{meshauthkey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := makq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MeshAuthKeys.
func (makq *MeshAuthKeyQuery) All(ctx context.Context) ([]*MeshAuthKey, error) {
	ctx = setContextOp(ctx, makq.ctx, ent.OpQueryAll)
	if err := makq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MeshAuthKey, *MeshAuthKeyQuery]()
	return withInterceptors[[]*MeshAuthKey](ctx, makq, qr, makq.inters)
}

// AllX is like All, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) AllX(ctx context.Context) []*MeshAuthKey {
	nodes, err := makq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MeshAuthKey IDs.
func (makq *MeshAuthKeyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if makq.ctx.Unique == nil && makq.path != nil {
		makq.Unique(true)
	}
	ctx = setContextOp(ctx, makq.ctx, ent.OpQueryIDs)
	if err = makq.Select(meshauthkey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := makq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (makq *MeshAuthKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, makq.ctx, ent.OpQueryCount)
	if err := makq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, makq, querierCount[*MeshAuthKeyQuery](), makq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) CountX(ctx context.Context) int {
	count, err := makq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (makq *MeshAuthKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, makq.ctx, ent.OpQueryExist)
	switch _, err := makq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (makq *MeshAuthKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := makq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeshAuthKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (makq *MeshAuthKeyQuery) Clone() *MeshAuthKeyQuery {
	if makq == nil {
		return nil
	}
	return &MeshAuthKeyQuery{
		config:     makq.config,
		ctx:        makq.ctx.Clone(),
		order:      append([]meshauthkey.OrderOption{}, makq.order...),
		inters:     append([]Interceptor{}, makq.inters...),
		predicates: append([]predicate.MeshAuthKey{}, makq.predicates...),
		// clone intermediate query.
		sql:  makq.sql.Clone(),
		path: makq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MeshAuthKey.Query().
//		GroupBy(meshauthkey.FieldMeshnetID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (makq *MeshAuthKeyQuery) GroupBy(field string, fields ...string) *MeshAuthKeyGroupBy {
	makq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeshAuthKeyGroupBy{build: makq}
	grbuild.flds = &makq.ctx.Fields
	grbuild.label = meshauthkey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//	}
//
//	client.MeshAuthKey.Query().
//		Select(meshauthkey.FieldMeshnetID).
//		Scan(ctx, &v)
func (makq *MeshAuthKeyQuery) Select(fields ...string) *MeshAuthKeySelect {
	makq.ctx.Fields = append(makq.ctx.Fields, fields...)
	sbuild := &MeshAuthKeySelect{MeshAuthKeyQuery: makq}
	sbuild.label = meshauthkey.Label
	sbuild.flds, sbuild.scan = &makq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeshAuthKeySelect configured with the given aggregations.
func (makq *MeshAuthKeyQuery) Aggregate(fns ...AggregateFunc) *MeshAuthKeySelect {
	return makq.Select().Aggregate(fns...)
}

func (makq *MeshAuthKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range makq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, makq); err != nil {
				return err
			}
		}
	}
	for _, f := range makq.ctx.Fields {
		if !meshauthkey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if makq.path != nil {
		prev, err := makq.path(ctx)
		if err != nil {
			return err
		}
		makq.sql = prev
	}
	return nil
}

func (makq *MeshAuthKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MeshAuthKey, error) {
	var (
		nodes = []*MeshAuthKey{}
		_spec = makq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MeshAuthKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MeshAuthKey{config: makq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, makq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (makq *MeshAuthKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := makq.querySpec()
	_spec.Node.Columns = makq.ctx.Fields
	if len(makq.ctx.Fields) > 0 {
		_spec.Unique = makq.ctx.Unique != nil && *makq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, makq.driver, _spec)
}

func (makq *MeshAuthKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meshauthkey.Table, meshauthkey.Columns, sqlgraph.NewFieldSpec(meshauthkey.FieldID, field.TypeInt))
	_spec.From = makq.sql
	if unique := makq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if makq.path != nil {
		_spec.Unique = true
	}
	if fields := makq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshauthkey.FieldID)
		for i := range fields {
			if fields[i] != meshauthkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := makq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := makq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := makq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := makq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (makq *MeshAuthKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(makq.driver.Dialect())
	t1 := builder.Table(meshauthkey.Table)
	columns := makq.ctx.Fields
	if len(columns) == 0 {
		columns = meshauthkey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if makq.sql != nil {
		selector = makq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if makq.ctx.Unique != nil && *makq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range makq.predicates {
		p(selector)
	}
	for _, p := range makq.order {
		p(selector)
	}
	if offset := makq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := makq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeshAuthKeyGroupBy is the group-by builder for MeshAuthKey entities.
type MeshAuthKeyGroupBy struct {
	selector
	build *MeshAuthKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (makgb *MeshAuthKeyGroupBy) Aggregate(fns ...AggregateFunc) *MeshAuthKeyGroupBy {
	makgb.fns = append(makgb.fns, fns...)
	return makgb
}

// Scan applies the selector query and scans the result into the given value.
func (makgb *MeshAuthKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, makgb.build.ctx, ent.OpQueryGroupBy)
	if err := makgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshAuthKeyQuery, *MeshAuthKeyGroupBy](ctx, makgb.build, makgb, makgb.build.inters, v)
}

func (makgb *MeshAuthKeyGroupBy) sqlScan(ctx context.Context, root *MeshAuthKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(makgb.fns))
	for _, fn := range makgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*makgb.flds)+len(makgb.fns))
		for _, f := range *makgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*makgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := makgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeshAuthKeySelect is the builder for selecting fields of MeshAuthKey entities.
type MeshAuthKeySelect struct {
	*MeshAuthKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (maks *MeshAuthKeySelect) Aggregate(fns ...AggregateFunc) *MeshAuthKeySelect {
	maks.fns = append(maks.fns, fns...)
	return maks
}

// Scan applies the selector query and scans the result into the given value.
func (maks *MeshAuthKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, maks.ctx, ent.OpQuerySelect)
	if err := maks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshAuthKeyQuery, *MeshAuthKeySelect](ctx, maks.MeshAuthKeyQuery, maks, maks.inters, v)
}

func (maks *MeshAuthKeySelect) sqlScan(ctx context.Context, root *MeshAuthKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(maks.fns))
	for _, fn := range maks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*maks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := maks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
