// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshtunnelusage"
)

// MeshTunnelUsageCreate is the builder for creating a MeshTunnelUsage entity.
type MeshTunnelUsageCreate struct {
	config
	mutation *MeshTunnelUsageMutation
	hooks    []Hook
}

// SetMeshnetID sets the "meshnet_id" field.
func (mtuc *MeshTunnelUsageCreate) SetMeshnetID(i int64) *MeshTunnelUsageCreate {
	mtuc.mutation.SetMeshnetID(i)
	return mtuc
}

// SetNodeID sets the "node_id" field.
func (mtuc *MeshTunnelUsageCreate) SetNodeID(i int64) *MeshTunnelUsageCreate {
	mtuc.mutation.SetNodeID(i)
	return mtuc
}

// SetName sets the "name" field.
func (mtuc *MeshTunnelUsageCreate) SetName(s string) *MeshTunnelUsageCreate {
	mtuc.mutation.SetName(s)
	return mtuc
}

// SetHour sets the "hour" field.
func (mtuc *MeshTunnelUsageCreate) SetHour(t time.Time) *MeshTunnelUsageCreate {
	mtuc.mutation.SetHour(t)
	return mtuc
}

// SetBytesIn sets the "bytes_in" field.
func (mtuc *MeshTunnelUsageCreate) SetBytesIn(i int64) *MeshTunnelUsageCreate {
	mtuc.mutation.SetBytesIn(i)
	return mtuc
}

// SetNillableBytesIn sets the "bytes_in" field if the given value is not nil.
func (mtuc *MeshTunnelUsageCreate) SetNillableBytesIn(i *int64) *MeshTunnelUsageCreate {
	if i != nil {
		mtuc.SetBytesIn(*i)
	}
	return mtuc
}

// SetBytesOut sets the "bytes_out" field.
func (mtuc *MeshTunnelUsageCreate) SetBytesOut(i int64) *MeshTunnelUsageCreate {
	mtuc.mutation.SetBytesOut(i)
	return mtuc
}

// SetNillableBytesOut sets the "bytes_out" field if the given value is not nil.
func (mtuc *MeshTunnelUsageCreate) SetNillableBytesOut(i *int64) *MeshTunnelUsageCreate {
	if i != nil {
		mtuc.SetBytesOut(*i)
	}
	return mtuc
}

// Mutation returns the MeshTunnelUsageMutation object of the builder.
func (mtuc *MeshTunnelUsageCreate) Mutation() *MeshTunnelUsageMutation {
	return mtuc.mutation
}

// Save creates the MeshTunnelUsage in the database.
func (mtuc *MeshTunnelUsageCreate) Save(ctx context.Context) (*MeshTunnelUsage, error) {
	mtuc.defaults()
	return withHooks(ctx, mtuc.sqlSave, mtuc.mutation, mtuc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mtuc *MeshTunnelUsageCreate) SaveX(ctx context.Context) *MeshTunnelUsage {
	v, err := mtuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mtuc *MeshTunnelUsageCreate) Exec(ctx context.Context) error {
	_, err := mtuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtuc *MeshTunnelUsageCreate) ExecX(ctx context.Context) {
	if err := mtuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mtuc *MeshTunnelUsageCreate) defaults() {
	if _, ok := mtuc.mutation.BytesIn(); !ok {
		v := meshtunnelusage.DefaultBytesIn
		mtuc.mutation.SetBytesIn(v)
	}
	if _, ok := mtuc.mutation.BytesOut(); !ok {
		v := meshtunnelusage.DefaultBytesOut
		mtuc.mutation.SetBytesOut(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtuc *MeshTunnelUsageCreate) check() error {
	if _, ok := mtuc.mutation.MeshnetID(); !ok {
		return &ValidationError{Name: "meshnet_id", err: errors.New(`ent: missing required field "MeshTunnelUsage.meshnet_id"`)}
	}
	if _, ok := mtuc.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "MeshTunnelUsage.node_id"`)}
	}
	if _, ok := mtuc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MeshTunnelUsage.name"`)}
	}
	if _, ok := mtuc.mutation.Hour(); !ok {
		return &ValidationError{Name: "hour", err: errors.New(`ent: missing required field "MeshTunnelUsage.hour"`)}
	}
	if _, ok := mtuc.mutation.BytesIn(); !ok {
		return &ValidationError{Name: "bytes_in", err: errors.New(`ent: missing required field "MeshTunnelUsage.bytes_in"`)}
	}
	if _, ok := mtuc.mutation.BytesOut(); !ok {
		return &ValidationError{Name: "bytes_out", err: errors.New(`ent: missing required field "MeshTunnelUsage.bytes_out"`)}
	}
	return nil
}

func (mtuc *MeshTunnelUsageCreate) sqlSave(ctx context.Context) (*MeshTunnelUsage, error) {
	if err := mtuc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mtuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mtuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mtuc.mutation.id = &_node.ID
	mtuc.mutation.done = true
	return _node, nil
}

func (mtuc *MeshTunnelUsageCreate) createSpec() (*MeshTunnelUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &MeshTunnelUsage{config: mtuc.config}
		_spec = sqlgraph.NewCreateSpec(meshtunnelusage.Table, sqlgraph.NewFieldSpec(meshtunnelusage.FieldID, field.TypeInt))
	)
	if value, ok := mtuc.mutation.MeshnetID(); ok {
		_spec.SetField(meshtunnelusage.FieldMeshnetID, field.TypeInt64, value)
		_node.MeshnetID = value
	}
	if value, ok := mtuc.mutation.NodeID(); ok {
		_spec.SetField(meshtunnelusage.FieldNodeID, field.TypeInt64, value)
		_node.NodeID = value
	}
	if value, ok := mtuc.mutation.Name(); ok {
		_spec.SetField(meshtunnelusage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mtuc.mutation.Hour(); ok {
		_spec.SetField(meshtunnelusage.FieldHour, field.TypeTime, value)
		_node.Hour = value
	}
	if value, ok := mtuc.mutation.BytesIn(); ok {
		_spec.SetField(meshtunnelusage.FieldBytesIn, field.TypeInt64, value)
		_node.BytesIn = value
	}
	if value, ok := mtuc.mutation.BytesOut(); ok {
		_spec.SetField(meshtunnelusage.FieldBytesOut, field.TypeInt64, value)
		_node.BytesOut = value
	}
	return _node, _spec
}

// MeshTunnelUsageCreateBulk is the builder for creating many MeshTunnelUsage entities in bulk.
type MeshTunnelUsageCreateBulk struct {
	config
	err      error
	builders []*MeshTunnelUsageCreate
}

// Save creates the MeshTunnelUsage entities in the database.
func (mtucb *MeshTunnelUsageCreateBulk) Save(ctx context.Context) ([]*MeshTunnelUsage, error) {
	if mtucb.err != nil {
		return nil, mtucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mtucb.builders))
	nodes := make([]*MeshTunnelUsage, len(mtucb.builders))
	mutators := make([]Mutator, len(mtucb.builders))
	for i := range mtucb.builders {
		func(i int, root context.Context) {
			builder := mtucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshTunnelUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mtucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mtucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mtucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mtucb *MeshTunnelUsageCreateBulk) SaveX(ctx context.Context) []*MeshTunnelUsage {
	v, err := mtucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mtucb *MeshTunnelUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := mtucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtucb *MeshTunnelUsageCreateBulk) ExecX(ctx context.Context) {
	if err := mtucb.Exec(ctx); err != nil {
		panic(err)
	}
}
