// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshauthkey"
)

// MeshAuthKey is the model entity for the MeshAuthKey schema.
type MeshAuthKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// the meshnet a device this key admits joins
	MeshnetID int64 `json:"meshnet_id,omitempty"`
	// hex SHA-256 of the key; the key itself is never stored
	Hash string `json:"hash,omitempty"`
	// the key's first characters, to recognise it in a list
	Prefix string `json:"prefix,omitempty"`
	// JSON array of ACL tags stamped on every device it admits
	TagsJSON string `json:"tags_json,omitempty"`
	// how many devices it may admit; 0 = any number
	MaxUses int `json:"max_uses,omitempty"`
	// how many devices it has admitted
	Uses int `json:"uses,omitempty"`
	// after this it admits no new device; NULL = never
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// revoked: refused outright; NULL = not revoked
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// the operator's own label
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MeshAuthKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case meshauthkey.FieldID, meshauthkey.FieldMeshnetID, meshauthkey.FieldMaxUses, meshauthkey.FieldUses:
			values[i] = new(sql.NullInt64)
		case meshauthkey.FieldHash, meshauthkey.FieldPrefix, meshauthkey.FieldTagsJSON, meshauthkey.FieldNote:
			values[i] = new(sql.NullString)
		case meshauthkey.FieldExpiresAt, meshauthkey.FieldRevokedAt, meshauthkey.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MeshAuthKey fields.
func (mak *MeshAuthKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case meshauthkey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mak.ID = int(value.Int64)
		case meshauthkey.FieldMeshnetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field meshnet_id", values[i])
			} else if value.Valid {
				mak.MeshnetID = value.Int64
			}
		case meshauthkey.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				mak.Hash = value.String
			}
		case meshauthkey.FieldPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prefix", values[i])
			} else if value.Valid {
				mak.Prefix = value.String
			}
		case meshauthkey.FieldTagsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags_json", values[i])
			} else if value.Valid {
				mak.TagsJSON = value.String
			}
		case meshauthkey.FieldMaxUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses", values[i])
			} else if value.Valid {
				mak.MaxUses = int(value.Int64)
			}
		case meshauthkey.FieldUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uses", values[i])
			} else if value.Valid {
				mak.Uses = int(value.Int64)
			}
		case meshauthkey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				mak.ExpiresAt = new(time.Time)
				*mak.ExpiresAt = value.Time
			}
		case meshauthkey.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				mak.RevokedAt = new(time.Time)
				*mak.RevokedAt = value.Time
			}
		case meshauthkey.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				mak.Note = value.String
			}
		case meshauthkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				mak.CreatedAt = value.Time
			}
		default:
			mak.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MeshAuthKey.
// This includes values selected through modifiers, order, etc.
func (mak *MeshAuthKey) Value(name string) (ent.Value, error) {
	return mak.selectValues.Get(name)
}

// Update returns a builder for updating this MeshAuthKey.
// Note that you need to call MeshAuthKey.Unwrap() before calling this method if this MeshAuthKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (mak *MeshAuthKey) Update() *MeshAuthKeyUpdateOne {
	return NewMeshAuthKeyClient(mak.config).UpdateOne(mak)
}

// Unwrap unwraps the MeshAuthKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mak *MeshAuthKey) Unwrap() *MeshAuthKey {
	_tx, ok := mak.config.driver.(*txDriver)
	if !ok {
		panic("ent: MeshAuthKey is not a transactional entity")
	}
	mak.config.driver = _tx.drv
	return mak
}

// String implements the fmt.Stringer.
func (mak *MeshAuthKey) String() string {
	var builder strings.Builder
	builder.WriteString("MeshAuthKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mak.ID))
	builder.WriteString("meshnet_id=")
	builder.WriteString(fmt.Sprintf("%v", mak.MeshnetID))
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(mak.Hash)
	builder.WriteString(", ")
	builder.WriteString("prefix=")
	builder.WriteString(mak.Prefix)
	builder.WriteString(", ")
	builder.WriteString("tags_json=")
	builder.WriteString(mak.TagsJSON)
	builder.WriteString(", ")
	builder.WriteString("max_uses=")
	builder.WriteString(fmt.Sprintf("%v", mak.MaxUses))
	builder.WriteString(", ")
	builder.WriteString("uses=")
	builder.WriteString(fmt.Sprintf("%v", mak.Uses))
	builder.WriteString(", ")
	if v := mak.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := mak.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(mak.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(mak.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MeshAuthKeys is a parsable slice of MeshAuthKey.
type MeshAuthKeys []*MeshAuthKey
