// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshtunnel"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshTunnelQuery is the builder for querying MeshTunnel entities.
type MeshTunnelQuery struct {
	config
	ctx        *QueryContext
	order      []meshtunnel.OrderOption
	inters     []Interceptor
	predicates []predicate.MeshTunnel
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeshTunnelQuery builder.
func (mtq *MeshTunnelQuery) Where(ps ...predicate.MeshTunnel) *MeshTunnelQuery {
	mtq.predicates = append(mtq.predicates, ps...)
	return mtq
}

// Limit the number of records to be returned by this query.
func (mtq *MeshTunnelQuery) Limit(limit int) *MeshTunnelQuery {
	mtq.ctx.Limit = &limit
	return mtq
}

// Offset to start from.
func (mtq *MeshTunnelQuery) Offset(offset int) *MeshTunnelQuery {
	mtq.ctx.Offset = &offset
	return mtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mtq *MeshTunnelQuery) Unique(unique bool) *MeshTunnelQuery {
	mtq.ctx.Unique = &unique
	return mtq
}

// Order specifies how the records should be ordered.
func (mtq *MeshTunnelQuery) Order(o ...meshtunnel.OrderOption) *MeshTunnelQuery {
	mtq.order = append(mtq.order, o...)
	return mtq
}

// First returns the first MeshTunnel entity from the query.
// Returns a *NotFoundError when no MeshTunnel was found.
func (mtq *MeshTunnelQuery) First(ctx context.Context) (*MeshTunnel, error) {
	nodes, err := mtq.Limit(1).All(setContextOp(ctx, mtq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meshtunnel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mtq *MeshTunnelQuery) FirstX(ctx context.Context) *MeshTunnel {
	node, err := mtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MeshTunnel ID from the query.
// Returns a *NotFoundError when no MeshTunnel ID was found.
func (mtq *MeshTunnelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mtq.Limit(1).IDs(setContextOp(ctx, mtq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meshtunnel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mtq *MeshTunnelQuery) FirstIDX(ctx context.Context) int {
	id, err := mtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MeshTunnel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MeshTunnel entity is found.
// Returns a *NotFoundError when no MeshTunnel entities are found.
func (mtq *MeshTunnelQuery) Only(ctx context.Context) (*MeshTunnel, error) {
	nodes, err := mtq.Limit(2).All(setContextOp(ctx, mtq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meshtunnel.Label}
	default:
		return nil, &NotSingularError{meshtunnel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mtq *MeshTunnelQuery) OnlyX(ctx context.Context) *MeshTunnel {
	node, err := mtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MeshTunnel ID in the query.
// Returns a *NotSingularError when more than one MeshTunnel ID is found.
// Returns a *NotFoundError when no entities are found.
func (mtq *MeshTunnelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mtq.Limit(2).IDs(setContextOp(ctx, mtq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meshtunnel.Label}
	default:
		err = &NotSingularError{meshtunnel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mtq *MeshTunnelQuery) OnlyIDX(ctx context.Context) int {
	id, err := mtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MeshTunnels.
func (mtq *MeshTunnelQuery) All(ctx context.Context) ([]*MeshTunnel, error) {
	ctx = setContextOp(ctx, mtq.ctx, ent.OpQueryAll)
	if err := mtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MeshTunnel, *MeshTunnelQuery]()
	return withInterceptors[[]*MeshTunnel](ctx, mtq, qr, mtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mtq *MeshTunnelQuery) AllX(ctx context.Context) []*MeshTunnel {
	nodes, err := mtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MeshTunnel IDs.
func (mtq *MeshTunnelQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mtq.ctx.Unique == nil && mtq.path != nil {
		mtq.Unique(true)
	}
	ctx = setContextOp(ctx, mtq.ctx, ent.OpQueryIDs)
	if err = mtq.Select(meshtunnel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mtq *MeshTunnelQuery) IDsX(ctx context.Context) []int {
	ids, err := mtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mtq *MeshTunnelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mtq.ctx, ent.OpQueryCount)
	if err := mtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mtq, querierCount[*MeshTunnelQuery](), mtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mtq *MeshTunnelQuery) CountX(ctx context.Context) int {
	count, err := mtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mtq *MeshTunnelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mtq.ctx, ent.OpQueryExist)
	switch _, err := mtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mtq *MeshTunnelQuery) ExistX(ctx context.Context) bool {
	exist, err := mtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeshTunnelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mtq *MeshTunnelQuery) Clone() *MeshTunnelQuery {
	if mtq == nil {
		return nil
	}
	return &MeshTunnelQuery{
		config:     mtq.config,
		ctx:        mtq.ctx.Clone(),
		order:      append([]meshtunnel.OrderOption{}, mtq.order...),
		inters:     append([]Interceptor{}, mtq.inters...),
		predicates: append([]predicate.MeshTunnel{}, mtq.predicates...),
		// clone intermediate query.
		sql:  mtq.sql.Clone(),
		path: mtq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MeshTunnel.Query().
//		GroupBy(meshtunnel.FieldMeshnetID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mtq *MeshTunnelQuery) GroupBy(field string, fields ...string) *MeshTunnelGroupBy {
	mtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeshTunnelGroupBy{build: mtq}
	grbuild.flds = &mtq.ctx.Fields
	grbuild.label = meshtunnel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//	}
//
//	client.MeshTunnel.Query().
//		Select(meshtunnel.FieldMeshnetID).
//		Scan(ctx, &v)
func (mtq *MeshTunnelQuery) Select(fields ...string) *MeshTunnelSelect {
	mtq.ctx.Fields = append(mtq.ctx.Fields, fields...)
	sbuild := &MeshTunnelSelect{MeshTunnelQuery: mtq}
	sbuild.label = meshtunnel.Label
	sbuild.flds, sbuild.scan = &mtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeshTunnelSelect configured with the given aggregations.
func (mtq *MeshTunnelQuery) Aggregate(fns ...AggregateFunc) *MeshTunnelSelect {
	return mtq.Select().Aggregate(fns...)
}

func (mtq *MeshTunnelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mtq); err != nil {
				return err
			}
		}
	}
	for _, f := range mtq.ctx.Fields {
		if !meshtunnel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mtq.path != nil {
		prev, err := mtq.path(ctx)
		if err != nil {
			return err
		}
		mtq.sql = prev
	}
	return nil
}

func (mtq *MeshTunnelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MeshTunnel, error) {
	var (
		nodes = []*MeshTunnel{}
		_spec = mtq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MeshTunnel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MeshTunnel{config: mtq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mtq *MeshTunnelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mtq.querySpec()
	_spec.Node.Columns = mtq.ctx.Fields
	if len(mtq.ctx.Fields) > 0 {
		_spec.Unique = mtq.ctx.Unique != nil && *mtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mtq.driver, _spec)
}

func (mtq *MeshTunnelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meshtunnel.Table, meshtunnel.Columns, sqlgraph.NewFieldSpec(meshtunnel.FieldID, field.TypeInt))
	_spec.From = mtq.sql
	if unique := mtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mtq.path != nil {
		_spec.Unique = true
	}
	if fields := mtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshtunnel.FieldID)
		for i := range fields {
			if fields[i] != meshtunnel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mtq *MeshTunnelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mtq.driver.Dialect())
	t1 := builder.Table(meshtunnel.Table)
	columns := mtq.ctx.Fields
	if len(columns) == 0 {
		columns = meshtunnel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mtq.sql != nil {
		selector = mtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mtq.ctx.Unique != nil && *mtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mtq.predicates {
		p(selector)
	}
	for _, p := range mtq.order {
		p(selector)
	}
	if offset := mtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeshTunnelGroupBy is the group-by builder for MeshTunnel entities.
type MeshTunnelGroupBy struct {
	selector
	build *MeshTunnelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mtgb *MeshTunnelGroupBy) Aggregate(fns ...AggregateFunc) *MeshTunnelGroupBy {
	mtgb.fns = append(mtgb.fns, fns...)
	return mtgb
}

// Scan applies the selector query and scans the result into the given value.
func (mtgb *MeshTunnelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mtgb.build.ctx, ent.OpQueryGroupBy)
	if err := mtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshTunnelQuery, *MeshTunnelGroupBy](ctx, mtgb.build, mtgb, mtgb.build.inters, v)
}

func (mtgb *MeshTunnelGroupBy) sqlScan(ctx context.Context, root *MeshTunnelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mtgb.fns))
	for _, fn := range mtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mtgb.flds)+len(mtgb.fns))
		for _, f := range *mtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeshTunnelSelect is the builder for selecting fields of MeshTunnel entities.
type MeshTunnelSelect struct {
	*MeshTunnelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mts *MeshTunnelSelect) Aggregate(fns ...AggregateFunc) *MeshTunnelSelect {
	mts.fns = append(mts.fns, fns...)
	return mts
}

// Scan applies the selector query and scans the result into the given value.
func (mts *MeshTunnelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mts.ctx, ent.OpQuerySelect)
	if err := mts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshTunnelQuery, *MeshTunnelSelect](ctx, mts.MeshTunnelQuery, mts, mts.inters, v)
}

func (mts *MeshTunnelSelect) sqlScan(ctx context.Context, root *MeshTunnelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mts.fns))
	for _, fn := range mts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
