// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshtunnel"
)

// MeshTunnelCreate is the builder for creating a MeshTunnel entity.
type MeshTunnelCreate struct {
	config
	mutation *MeshTunnelMutation
	hooks    []Hook
}

// SetMeshnetID sets the "meshnet_id" field.
func (mtc *MeshTunnelCreate) SetMeshnetID(i int64) *MeshTunnelCreate {
	mtc.mutation.SetMeshnetID(i)
	return mtc
}

// SetNodeID sets the "node_id" field.
func (mtc *MeshTunnelCreate) SetNodeID(i int64) *MeshTunnelCreate {
	mtc.mutation.SetNodeID(i)
	return mtc
}

// SetName sets the "name" field.
func (mtc *MeshTunnelCreate) SetName(s string) *MeshTunnelCreate {
	mtc.mutation.SetName(s)
	return mtc
}

// SetType sets the "type" field.
func (mtc *MeshTunnelCreate) SetType(s string) *MeshTunnelCreate {
	mtc.mutation.SetType(s)
	return mtc
}

// SetPublicAddr sets the "public_addr" field.
func (mtc *MeshTunnelCreate) SetPublicAddr(s string) *MeshTunnelCreate {
	mtc.mutation.SetPublicAddr(s)
	return mtc
}

// SetNillablePublicAddr sets the "public_addr" field if the given value is not nil.
func (mtc *MeshTunnelCreate) SetNillablePublicAddr(s *string) *MeshTunnelCreate {
	if s != nil {
		mtc.SetPublicAddr(*s)
	}
	return mtc
}

// SetLocalAddr sets the "local_addr" field.
func (mtc *MeshTunnelCreate) SetLocalAddr(s string) *MeshTunnelCreate {
	mtc.mutation.SetLocalAddr(s)
	return mtc
}

// SetNillableLocalAddr sets the "local_addr" field if the given value is not nil.
func (mtc *MeshTunnelCreate) SetNillableLocalAddr(s *string) *MeshTunnelCreate {
	if s != nil {
		mtc.SetLocalAddr(*s)
	}
	return mtc
}

// SetStatus sets the "status" field.
func (mtc *MeshTunnelCreate) SetStatus(s string) *MeshTunnelCreate {
	mtc.mutation.SetStatus(s)
	return mtc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (mtc *MeshTunnelCreate) SetNillableStatus(s *string) *MeshTunnelCreate {
	if s != nil {
		mtc.SetStatus(*s)
	}
	return mtc
}

// SetFirstSeen sets the "first_seen" field.
func (mtc *MeshTunnelCreate) SetFirstSeen(t time.Time) *MeshTunnelCreate {
	mtc.mutation.SetFirstSeen(t)
	return mtc
}

// SetReportedAt sets the "reported_at" field.
func (mtc *MeshTunnelCreate) SetReportedAt(t time.Time) *MeshTunnelCreate {
	mtc.mutation.SetReportedAt(t)
	return mtc
}

// Mutation returns the MeshTunnelMutation object of the builder.
func (mtc *MeshTunnelCreate) Mutation() *MeshTunnelMutation {
	return mtc.mutation
}

// Save creates the MeshTunnel in the database.
func (mtc *MeshTunnelCreate) Save(ctx context.Context) (*MeshTunnel, error) {
	mtc.defaults()
	return withHooks(ctx, mtc.sqlSave, mtc.mutation, mtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mtc *MeshTunnelCreate) SaveX(ctx context.Context) *MeshTunnel {
	v, err := mtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mtc *MeshTunnelCreate) Exec(ctx context.Context) error {
	_, err := mtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtc *MeshTunnelCreate) ExecX(ctx context.Context) {
	if err := mtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mtc *MeshTunnelCreate) defaults() {
	if _, ok := mtc.mutation.PublicAddr(); !ok {
		v := meshtunnel.DefaultPublicAddr
		mtc.mutation.SetPublicAddr(v)
	}
	if _, ok := mtc.mutation.LocalAddr(); !ok {
		v := meshtunnel.DefaultLocalAddr
		mtc.mutation.SetLocalAddr(v)
	}
	if _, ok := mtc.mutation.Status(); !ok {
		v := meshtunnel.DefaultStatus
		mtc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtc *MeshTunnelCreate) check() error {
	if _, ok := mtc.mutation.MeshnetID(); !ok {
		return &ValidationError{Name: "meshnet_id", err: errors.New(`ent: missing required field "MeshTunnel.meshnet_id"`)}
	}
	if _, ok := mtc.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "MeshTunnel.node_id"`)}
	}
	if _, ok := mtc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MeshTunnel.name"`)}
	}
	if _, ok := mtc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MeshTunnel.type"`)}
	}
	if _, ok := mtc.mutation.PublicAddr(); !ok {
		return &ValidationError{Name: "public_addr", err: errors.New(`ent: missing required field "MeshTunnel.public_addr"`)}
	}
	if _, ok := mtc.mutation.LocalAddr(); !ok {
		return &ValidationError{Name: "local_addr", err: errors.New(`ent: missing required field "MeshTunnel.local_addr"`)}
	}
	if _, ok := mtc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MeshTunnel.status"`)}
	}
	if _, ok := mtc.mutation.FirstSeen(); !ok {
		return &ValidationError{Name: "first_seen", err: errors.New(`ent: missing required field "MeshTunnel.first_seen"`)}
	}
	if _, ok := mtc.mutation.ReportedAt(); !ok {
		return &ValidationError{Name: "reported_at", err: errors.New(`ent: missing required field "MeshTunnel.reported_at"`)}
	}
	return nil
}

func (mtc *MeshTunnelCreate) sqlSave(ctx context.Context) (*MeshTunnel, error) {
	if err := mtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mtc.mutation.id = &_node.ID
	mtc.mutation.done = true
	return _node, nil
}

func (mtc *MeshTunnelCreate) createSpec() (*MeshTunnel, *sqlgraph.CreateSpec) {
	var (
		_node = &MeshTunnel{config: mtc.config}
		_spec = sqlgraph.NewCreateSpec(meshtunnel.Table, sqlgraph.NewFieldSpec(meshtunnel.FieldID, field.TypeInt))
	)
	if value, ok := mtc.mutation.MeshnetID(); ok {
		_spec.SetField(meshtunnel.FieldMeshnetID, field.TypeInt64, value)
		_node.MeshnetID = value
	}
	if value, ok := mtc.mutation.NodeID(); ok {
		_spec.SetField(meshtunnel.FieldNodeID, field.TypeInt64, value)
		_node.NodeID = value
	}
	if value, ok := mtc.mutation.Name(); ok {
		_spec.SetField(meshtunnel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mtc.mutation.GetType(); ok {
		_spec.SetField(meshtunnel.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := mtc.mutation.PublicAddr(); ok {
		_spec.SetField(meshtunnel.FieldPublicAddr, field.TypeString, value)
		_node.PublicAddr = value
	}
	if value, ok := mtc.mutation.LocalAddr(); ok {
		_spec.SetField(meshtunnel.FieldLocalAddr, field.TypeString, value)
		_node.LocalAddr = value
	}
	if value, ok := mtc.mutation.Status(); ok {
		_spec.SetField(meshtunnel.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := mtc.mutation.FirstSeen(); ok {
		_spec.SetField(meshtunnel.FieldFirstSeen, field.TypeTime, value)
		_node.FirstSeen = value
	}
	if value, ok := mtc.mutation.ReportedAt(); ok {
		_spec.SetField(meshtunnel.FieldReportedAt, field.TypeTime, value)
		_node.ReportedAt = value
	}
	return _node, _spec
}

// MeshTunnelCreateBulk is the builder for creating many MeshTunnel entities in bulk.
type MeshTunnelCreateBulk struct {
	config
	err      error
	builders []*MeshTunnelCreate
}

// Save creates the MeshTunnel entities in the database.
func (mtcb *MeshTunnelCreateBulk) Save(ctx context.Context) ([]*MeshTunnel, error) {
	if mtcb.err != nil {
		return nil, mtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mtcb.builders))
	nodes := make([]*MeshTunnel, len(mtcb.builders))
	mutators := make([]Mutator, len(mtcb.builders))
	for i := range mtcb.builders {
		func(i int, root context.Context) {
			builder := mtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshTunnelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mtcb *MeshTunnelCreateBulk) SaveX(ctx context.Context) []*MeshTunnel {
	v, err := mtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mtcb *MeshTunnelCreateBulk) Exec(ctx context.Context) error {
	_, err := mtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtcb *MeshTunnelCreateBulk) ExecX(ctx context.Context) {
	if err := mtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
