// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshconnrecord"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshConnRecordUpdate is the builder for updating MeshConnRecord entities.
type MeshConnRecordUpdate struct {
	config
	hooks    []Hook
	mutation *MeshConnRecordMutation
}

// Where appends a list predicates to the MeshConnRecordUpdate builder.
func (mcru *MeshConnRecordUpdate) Where(ps ...predicate.MeshConnRecord) *MeshConnRecordUpdate {
	mcru.mutation.Where(ps...)
	return mcru
}

// SetMeshnetID sets the "meshnet_id" field.
func (mcru *MeshConnRecordUpdate) SetMeshnetID(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetMeshnetID()
	mcru.mutation.SetMeshnetID(i)
	return mcru
}

// SetNillableMeshnetID sets the "meshnet_id" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableMeshnetID(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetMeshnetID(*i)
	}
	return mcru
}

// AddMeshnetID adds i to the "meshnet_id" field.
func (mcru *MeshConnRecordUpdate) AddMeshnetID(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddMeshnetID(i)
	return mcru
}

// SetSrcNodeID sets the "src_node_id" field.
func (mcru *MeshConnRecordUpdate) SetSrcNodeID(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetSrcNodeID()
	mcru.mutation.SetSrcNodeID(i)
	return mcru
}

// SetNillableSrcNodeID sets the "src_node_id" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableSrcNodeID(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetSrcNodeID(*i)
	}
	return mcru
}

// AddSrcNodeID adds i to the "src_node_id" field.
func (mcru *MeshConnRecordUpdate) AddSrcNodeID(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddSrcNodeID(i)
	return mcru
}

// SetDstNodeID sets the "dst_node_id" field.
func (mcru *MeshConnRecordUpdate) SetDstNodeID(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetDstNodeID()
	mcru.mutation.SetDstNodeID(i)
	return mcru
}

// SetNillableDstNodeID sets the "dst_node_id" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableDstNodeID(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetDstNodeID(*i)
	}
	return mcru
}

// AddDstNodeID adds i to the "dst_node_id" field.
func (mcru *MeshConnRecordUpdate) AddDstNodeID(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddDstNodeID(i)
	return mcru
}

// SetHour sets the "hour" field.
func (mcru *MeshConnRecordUpdate) SetHour(t time.Time) *MeshConnRecordUpdate {
	mcru.mutation.SetHour(t)
	return mcru
}

// SetNillableHour sets the "hour" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableHour(t *time.Time) *MeshConnRecordUpdate {
	if t != nil {
		mcru.SetHour(*t)
	}
	return mcru
}

// SetBytesTx sets the "bytes_tx" field.
func (mcru *MeshConnRecordUpdate) SetBytesTx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetBytesTx()
	mcru.mutation.SetBytesTx(i)
	return mcru
}

// SetNillableBytesTx sets the "bytes_tx" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableBytesTx(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetBytesTx(*i)
	}
	return mcru
}

// AddBytesTx adds i to the "bytes_tx" field.
func (mcru *MeshConnRecordUpdate) AddBytesTx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddBytesTx(i)
	return mcru
}

// SetBytesRx sets the "bytes_rx" field.
func (mcru *MeshConnRecordUpdate) SetBytesRx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetBytesRx()
	mcru.mutation.SetBytesRx(i)
	return mcru
}

// SetNillableBytesRx sets the "bytes_rx" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableBytesRx(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetBytesRx(*i)
	}
	return mcru
}

// AddBytesRx adds i to the "bytes_rx" field.
func (mcru *MeshConnRecordUpdate) AddBytesRx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddBytesRx(i)
	return mcru
}

// SetPath sets the "path" field.
func (mcru *MeshConnRecordUpdate) SetPath(s string) *MeshConnRecordUpdate {
	mcru.mutation.SetPath(s)
	return mcru
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillablePath(s *string) *MeshConnRecordUpdate {
	if s != nil {
		mcru.SetPath(*s)
	}
	return mcru
}

// SetRelayBytesTx sets the "relay_bytes_tx" field.
func (mcru *MeshConnRecordUpdate) SetRelayBytesTx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetRelayBytesTx()
	mcru.mutation.SetRelayBytesTx(i)
	return mcru
}

// SetNillableRelayBytesTx sets the "relay_bytes_tx" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableRelayBytesTx(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetRelayBytesTx(*i)
	}
	return mcru
}

// AddRelayBytesTx adds i to the "relay_bytes_tx" field.
func (mcru *MeshConnRecordUpdate) AddRelayBytesTx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddRelayBytesTx(i)
	return mcru
}

// SetRelayBytesRx sets the "relay_bytes_rx" field.
func (mcru *MeshConnRecordUpdate) SetRelayBytesRx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.ResetRelayBytesRx()
	mcru.mutation.SetRelayBytesRx(i)
	return mcru
}

// SetNillableRelayBytesRx sets the "relay_bytes_rx" field if the given value is not nil.
func (mcru *MeshConnRecordUpdate) SetNillableRelayBytesRx(i *int64) *MeshConnRecordUpdate {
	if i != nil {
		mcru.SetRelayBytesRx(*i)
	}
	return mcru
}

// AddRelayBytesRx adds i to the "relay_bytes_rx" field.
func (mcru *MeshConnRecordUpdate) AddRelayBytesRx(i int64) *MeshConnRecordUpdate {
	mcru.mutation.AddRelayBytesRx(i)
	return mcru
}

// SetUpdatedAt sets the "updated_at" field.
func (mcru *MeshConnRecordUpdate) SetUpdatedAt(t time.Time) *MeshConnRecordUpdate {
	mcru.mutation.SetUpdatedAt(t)
	return mcru
}

// Mutation returns the MeshConnRecordMutation object of the builder.
func (mcru *MeshConnRecordUpdate) Mutation() *MeshConnRecordMutation {
	return mcru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mcru *MeshConnRecordUpdate) Save(ctx context.Context) (int, error) {
	mcru.defaults()
	return withHooks(ctx, mcru.sqlSave, mcru.mutation, mcru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mcru *MeshConnRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := mcru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mcru *MeshConnRecordUpdate) Exec(ctx context.Context) error {
	_, err := mcru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcru *MeshConnRecordUpdate) ExecX(ctx context.Context) {
	if err := mcru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mcru *MeshConnRecordUpdate) defaults() {
	if _, ok := mcru.mutation.UpdatedAt(); !ok {
		v := meshconnrecord.UpdateDefaultUpdatedAt()
		mcru.mutation.SetUpdatedAt(v)
	}
}

func (mcru *MeshConnRecordUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(meshconnrecord.Table, meshconnrecord.Columns, sqlgraph.NewFieldSpec(meshconnrecord.FieldID, field.TypeInt))
	if ps := mcru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mcru.mutation.MeshnetID(); ok {
		_spec.SetField(meshconnrecord.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedMeshnetID(); ok {
		_spec.AddField(meshconnrecord.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.SrcNodeID(); ok {
		_spec.SetField(meshconnrecord.FieldSrcNodeID, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedSrcNodeID(); ok {
		_spec.AddField(meshconnrecord.FieldSrcNodeID, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.DstNodeID(); ok {
		_spec.SetField(meshconnrecord.FieldDstNodeID, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedDstNodeID(); ok {
		_spec.AddField(meshconnrecord.FieldDstNodeID, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.Hour(); ok {
		_spec.SetField(meshconnrecord.FieldHour, field.TypeTime, value)
	}
	if value, ok := mcru.mutation.BytesTx(); ok {
		_spec.SetField(meshconnrecord.FieldBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedBytesTx(); ok {
		_spec.AddField(meshconnrecord.FieldBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.BytesRx(); ok {
		_spec.SetField(meshconnrecord.FieldBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedBytesRx(); ok {
		_spec.AddField(meshconnrecord.FieldBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.Path(); ok {
		_spec.SetField(meshconnrecord.FieldPath, field.TypeString, value)
	}
	if value, ok := mcru.mutation.RelayBytesTx(); ok {
		_spec.SetField(meshconnrecord.FieldRelayBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedRelayBytesTx(); ok {
		_spec.AddField(meshconnrecord.FieldRelayBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.RelayBytesRx(); ok {
		_spec.SetField(meshconnrecord.FieldRelayBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.AddedRelayBytesRx(); ok {
		_spec.AddField(meshconnrecord.FieldRelayBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcru.mutation.UpdatedAt(); ok {
		_spec.SetField(meshconnrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mcru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meshconnrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mcru.mutation.done = true
	return n, nil
}

// MeshConnRecordUpdateOne is the builder for updating a single MeshConnRecord entity.
type MeshConnRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MeshConnRecordMutation
}

// SetMeshnetID sets the "meshnet_id" field.
func (mcruo *MeshConnRecordUpdateOne) SetMeshnetID(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetMeshnetID()
	mcruo.mutation.SetMeshnetID(i)
	return mcruo
}

// SetNillableMeshnetID sets the "meshnet_id" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableMeshnetID(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetMeshnetID(*i)
	}
	return mcruo
}

// AddMeshnetID adds i to the "meshnet_id" field.
func (mcruo *MeshConnRecordUpdateOne) AddMeshnetID(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddMeshnetID(i)
	return mcruo
}

// SetSrcNodeID sets the "src_node_id" field.
func (mcruo *MeshConnRecordUpdateOne) SetSrcNodeID(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetSrcNodeID()
	mcruo.mutation.SetSrcNodeID(i)
	return mcruo
}

// SetNillableSrcNodeID sets the "src_node_id" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableSrcNodeID(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetSrcNodeID(*i)
	}
	return mcruo
}

// AddSrcNodeID adds i to the "src_node_id" field.
func (mcruo *MeshConnRecordUpdateOne) AddSrcNodeID(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddSrcNodeID(i)
	return mcruo
}

// SetDstNodeID sets the "dst_node_id" field.
func (mcruo *MeshConnRecordUpdateOne) SetDstNodeID(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetDstNodeID()
	mcruo.mutation.SetDstNodeID(i)
	return mcruo
}

// SetNillableDstNodeID sets the "dst_node_id" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableDstNodeID(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetDstNodeID(*i)
	}
	return mcruo
}

// AddDstNodeID adds i to the "dst_node_id" field.
func (mcruo *MeshConnRecordUpdateOne) AddDstNodeID(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddDstNodeID(i)
	return mcruo
}

// SetHour sets the "hour" field.
func (mcruo *MeshConnRecordUpdateOne) SetHour(t time.Time) *MeshConnRecordUpdateOne {
	mcruo.mutation.SetHour(t)
	return mcruo
}

// SetNillableHour sets the "hour" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableHour(t *time.Time) *MeshConnRecordUpdateOne {
	if t != nil {
		mcruo.SetHour(*t)
	}
	return mcruo
}

// SetBytesTx sets the "bytes_tx" field.
func (mcruo *MeshConnRecordUpdateOne) SetBytesTx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetBytesTx()
	mcruo.mutation.SetBytesTx(i)
	return mcruo
}

// SetNillableBytesTx sets the "bytes_tx" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableBytesTx(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetBytesTx(*i)
	}
	return mcruo
}

// AddBytesTx adds i to the "bytes_tx" field.
func (mcruo *MeshConnRecordUpdateOne) AddBytesTx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddBytesTx(i)
	return mcruo
}

// SetBytesRx sets the "bytes_rx" field.
func (mcruo *MeshConnRecordUpdateOne) SetBytesRx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetBytesRx()
	mcruo.mutation.SetBytesRx(i)
	return mcruo
}

// SetNillableBytesRx sets the "bytes_rx" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableBytesRx(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetBytesRx(*i)
	}
	return mcruo
}

// AddBytesRx adds i to the "bytes_rx" field.
func (mcruo *MeshConnRecordUpdateOne) AddBytesRx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddBytesRx(i)
	return mcruo
}

// SetPath sets the "path" field.
func (mcruo *MeshConnRecordUpdateOne) SetPath(s string) *MeshConnRecordUpdateOne {
	mcruo.mutation.SetPath(s)
	return mcruo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillablePath(s *string) *MeshConnRecordUpdateOne {
	if s != nil {
		mcruo.SetPath(*s)
	}
	return mcruo
}

// SetRelayBytesTx sets the "relay_bytes_tx" field.
func (mcruo *MeshConnRecordUpdateOne) SetRelayBytesTx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetRelayBytesTx()
	mcruo.mutation.SetRelayBytesTx(i)
	return mcruo
}

// SetNillableRelayBytesTx sets the "relay_bytes_tx" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableRelayBytesTx(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetRelayBytesTx(*i)
	}
	return mcruo
}

// AddRelayBytesTx adds i to the "relay_bytes_tx" field.
func (mcruo *MeshConnRecordUpdateOne) AddRelayBytesTx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddRelayBytesTx(i)
	return mcruo
}

// SetRelayBytesRx sets the "relay_bytes_rx" field.
func (mcruo *MeshConnRecordUpdateOne) SetRelayBytesRx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.ResetRelayBytesRx()
	mcruo.mutation.SetRelayBytesRx(i)
	return mcruo
}

// SetNillableRelayBytesRx sets the "relay_bytes_rx" field if the given value is not nil.
func (mcruo *MeshConnRecordUpdateOne) SetNillableRelayBytesRx(i *int64) *MeshConnRecordUpdateOne {
	if i != nil {
		mcruo.SetRelayBytesRx(*i)
	}
	return mcruo
}

// AddRelayBytesRx adds i to the "relay_bytes_rx" field.
func (mcruo *MeshConnRecordUpdateOne) AddRelayBytesRx(i int64) *MeshConnRecordUpdateOne {
	mcruo.mutation.AddRelayBytesRx(i)
	return mcruo
}

// SetUpdatedAt sets the "updated_at" field.
func (mcruo *MeshConnRecordUpdateOne) SetUpdatedAt(t time.Time) *MeshConnRecordUpdateOne {
	mcruo.mutation.SetUpdatedAt(t)
	return mcruo
}

// Mutation returns the MeshConnRecordMutation object of the builder.
func (mcruo *MeshConnRecordUpdateOne) Mutation() *MeshConnRecordMutation {
	return mcruo.mutation
}

// Where appends a list predicates to the MeshConnRecordUpdate builder.
func (mcruo *MeshConnRecordUpdateOne) Where(ps ...predicate.MeshConnRecord) *MeshConnRecordUpdateOne {
	mcruo.mutation.Where(ps...)
	return mcruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mcruo *MeshConnRecordUpdateOne) Select(field string, fields ...string) *MeshConnRecordUpdateOne {
	mcruo.fields = append([]string{field}, fields...)
	return mcruo
}

// Save executes the query and returns the updated MeshConnRecord entity.
func (mcruo *MeshConnRecordUpdateOne) Save(ctx context.Context) (*MeshConnRecord, error) {
	mcruo.defaults()
	return withHooks(ctx, mcruo.sqlSave, mcruo.mutation, mcruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mcruo *MeshConnRecordUpdateOne) SaveX(ctx context.Context) *MeshConnRecord {
	node, err := mcruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mcruo *MeshConnRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := mcruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcruo *MeshConnRecordUpdateOne) ExecX(ctx context.Context) {
	if err := mcruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mcruo *MeshConnRecordUpdateOne) defaults() {
	if _, ok := mcruo.mutation.UpdatedAt(); !ok {
		v := meshconnrecord.UpdateDefaultUpdatedAt()
		mcruo.mutation.SetUpdatedAt(v)
	}
}

func (mcruo *MeshConnRecordUpdateOne) sqlSave(ctx context.Context) (_node *MeshConnRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(meshconnrecord.Table, meshconnrecord.Columns, sqlgraph.NewFieldSpec(meshconnrecord.FieldID, field.TypeInt))
	id, ok := mcruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MeshConnRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mcruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshconnrecord.FieldID)
		for _, f := range fields {
			if !meshconnrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != meshconnrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mcruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mcruo.mutation.MeshnetID(); ok {
		_spec.SetField(meshconnrecord.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedMeshnetID(); ok {
		_spec.AddField(meshconnrecord.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.SrcNodeID(); ok {
		_spec.SetField(meshconnrecord.FieldSrcNodeID, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedSrcNodeID(); ok {
		_spec.AddField(meshconnrecord.FieldSrcNodeID, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.DstNodeID(); ok {
		_spec.SetField(meshconnrecord.FieldDstNodeID, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedDstNodeID(); ok {
		_spec.AddField(meshconnrecord.FieldDstNodeID, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.Hour(); ok {
		_spec.SetField(meshconnrecord.FieldHour, field.TypeTime, value)
	}
	if value, ok := mcruo.mutation.BytesTx(); ok {
		_spec.SetField(meshconnrecord.FieldBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedBytesTx(); ok {
		_spec.AddField(meshconnrecord.FieldBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.BytesRx(); ok {
		_spec.SetField(meshconnrecord.FieldBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedBytesRx(); ok {
		_spec.AddField(meshconnrecord.FieldBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.Path(); ok {
		_spec.SetField(meshconnrecord.FieldPath, field.TypeString, value)
	}
	if value, ok := mcruo.mutation.RelayBytesTx(); ok {
		_spec.SetField(meshconnrecord.FieldRelayBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedRelayBytesTx(); ok {
		_spec.AddField(meshconnrecord.FieldRelayBytesTx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.RelayBytesRx(); ok {
		_spec.SetField(meshconnrecord.FieldRelayBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.AddedRelayBytesRx(); ok {
		_spec.AddField(meshconnrecord.FieldRelayBytesRx, field.TypeInt64, value)
	}
	if value, ok := mcruo.mutation.UpdatedAt(); ok {
		_spec.SetField(meshconnrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &MeshConnRecord{config: mcruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mcruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meshconnrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mcruo.mutation.done = true
	return _node, nil
}
