// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshacl"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshACLUpdate is the builder for updating MeshACL entities.
type MeshACLUpdate struct {
	config
	hooks    []Hook
	mutation *MeshACLMutation
}

// Where appends a list predicates to the MeshACLUpdate builder.
func (mau *MeshACLUpdate) Where(ps ...predicate.MeshACL) *MeshACLUpdate {
	mau.mutation.Where(ps...)
	return mau
}

// SetMeshnetID sets the "meshnet_id" field.
func (mau *MeshACLUpdate) SetMeshnetID(i int64) *MeshACLUpdate {
	mau.mutation.ResetMeshnetID()
	mau.mutation.SetMeshnetID(i)
	return mau
}

// SetNillableMeshnetID sets the "meshnet_id" field if the given value is not nil.
func (mau *MeshACLUpdate) SetNillableMeshnetID(i *int64) *MeshACLUpdate {
	if i != nil {
		mau.SetMeshnetID(*i)
	}
	return mau
}

// AddMeshnetID adds i to the "meshnet_id" field.
func (mau *MeshACLUpdate) AddMeshnetID(i int64) *MeshACLUpdate {
	mau.mutation.AddMeshnetID(i)
	return mau
}

// SetPolicyJSON sets the "policy_json" field.
func (mau *MeshACLUpdate) SetPolicyJSON(s string) *MeshACLUpdate {
	mau.mutation.SetPolicyJSON(s)
	return mau
}

// SetNillablePolicyJSON sets the "policy_json" field if the given value is not nil.
func (mau *MeshACLUpdate) SetNillablePolicyJSON(s *string) *MeshACLUpdate {
	if s != nil {
		mau.SetPolicyJSON(*s)
	}
	return mau
}

// SetUpdatedAt sets the "updated_at" field.
func (mau *MeshACLUpdate) SetUpdatedAt(t time.Time) *MeshACLUpdate {
	mau.mutation.SetUpdatedAt(t)
	return mau
}

// Mutation returns the MeshACLMutation object of the builder.
func (mau *MeshACLUpdate) Mutation() *MeshACLMutation {
	return mau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mau *MeshACLUpdate) Save(ctx context.Context) (int, error) {
	mau.defaults()
	return withHooks(ctx, mau.sqlSave, mau.mutation, mau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mau *MeshACLUpdate) SaveX(ctx context.Context) int {
	affected, err := mau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mau *MeshACLUpdate) Exec(ctx context.Context) error {
	_, err := mau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mau *MeshACLUpdate) ExecX(ctx context.Context) {
	if err := mau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mau *MeshACLUpdate) defaults() {
	if _, ok := mau.mutation.UpdatedAt(); !ok {
		v := meshacl.UpdateDefaultUpdatedAt()
		mau.mutation.SetUpdatedAt(v)
	}
}

func (mau *MeshACLUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(meshacl.Table, meshacl.Columns, sqlgraph.NewFieldSpec(meshacl.FieldID, field.TypeInt))
	if ps := mau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mau.mutation.MeshnetID(); ok {
		_spec.SetField(meshacl.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mau.mutation.AddedMeshnetID(); ok {
		_spec.AddField(meshacl.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mau.mutation.PolicyJSON(); ok {
		_spec.SetField(meshacl.FieldPolicyJSON, field.TypeString, value)
	}
	if value, ok := mau.mutation.UpdatedAt(); ok {
		_spec.SetField(meshacl.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meshacl.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mau.mutation.done = true
	return n, nil
}

// MeshACLUpdateOne is the builder for updating a single MeshACL entity.
type MeshACLUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MeshACLMutation
}

// SetMeshnetID sets the "meshnet_id" field.
func (mauo *MeshACLUpdateOne) SetMeshnetID(i int64) *MeshACLUpdateOne {
	mauo.mutation.ResetMeshnetID()
	mauo.mutation.SetMeshnetID(i)
	return mauo
}

// SetNillableMeshnetID sets the "meshnet_id" field if the given value is not nil.
func (mauo *MeshACLUpdateOne) SetNillableMeshnetID(i *int64) *MeshACLUpdateOne {
	if i != nil {
		mauo.SetMeshnetID(*i)
	}
	return mauo
}

// AddMeshnetID adds i to the "meshnet_id" field.
func (mauo *MeshACLUpdateOne) AddMeshnetID(i int64) *MeshACLUpdateOne {
	mauo.mutation.AddMeshnetID(i)
	return mauo
}

// SetPolicyJSON sets the "policy_json" field.
func (mauo *MeshACLUpdateOne) SetPolicyJSON(s string) *MeshACLUpdateOne {
	mauo.mutation.SetPolicyJSON(s)
	return mauo
}

// SetNillablePolicyJSON sets the "policy_json" field if the given value is not nil.
func (mauo *MeshACLUpdateOne) SetNillablePolicyJSON(s *string) *MeshACLUpdateOne {
	if s != nil {
		mauo.SetPolicyJSON(*s)
	}
	return mauo
}

// SetUpdatedAt sets the "updated_at" field.
func (mauo *MeshACLUpdateOne) SetUpdatedAt(t time.Time) *MeshACLUpdateOne {
	mauo.mutation.SetUpdatedAt(t)
	return mauo
}

// Mutation returns the MeshACLMutation object of the builder.
func (mauo *MeshACLUpdateOne) Mutation() *MeshACLMutation {
	return mauo.mutation
}

// Where appends a list predicates to the MeshACLUpdate builder.
func (mauo *MeshACLUpdateOne) Where(ps ...predicate.MeshACL) *MeshACLUpdateOne {
	mauo.mutation.Where(ps...)
	return mauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mauo *MeshACLUpdateOne) Select(field string, fields ...string) *MeshACLUpdateOne {
	mauo.fields = append([]string{field}, fields...)
	return mauo
}

// Save executes the query and returns the updated MeshACL entity.
func (mauo *MeshACLUpdateOne) Save(ctx context.Context) (*MeshACL, error) {
	mauo.defaults()
	return withHooks(ctx, mauo.sqlSave, mauo.mutation, mauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mauo *MeshACLUpdateOne) SaveX(ctx context.Context) *MeshACL {
	node, err := mauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mauo *MeshACLUpdateOne) Exec(ctx context.Context) error {
	_, err := mauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mauo *MeshACLUpdateOne) ExecX(ctx context.Context) {
	if err := mauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mauo *MeshACLUpdateOne) defaults() {
	if _, ok := mauo.mutation.UpdatedAt(); !ok {
		v := meshacl.UpdateDefaultUpdatedAt()
		mauo.mutation.SetUpdatedAt(v)
	}
}

func (mauo *MeshACLUpdateOne) sqlSave(ctx context.Context) (_node *MeshACL, err error) {
	_spec := sqlgraph.NewUpdateSpec(meshacl.Table, meshacl.Columns, sqlgraph.NewFieldSpec(meshacl.FieldID, field.TypeInt))
	id, ok := mauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MeshACL.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshacl.FieldID)
		for _, f := range fields {
			if !meshacl.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != meshacl.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mauo.mutation.MeshnetID(); ok {
		_spec.SetField(meshacl.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mauo.mutation.AddedMeshnetID(); ok {
		_spec.AddField(meshacl.FieldMeshnetID, field.TypeInt64, value)
	}
	if value, ok := mauo.mutation.PolicyJSON(); ok {
		_spec.SetField(meshacl.FieldPolicyJSON, field.TypeString, value)
	}
	if value, ok := mauo.mutation.UpdatedAt(); ok {
		_spec.SetField(meshacl.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &MeshACL{config: mauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meshacl.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mauo.mutation.done = true
	return _node, nil
}
