// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshservice"
)

// MeshServiceCreate is the builder for creating a MeshService entity.
type MeshServiceCreate struct {
	config
	mutation *MeshServiceMutation
	hooks    []Hook
}

// SetMeshnetID sets the "meshnet_id" field.
func (msc *MeshServiceCreate) SetMeshnetID(i int64) *MeshServiceCreate {
	msc.mutation.SetMeshnetID(i)
	return msc
}

// SetNodeID sets the "node_id" field.
func (msc *MeshServiceCreate) SetNodeID(i int64) *MeshServiceCreate {
	msc.mutation.SetNodeID(i)
	return msc
}

// SetName sets the "name" field.
func (msc *MeshServiceCreate) SetName(s string) *MeshServiceCreate {
	msc.mutation.SetName(s)
	return msc
}

// SetProto sets the "proto" field.
func (msc *MeshServiceCreate) SetProto(s string) *MeshServiceCreate {
	msc.mutation.SetProto(s)
	return msc
}

// SetNillableProto sets the "proto" field if the given value is not nil.
func (msc *MeshServiceCreate) SetNillableProto(s *string) *MeshServiceCreate {
	if s != nil {
		msc.SetProto(*s)
	}
	return msc
}

// SetPort sets the "port" field.
func (msc *MeshServiceCreate) SetPort(i int) *MeshServiceCreate {
	msc.mutation.SetPort(i)
	return msc
}

// SetTarget sets the "target" field.
func (msc *MeshServiceCreate) SetTarget(s string) *MeshServiceCreate {
	msc.mutation.SetTarget(s)
	return msc
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (msc *MeshServiceCreate) SetNillableTarget(s *string) *MeshServiceCreate {
	if s != nil {
		msc.SetTarget(*s)
	}
	return msc
}

// SetNote sets the "note" field.
func (msc *MeshServiceCreate) SetNote(s string) *MeshServiceCreate {
	msc.mutation.SetNote(s)
	return msc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (msc *MeshServiceCreate) SetNillableNote(s *string) *MeshServiceCreate {
	if s != nil {
		msc.SetNote(*s)
	}
	return msc
}

// SetSource sets the "source" field.
func (msc *MeshServiceCreate) SetSource(s string) *MeshServiceCreate {
	msc.mutation.SetSource(s)
	return msc
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (msc *MeshServiceCreate) SetNillableSource(s *string) *MeshServiceCreate {
	if s != nil {
		msc.SetSource(*s)
	}
	return msc
}

// SetApproved sets the "approved" field.
func (msc *MeshServiceCreate) SetApproved(b bool) *MeshServiceCreate {
	msc.mutation.SetApproved(b)
	return msc
}

// SetNillableApproved sets the "approved" field if the given value is not nil.
func (msc *MeshServiceCreate) SetNillableApproved(b *bool) *MeshServiceCreate {
	if b != nil {
		msc.SetApproved(*b)
	}
	return msc
}

// SetCreatedAt sets the "created_at" field.
func (msc *MeshServiceCreate) SetCreatedAt(t time.Time) *MeshServiceCreate {
	msc.mutation.SetCreatedAt(t)
	return msc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (msc *MeshServiceCreate) SetNillableCreatedAt(t *time.Time) *MeshServiceCreate {
	if t != nil {
		msc.SetCreatedAt(*t)
	}
	return msc
}

// Mutation returns the MeshServiceMutation object of the builder.
func (msc *MeshServiceCreate) Mutation() *MeshServiceMutation {
	return msc.mutation
}

// Save creates the MeshService in the database.
func (msc *MeshServiceCreate) Save(ctx context.Context) (*MeshService, error) {
	msc.defaults()
	return withHooks(ctx, msc.sqlSave, msc.mutation, msc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (msc *MeshServiceCreate) SaveX(ctx context.Context) *MeshService {
	v, err := msc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (msc *MeshServiceCreate) Exec(ctx context.Context) error {
	_, err := msc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (msc *MeshServiceCreate) ExecX(ctx context.Context) {
	if err := msc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (msc *MeshServiceCreate) defaults() {
	if _, ok := msc.mutation.Proto(); !ok {
		v := meshservice.DefaultProto
		msc.mutation.SetProto(v)
	}
	if _, ok := msc.mutation.Target(); !ok {
		v := meshservice.DefaultTarget
		msc.mutation.SetTarget(v)
	}
	if _, ok := msc.mutation.Note(); !ok {
		v := meshservice.DefaultNote
		msc.mutation.SetNote(v)
	}
	if _, ok := msc.mutation.Source(); !ok {
		v := meshservice.DefaultSource
		msc.mutation.SetSource(v)
	}
	if _, ok := msc.mutation.Approved(); !ok {
		v := meshservice.DefaultApproved
		msc.mutation.SetApproved(v)
	}
	if _, ok := msc.mutation.CreatedAt(); !ok {
		v := meshservice.DefaultCreatedAt()
		msc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (msc *MeshServiceCreate) check() error {
	if _, ok := msc.mutation.MeshnetID(); !ok {
		return &ValidationError{Name: "meshnet_id", err: errors.New(`ent: missing required field "MeshService.meshnet_id"`)}
	}
	if _, ok := msc.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "MeshService.node_id"`)}
	}
	if _, ok := msc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MeshService.name"`)}
	}
	if _, ok := msc.mutation.Proto(); !ok {
		return &ValidationError{Name: "proto", err: errors.New(`ent: missing required field "MeshService.proto"`)}
	}
	if _, ok := msc.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "MeshService.port"`)}
	}
	if _, ok := msc.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "MeshService.target"`)}
	}
	if _, ok := msc.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "MeshService.note"`)}
	}
	if _, ok := msc.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "MeshService.source"`)}
	}
	if _, ok := msc.mutation.Approved(); !ok {
		return &ValidationError{Name: "approved", err: errors.New(`ent: missing required field "MeshService.approved"`)}
	}
	if _, ok := msc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MeshService.created_at"`)}
	}
	return nil
}

func (msc *MeshServiceCreate) sqlSave(ctx context.Context) (*MeshService, error) {
	if err := msc.check(); err != nil {
		return nil, err
	}
	_node, _spec := msc.createSpec()
	if err := sqlgraph.CreateNode(ctx, msc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	msc.mutation.id = &_node.ID
	msc.mutation.done = true
	return _node, nil
}

func (msc *MeshServiceCreate) createSpec() (*MeshService, *sqlgraph.CreateSpec) {
	var (
		_node = &MeshService{config: msc.config}
		_spec = sqlgraph.NewCreateSpec(meshservice.Table, sqlgraph.NewFieldSpec(meshservice.FieldID, field.TypeInt))
	)
	if value, ok := msc.mutation.MeshnetID(); ok {
		_spec.SetField(meshservice.FieldMeshnetID, field.TypeInt64, value)
		_node.MeshnetID = value
	}
	if value, ok := msc.mutation.NodeID(); ok {
		_spec.SetField(meshservice.FieldNodeID, field.TypeInt64, value)
		_node.NodeID = value
	}
	if value, ok := msc.mutation.Name(); ok {
		_spec.SetField(meshservice.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := msc.mutation.Proto(); ok {
		_spec.SetField(meshservice.FieldProto, field.TypeString, value)
		_node.Proto = value
	}
	if value, ok := msc.mutation.Port(); ok {
		_spec.SetField(meshservice.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := msc.mutation.Target(); ok {
		_spec.SetField(meshservice.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := msc.mutation.Note(); ok {
		_spec.SetField(meshservice.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := msc.mutation.Source(); ok {
		_spec.SetField(meshservice.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := msc.mutation.Approved(); ok {
		_spec.SetField(meshservice.FieldApproved, field.TypeBool, value)
		_node.Approved = value
	}
	if value, ok := msc.mutation.CreatedAt(); ok {
		_spec.SetField(meshservice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MeshServiceCreateBulk is the builder for creating many MeshService entities in bulk.
type MeshServiceCreateBulk struct {
	config
	err      error
	builders []*MeshServiceCreate
}

// Save creates the MeshService entities in the database.
func (mscb *MeshServiceCreateBulk) Save(ctx context.Context) ([]*MeshService, error) {
	if mscb.err != nil {
		return nil, mscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mscb.builders))
	nodes := make([]*MeshService, len(mscb.builders))
	mutators := make([]Mutator, len(mscb.builders))
	for i := range mscb.builders {
		func(i int, root context.Context) {
			builder := mscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshServiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mscb *MeshServiceCreateBulk) SaveX(ctx context.Context) []*MeshService {
	v, err := mscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mscb *MeshServiceCreateBulk) Exec(ctx context.Context) error {
	_, err := mscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mscb *MeshServiceCreateBulk) ExecX(ctx context.Context) {
	if err := mscb.Exec(ctx); err != nil {
		panic(err)
	}
}
