// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshservice"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshServiceDelete is the builder for deleting a MeshService entity.
type MeshServiceDelete struct {
	config
	hooks    []Hook
	mutation *MeshServiceMutation
}

// Where appends a list predicates to the MeshServiceDelete builder.
func (msd *MeshServiceDelete) Where(ps ...predicate.MeshService) *MeshServiceDelete {
	msd.mutation.Where(ps...)
	return msd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (msd *MeshServiceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, msd.sqlExec, msd.mutation, msd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (msd *MeshServiceDelete) ExecX(ctx context.Context) int {
	n, err := msd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (msd *MeshServiceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(meshservice.Table, sqlgraph.NewFieldSpec(meshservice.FieldID, field.TypeInt))
	if ps := msd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, msd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	msd.mutation.done = true
	return affected, err
}

// MeshServiceDeleteOne is the builder for deleting a single MeshService entity.
type MeshServiceDeleteOne struct {
	msd *MeshServiceDelete
}

// Where appends a list predicates to the MeshServiceDelete builder.
func (msdo *MeshServiceDeleteOne) Where(ps ...predicate.MeshService) *MeshServiceDeleteOne {
	msdo.msd.mutation.Where(ps...)
	return msdo
}

// Exec executes the deletion query.
func (msdo *MeshServiceDeleteOne) Exec(ctx context.Context) error {
	n, err := msdo.msd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{meshservice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (msdo *MeshServiceDeleteOne) ExecX(ctx context.Context) {
	if err := msdo.Exec(ctx); err != nil {
		panic(err)
	}
}
