// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshrelay"
)

// MeshRelayCreate is the builder for creating a MeshRelay entity.
type MeshRelayCreate struct {
	config
	mutation *MeshRelayMutation
	hooks    []Hook
}

// SetMeshnetID sets the "meshnet_id" field.
func (mrc *MeshRelayCreate) SetMeshnetID(i int64) *MeshRelayCreate {
	mrc.mutation.SetMeshnetID(i)
	return mrc
}

// SetLabel sets the "label" field.
func (mrc *MeshRelayCreate) SetLabel(s string) *MeshRelayCreate {
	mrc.mutation.SetLabel(s)
	return mrc
}

// SetHostName sets the "host_name" field.
func (mrc *MeshRelayCreate) SetHostName(s string) *MeshRelayCreate {
	mrc.mutation.SetHostName(s)
	return mrc
}

// SetDerpPort sets the "derp_port" field.
func (mrc *MeshRelayCreate) SetDerpPort(i int) *MeshRelayCreate {
	mrc.mutation.SetDerpPort(i)
	return mrc
}

// SetNillableDerpPort sets the "derp_port" field if the given value is not nil.
func (mrc *MeshRelayCreate) SetNillableDerpPort(i *int) *MeshRelayCreate {
	if i != nil {
		mrc.SetDerpPort(*i)
	}
	return mrc
}

// SetStunPort sets the "stun_port" field.
func (mrc *MeshRelayCreate) SetStunPort(i int) *MeshRelayCreate {
	mrc.mutation.SetStunPort(i)
	return mrc
}

// SetNillableStunPort sets the "stun_port" field if the given value is not nil.
func (mrc *MeshRelayCreate) SetNillableStunPort(i *int) *MeshRelayCreate {
	if i != nil {
		mrc.SetStunPort(*i)
	}
	return mrc
}

// SetEnabled sets the "enabled" field.
func (mrc *MeshRelayCreate) SetEnabled(b bool) *MeshRelayCreate {
	mrc.mutation.SetEnabled(b)
	return mrc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (mrc *MeshRelayCreate) SetNillableEnabled(b *bool) *MeshRelayCreate {
	if b != nil {
		mrc.SetEnabled(*b)
	}
	return mrc
}

// SetCreatedAt sets the "created_at" field.
func (mrc *MeshRelayCreate) SetCreatedAt(t time.Time) *MeshRelayCreate {
	mrc.mutation.SetCreatedAt(t)
	return mrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mrc *MeshRelayCreate) SetNillableCreatedAt(t *time.Time) *MeshRelayCreate {
	if t != nil {
		mrc.SetCreatedAt(*t)
	}
	return mrc
}

// Mutation returns the MeshRelayMutation object of the builder.
func (mrc *MeshRelayCreate) Mutation() *MeshRelayMutation {
	return mrc.mutation
}

// Save creates the MeshRelay in the database.
func (mrc *MeshRelayCreate) Save(ctx context.Context) (*MeshRelay, error) {
	mrc.defaults()
	return withHooks(ctx, mrc.sqlSave, mrc.mutation, mrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mrc *MeshRelayCreate) SaveX(ctx context.Context) *MeshRelay {
	v, err := mrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrc *MeshRelayCreate) Exec(ctx context.Context) error {
	_, err := mrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrc *MeshRelayCreate) ExecX(ctx context.Context) {
	if err := mrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mrc *MeshRelayCreate) defaults() {
	if _, ok := mrc.mutation.DerpPort(); !ok {
		v := meshrelay.DefaultDerpPort
		mrc.mutation.SetDerpPort(v)
	}
	if _, ok := mrc.mutation.StunPort(); !ok {
		v := meshrelay.DefaultStunPort
		mrc.mutation.SetStunPort(v)
	}
	if _, ok := mrc.mutation.Enabled(); !ok {
		v := meshrelay.DefaultEnabled
		mrc.mutation.SetEnabled(v)
	}
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		v := meshrelay.DefaultCreatedAt()
		mrc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mrc *MeshRelayCreate) check() error {
	if _, ok := mrc.mutation.MeshnetID(); !ok {
		return &ValidationError{Name: "meshnet_id", err: errors.New(`ent: missing required field "MeshRelay.meshnet_id"`)}
	}
	if _, ok := mrc.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "MeshRelay.label"`)}
	}
	if _, ok := mrc.mutation.HostName(); !ok {
		return &ValidationError{Name: "host_name", err: errors.New(`ent: missing required field "MeshRelay.host_name"`)}
	}
	if _, ok := mrc.mutation.DerpPort(); !ok {
		return &ValidationError{Name: "derp_port", err: errors.New(`ent: missing required field "MeshRelay.derp_port"`)}
	}
	if _, ok := mrc.mutation.StunPort(); !ok {
		return &ValidationError{Name: "stun_port", err: errors.New(`ent: missing required field "MeshRelay.stun_port"`)}
	}
	if _, ok := mrc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "MeshRelay.enabled"`)}
	}
	if _, ok := mrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MeshRelay.created_at"`)}
	}
	return nil
}

func (mrc *MeshRelayCreate) sqlSave(ctx context.Context) (*MeshRelay, error) {
	if err := mrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mrc.mutation.id = &_node.ID
	mrc.mutation.done = true
	return _node, nil
}

func (mrc *MeshRelayCreate) createSpec() (*MeshRelay, *sqlgraph.CreateSpec) {
	var (
		_node = &MeshRelay{config: mrc.config}
		_spec = sqlgraph.NewCreateSpec(meshrelay.Table, sqlgraph.NewFieldSpec(meshrelay.FieldID, field.TypeInt))
	)
	if value, ok := mrc.mutation.MeshnetID(); ok {
		_spec.SetField(meshrelay.FieldMeshnetID, field.TypeInt64, value)
		_node.MeshnetID = value
	}
	if value, ok := mrc.mutation.Label(); ok {
		_spec.SetField(meshrelay.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := mrc.mutation.HostName(); ok {
		_spec.SetField(meshrelay.FieldHostName, field.TypeString, value)
		_node.HostName = value
	}
	if value, ok := mrc.mutation.DerpPort(); ok {
		_spec.SetField(meshrelay.FieldDerpPort, field.TypeInt, value)
		_node.DerpPort = value
	}
	if value, ok := mrc.mutation.StunPort(); ok {
		_spec.SetField(meshrelay.FieldStunPort, field.TypeInt, value)
		_node.StunPort = value
	}
	if value, ok := mrc.mutation.Enabled(); ok {
		_spec.SetField(meshrelay.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := mrc.mutation.CreatedAt(); ok {
		_spec.SetField(meshrelay.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MeshRelayCreateBulk is the builder for creating many MeshRelay entities in bulk.
type MeshRelayCreateBulk struct {
	config
	err      error
	builders []*MeshRelayCreate
}

// Save creates the MeshRelay entities in the database.
func (mrcb *MeshRelayCreateBulk) Save(ctx context.Context) ([]*MeshRelay, error) {
	if mrcb.err != nil {
		return nil, mrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mrcb.builders))
	nodes := make([]*MeshRelay, len(mrcb.builders))
	mutators := make([]Mutator, len(mrcb.builders))
	for i := range mrcb.builders {
		func(i int, root context.Context) {
			builder := mrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshRelayMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mrcb *MeshRelayCreateBulk) SaveX(ctx context.Context) []*MeshRelay {
	v, err := mrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mrcb *MeshRelayCreateBulk) Exec(ctx context.Context) error {
	_, err := mrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mrcb *MeshRelayCreateBulk) ExecX(ctx context.Context) {
	if err := mrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
