// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshrelay"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshRelayQuery is the builder for querying MeshRelay entities.
type MeshRelayQuery struct {
	config
	ctx        *QueryContext
	order      []meshrelay.OrderOption
	inters     []Interceptor
	predicates []predicate.MeshRelay
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeshRelayQuery builder.
func (mrq *MeshRelayQuery) Where(ps ...predicate.MeshRelay) *MeshRelayQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *MeshRelayQuery) Limit(limit int) *MeshRelayQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *MeshRelayQuery) Offset(offset int) *MeshRelayQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *MeshRelayQuery) Unique(unique bool) *MeshRelayQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *MeshRelayQuery) Order(o ...meshrelay.OrderOption) *MeshRelayQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// First returns the first MeshRelay entity from the query.
// Returns a *NotFoundError when no MeshRelay was found.
func (mrq *MeshRelayQuery) First(ctx context.Context) (*MeshRelay, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meshrelay.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *MeshRelayQuery) FirstX(ctx context.Context) *MeshRelay {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MeshRelay ID from the query.
// Returns a *NotFoundError when no MeshRelay ID was found.
func (mrq *MeshRelayQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meshrelay.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *MeshRelayQuery) FirstIDX(ctx context.Context) int {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MeshRelay entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MeshRelay entity is found.
// Returns a *NotFoundError when no MeshRelay entities are found.
func (mrq *MeshRelayQuery) Only(ctx context.Context) (*MeshRelay, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meshrelay.Label}
	default:
		return nil, &NotSingularError{meshrelay.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *MeshRelayQuery) OnlyX(ctx context.Context) *MeshRelay {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MeshRelay ID in the query.
// Returns a *NotSingularError when more than one MeshRelay ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *MeshRelayQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meshrelay.Label}
	default:
		err = &NotSingularError{meshrelay.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *MeshRelayQuery) OnlyIDX(ctx context.Context) int {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MeshRelays.
func (mrq *MeshRelayQuery) All(ctx context.Context) ([]*MeshRelay, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryAll)
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MeshRelay, *MeshRelayQuery]()
	return withInterceptors[[]*MeshRelay](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *MeshRelayQuery) AllX(ctx context.Context) []*MeshRelay {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MeshRelay IDs.
func (mrq *MeshRelayQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryIDs)
	if err = mrq.Select(meshrelay.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *MeshRelayQuery) IDsX(ctx context.Context) []int {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *MeshRelayQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryCount)
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*MeshRelayQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *MeshRelayQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *MeshRelayQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, ent.OpQueryExist)
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *MeshRelayQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeshRelayQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *MeshRelayQuery) Clone() *MeshRelayQuery {
	if mrq == nil {
		return nil
	}
	return &MeshRelayQuery{
		config:     mrq.config,
		ctx:        mrq.ctx.Clone(),
		order:      append([]meshrelay.OrderOption{}, mrq.order...),
		inters:     append([]Interceptor{}, mrq.inters...),
		predicates: append([]predicate.MeshRelay{}, mrq.predicates...),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MeshRelay.Query().
//		GroupBy(meshrelay.FieldMeshnetID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *MeshRelayQuery) GroupBy(field string, fields ...string) *MeshRelayGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeshRelayGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = meshrelay.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//	}
//
//	client.MeshRelay.Query().
//		Select(meshrelay.FieldMeshnetID).
//		Scan(ctx, &v)
func (mrq *MeshRelayQuery) Select(fields ...string) *MeshRelaySelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &MeshRelaySelect{MeshRelayQuery: mrq}
	sbuild.label = meshrelay.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeshRelaySelect configured with the given aggregations.
func (mrq *MeshRelayQuery) Aggregate(fns ...AggregateFunc) *MeshRelaySelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *MeshRelayQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !meshrelay.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *MeshRelayQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MeshRelay, error) {
	var (
		nodes = []*MeshRelay{}
		_spec = mrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MeshRelay).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MeshRelay{config: mrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mrq *MeshRelayQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *MeshRelayQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meshrelay.Table, meshrelay.Columns, sqlgraph.NewFieldSpec(meshrelay.FieldID, field.TypeInt))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshrelay.FieldID)
		for i := range fields {
			if fields[i] != meshrelay.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *MeshRelayQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(meshrelay.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = meshrelay.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeshRelayGroupBy is the group-by builder for MeshRelay entities.
type MeshRelayGroupBy struct {
	selector
	build *MeshRelayQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *MeshRelayGroupBy) Aggregate(fns ...AggregateFunc) *MeshRelayGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *MeshRelayGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, ent.OpQueryGroupBy)
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshRelayQuery, *MeshRelayGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *MeshRelayGroupBy) sqlScan(ctx context.Context, root *MeshRelayQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeshRelaySelect is the builder for selecting fields of MeshRelay entities.
type MeshRelaySelect struct {
	*MeshRelayQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *MeshRelaySelect) Aggregate(fns ...AggregateFunc) *MeshRelaySelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *MeshRelaySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, ent.OpQuerySelect)
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshRelayQuery, *MeshRelaySelect](ctx, mrs.MeshRelayQuery, mrs, mrs.inters, v)
}

func (mrs *MeshRelaySelect) sqlScan(ctx context.Context, root *MeshRelayQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
