// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshaclrevision"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshACLRevisionDelete is the builder for deleting a MeshACLRevision entity.
type MeshACLRevisionDelete struct {
	config
	hooks    []Hook
	mutation *MeshACLRevisionMutation
}

// Where appends a list predicates to the MeshACLRevisionDelete builder.
func (_d *MeshACLRevisionDelete) Where(ps ...predicate.MeshACLRevision) *MeshACLRevisionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MeshACLRevisionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MeshACLRevisionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MeshACLRevisionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(meshaclrevision.Table, sqlgraph.NewFieldSpec(meshaclrevision.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MeshACLRevisionDeleteOne is the builder for deleting a single MeshACLRevision entity.
type MeshACLRevisionDeleteOne struct {
	_d *MeshACLRevisionDelete
}

// Where appends a list predicates to the MeshACLRevisionDelete builder.
func (_d *MeshACLRevisionDeleteOne) Where(ps ...predicate.MeshACLRevision) *MeshACLRevisionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MeshACLRevisionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{meshaclrevision.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MeshACLRevisionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
