// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabi/calabi/apps/calabi-coord/internal/platform/store/ent/meshservice"
)

// MeshServiceCreate is the builder for creating a MeshService entity.
type MeshServiceCreate struct {
	config
	mutation *MeshServiceMutation
	hooks    []Hook
}

// SetMeshnetID sets the "meshnet_id" field.
func (_c *MeshServiceCreate) SetMeshnetID(v int64) *MeshServiceCreate {
	_c.mutation.SetMeshnetID(v)
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *MeshServiceCreate) SetNodeID(v int64) *MeshServiceCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MeshServiceCreate) SetName(v string) *MeshServiceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProto sets the "proto" field.
func (_c *MeshServiceCreate) SetProto(v string) *MeshServiceCreate {
	_c.mutation.SetProto(v)
	return _c
}

// SetNillableProto sets the "proto" field if the given value is not nil.
func (_c *MeshServiceCreate) SetNillableProto(v *string) *MeshServiceCreate {
	if v != nil {
		_c.SetProto(*v)
	}
	return _c
}

// SetPort sets the "port" field.
func (_c *MeshServiceCreate) SetPort(v int) *MeshServiceCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *MeshServiceCreate) SetTarget(v string) *MeshServiceCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *MeshServiceCreate) SetNillableTarget(v *string) *MeshServiceCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *MeshServiceCreate) SetNote(v string) *MeshServiceCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *MeshServiceCreate) SetNillableNote(v *string) *MeshServiceCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *MeshServiceCreate) SetSource(v string) *MeshServiceCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *MeshServiceCreate) SetNillableSource(v *string) *MeshServiceCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetApproved sets the "approved" field.
func (_c *MeshServiceCreate) SetApproved(v bool) *MeshServiceCreate {
	_c.mutation.SetApproved(v)
	return _c
}

// SetNillableApproved sets the "approved" field if the given value is not nil.
func (_c *MeshServiceCreate) SetNillableApproved(v *bool) *MeshServiceCreate {
	if v != nil {
		_c.SetApproved(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MeshServiceCreate) SetCreatedAt(v time.Time) *MeshServiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MeshServiceCreate) SetNillableCreatedAt(v *time.Time) *MeshServiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the MeshServiceMutation object of the builder.
func (_c *MeshServiceCreate) Mutation() *MeshServiceMutation {
	return _c.mutation
}

// Save creates the MeshService in the database.
func (_c *MeshServiceCreate) Save(ctx context.Context) (*MeshService, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MeshServiceCreate) SaveX(ctx context.Context) *MeshService {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MeshServiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MeshServiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MeshServiceCreate) defaults() {
	if _, ok := _c.mutation.Proto(); !ok {
		v := meshservice.DefaultProto
		_c.mutation.SetProto(v)
	}
	if _, ok := _c.mutation.Target(); !ok {
		v := meshservice.DefaultTarget
		_c.mutation.SetTarget(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := meshservice.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := meshservice.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Approved(); !ok {
		v := meshservice.DefaultApproved
		_c.mutation.SetApproved(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := meshservice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MeshServiceCreate) check() error {
	if _, ok := _c.mutation.MeshnetID(); !ok {
		return &ValidationError{Name: "meshnet_id", err: errors.New(`ent: missing required field "MeshService.meshnet_id"`)}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "MeshService.node_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MeshService.name"`)}
	}
	if _, ok := _c.mutation.Proto(); !ok {
		return &ValidationError{Name: "proto", err: errors.New(`ent: missing required field "MeshService.proto"`)}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "MeshService.port"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "MeshService.target"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "MeshService.note"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "MeshService.source"`)}
	}
	if _, ok := _c.mutation.Approved(); !ok {
		return &ValidationError{Name: "approved", err: errors.New(`ent: missing required field "MeshService.approved"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MeshService.created_at"`)}
	}
	return nil
}

func (_c *MeshServiceCreate) sqlSave(ctx context.Context) (*MeshService, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MeshServiceCreate) createSpec() (*MeshService, *sqlgraph.CreateSpec) {
	var (
		_node = &MeshService{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(meshservice.Table, sqlgraph.NewFieldSpec(meshservice.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MeshnetID(); ok {
		_spec.SetField(meshservice.FieldMeshnetID, field.TypeInt64, value)
		_node.MeshnetID = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(meshservice.FieldNodeID, field.TypeInt64, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(meshservice.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Proto(); ok {
		_spec.SetField(meshservice.FieldProto, field.TypeString, value)
		_node.Proto = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(meshservice.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(meshservice.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(meshservice.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(meshservice.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Approved(); ok {
		_spec.SetField(meshservice.FieldApproved, field.TypeBool, value)
		_node.Approved = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(meshservice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// MeshServiceCreateBulk is the builder for creating many MeshService entities in bulk.
type MeshServiceCreateBulk struct {
	config
	err      error
	builders []*MeshServiceCreate
}

// Save creates the MeshService entities in the database.
func (_c *MeshServiceCreateBulk) Save(ctx context.Context) ([]*MeshService, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MeshService, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshServiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MeshServiceCreateBulk) SaveX(ctx context.Context) []*MeshService {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MeshServiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MeshServiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
