// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshauthkey"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshAuthKeyDelete is the builder for deleting a MeshAuthKey entity.
type MeshAuthKeyDelete struct {
	config
	hooks    []Hook
	mutation *MeshAuthKeyMutation
}

// Where appends a list predicates to the MeshAuthKeyDelete builder.
func (makd *MeshAuthKeyDelete) Where(ps ...predicate.MeshAuthKey) *MeshAuthKeyDelete {
	makd.mutation.Where(ps...)
	return makd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (makd *MeshAuthKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, makd.sqlExec, makd.mutation, makd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (makd *MeshAuthKeyDelete) ExecX(ctx context.Context) int {
	n, err := makd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (makd *MeshAuthKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(meshauthkey.Table, sqlgraph.NewFieldSpec(meshauthkey.FieldID, field.TypeInt))
	if ps := makd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, makd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	makd.mutation.done = true
	return affected, err
}

// MeshAuthKeyDeleteOne is the builder for deleting a single MeshAuthKey entity.
type MeshAuthKeyDeleteOne struct {
	makd *MeshAuthKeyDelete
}

// Where appends a list predicates to the MeshAuthKeyDelete builder.
func (makdo *MeshAuthKeyDeleteOne) Where(ps ...predicate.MeshAuthKey) *MeshAuthKeyDeleteOne {
	makdo.makd.mutation.Where(ps...)
	return makdo
}

// Exec executes the deletion query.
func (makdo *MeshAuthKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := makdo.makd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{meshauthkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (makdo *MeshAuthKeyDeleteOne) ExecX(ctx context.Context) {
	if err := makdo.Exec(ctx); err != nil {
		panic(err)
	}
}
