// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshnode"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshNodeQuery is the builder for querying MeshNode entities.
type MeshNodeQuery struct {
	config
	ctx        *QueryContext
	order      []meshnode.OrderOption
	inters     []Interceptor
	predicates []predicate.MeshNode
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeshNodeQuery builder.
func (mnq *MeshNodeQuery) Where(ps ...predicate.MeshNode) *MeshNodeQuery {
	mnq.predicates = append(mnq.predicates, ps...)
	return mnq
}

// Limit the number of records to be returned by this query.
func (mnq *MeshNodeQuery) Limit(limit int) *MeshNodeQuery {
	mnq.ctx.Limit = &limit
	return mnq
}

// Offset to start from.
func (mnq *MeshNodeQuery) Offset(offset int) *MeshNodeQuery {
	mnq.ctx.Offset = &offset
	return mnq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mnq *MeshNodeQuery) Unique(unique bool) *MeshNodeQuery {
	mnq.ctx.Unique = &unique
	return mnq
}

// Order specifies how the records should be ordered.
func (mnq *MeshNodeQuery) Order(o ...meshnode.OrderOption) *MeshNodeQuery {
	mnq.order = append(mnq.order, o...)
	return mnq
}

// First returns the first MeshNode entity from the query.
// Returns a *NotFoundError when no MeshNode was found.
func (mnq *MeshNodeQuery) First(ctx context.Context) (*MeshNode, error) {
	nodes, err := mnq.Limit(1).All(setContextOp(ctx, mnq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meshnode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mnq *MeshNodeQuery) FirstX(ctx context.Context) *MeshNode {
	node, err := mnq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MeshNode ID from the query.
// Returns a *NotFoundError when no MeshNode ID was found.
func (mnq *MeshNodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mnq.Limit(1).IDs(setContextOp(ctx, mnq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meshnode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mnq *MeshNodeQuery) FirstIDX(ctx context.Context) int {
	id, err := mnq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MeshNode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MeshNode entity is found.
// Returns a *NotFoundError when no MeshNode entities are found.
func (mnq *MeshNodeQuery) Only(ctx context.Context) (*MeshNode, error) {
	nodes, err := mnq.Limit(2).All(setContextOp(ctx, mnq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meshnode.Label}
	default:
		return nil, &NotSingularError{meshnode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mnq *MeshNodeQuery) OnlyX(ctx context.Context) *MeshNode {
	node, err := mnq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MeshNode ID in the query.
// Returns a *NotSingularError when more than one MeshNode ID is found.
// Returns a *NotFoundError when no entities are found.
func (mnq *MeshNodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mnq.Limit(2).IDs(setContextOp(ctx, mnq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meshnode.Label}
	default:
		err = &NotSingularError{meshnode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mnq *MeshNodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := mnq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MeshNodes.
func (mnq *MeshNodeQuery) All(ctx context.Context) ([]*MeshNode, error) {
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryAll)
	if err := mnq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MeshNode, *MeshNodeQuery]()
	return withInterceptors[[]*MeshNode](ctx, mnq, qr, mnq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mnq *MeshNodeQuery) AllX(ctx context.Context) []*MeshNode {
	nodes, err := mnq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MeshNode IDs.
func (mnq *MeshNodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mnq.ctx.Unique == nil && mnq.path != nil {
		mnq.Unique(true)
	}
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryIDs)
	if err = mnq.Select(meshnode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mnq *MeshNodeQuery) IDsX(ctx context.Context) []int {
	ids, err := mnq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mnq *MeshNodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryCount)
	if err := mnq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mnq, querierCount[*MeshNodeQuery](), mnq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mnq *MeshNodeQuery) CountX(ctx context.Context) int {
	count, err := mnq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mnq *MeshNodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mnq.ctx, ent.OpQueryExist)
	switch _, err := mnq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mnq *MeshNodeQuery) ExistX(ctx context.Context) bool {
	exist, err := mnq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeshNodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mnq *MeshNodeQuery) Clone() *MeshNodeQuery {
	if mnq == nil {
		return nil
	}
	return &MeshNodeQuery{
		config:     mnq.config,
		ctx:        mnq.ctx.Clone(),
		order:      append([]meshnode.OrderOption{}, mnq.order...),
		inters:     append([]Interceptor{}, mnq.inters...),
		predicates: append([]predicate.MeshNode{}, mnq.predicates...),
		// clone intermediate query.
		sql:  mnq.sql.Clone(),
		path: mnq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MeshNode.Query().
//		GroupBy(meshnode.FieldMeshnetID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mnq *MeshNodeQuery) GroupBy(field string, fields ...string) *MeshNodeGroupBy {
	mnq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeshNodeGroupBy{build: mnq}
	grbuild.flds = &mnq.ctx.Fields
	grbuild.label = meshnode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//	}
//
//	client.MeshNode.Query().
//		Select(meshnode.FieldMeshnetID).
//		Scan(ctx, &v)
func (mnq *MeshNodeQuery) Select(fields ...string) *MeshNodeSelect {
	mnq.ctx.Fields = append(mnq.ctx.Fields, fields...)
	sbuild := &MeshNodeSelect{MeshNodeQuery: mnq}
	sbuild.label = meshnode.Label
	sbuild.flds, sbuild.scan = &mnq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeshNodeSelect configured with the given aggregations.
func (mnq *MeshNodeQuery) Aggregate(fns ...AggregateFunc) *MeshNodeSelect {
	return mnq.Select().Aggregate(fns...)
}

func (mnq *MeshNodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mnq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mnq); err != nil {
				return err
			}
		}
	}
	for _, f := range mnq.ctx.Fields {
		if !meshnode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mnq.path != nil {
		prev, err := mnq.path(ctx)
		if err != nil {
			return err
		}
		mnq.sql = prev
	}
	return nil
}

func (mnq *MeshNodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MeshNode, error) {
	var (
		nodes = []*MeshNode{}
		_spec = mnq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MeshNode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MeshNode{config: mnq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mnq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mnq *MeshNodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mnq.querySpec()
	_spec.Node.Columns = mnq.ctx.Fields
	if len(mnq.ctx.Fields) > 0 {
		_spec.Unique = mnq.ctx.Unique != nil && *mnq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mnq.driver, _spec)
}

func (mnq *MeshNodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meshnode.Table, meshnode.Columns, sqlgraph.NewFieldSpec(meshnode.FieldID, field.TypeInt))
	_spec.From = mnq.sql
	if unique := mnq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mnq.path != nil {
		_spec.Unique = true
	}
	if fields := mnq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshnode.FieldID)
		for i := range fields {
			if fields[i] != meshnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mnq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mnq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mnq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mnq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mnq *MeshNodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mnq.driver.Dialect())
	t1 := builder.Table(meshnode.Table)
	columns := mnq.ctx.Fields
	if len(columns) == 0 {
		columns = meshnode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mnq.sql != nil {
		selector = mnq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mnq.ctx.Unique != nil && *mnq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mnq.predicates {
		p(selector)
	}
	for _, p := range mnq.order {
		p(selector)
	}
	if offset := mnq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mnq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeshNodeGroupBy is the group-by builder for MeshNode entities.
type MeshNodeGroupBy struct {
	selector
	build *MeshNodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mngb *MeshNodeGroupBy) Aggregate(fns ...AggregateFunc) *MeshNodeGroupBy {
	mngb.fns = append(mngb.fns, fns...)
	return mngb
}

// Scan applies the selector query and scans the result into the given value.
func (mngb *MeshNodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mngb.build.ctx, ent.OpQueryGroupBy)
	if err := mngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshNodeQuery, *MeshNodeGroupBy](ctx, mngb.build, mngb, mngb.build.inters, v)
}

func (mngb *MeshNodeGroupBy) sqlScan(ctx context.Context, root *MeshNodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mngb.fns))
	for _, fn := range mngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mngb.flds)+len(mngb.fns))
		for _, f := range *mngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeshNodeSelect is the builder for selecting fields of MeshNode entities.
type MeshNodeSelect struct {
	*MeshNodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mns *MeshNodeSelect) Aggregate(fns ...AggregateFunc) *MeshNodeSelect {
	mns.fns = append(mns.fns, fns...)
	return mns
}

// Scan applies the selector query and scans the result into the given value.
func (mns *MeshNodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mns.ctx, ent.OpQuerySelect)
	if err := mns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshNodeQuery, *MeshNodeSelect](ctx, mns.MeshNodeQuery, mns, mns.inters, v)
}

func (mns *MeshNodeSelect) sqlScan(ctx context.Context, root *MeshNodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mns.fns))
	for _, fn := range mns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
