// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshtunnelusage"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshTunnelUsageDelete is the builder for deleting a MeshTunnelUsage entity.
type MeshTunnelUsageDelete struct {
	config
	hooks    []Hook
	mutation *MeshTunnelUsageMutation
}

// Where appends a list predicates to the MeshTunnelUsageDelete builder.
func (mtud *MeshTunnelUsageDelete) Where(ps ...predicate.MeshTunnelUsage) *MeshTunnelUsageDelete {
	mtud.mutation.Where(ps...)
	return mtud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mtud *MeshTunnelUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mtud.sqlExec, mtud.mutation, mtud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mtud *MeshTunnelUsageDelete) ExecX(ctx context.Context) int {
	n, err := mtud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mtud *MeshTunnelUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(meshtunnelusage.Table, sqlgraph.NewFieldSpec(meshtunnelusage.FieldID, field.TypeInt))
	if ps := mtud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mtud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mtud.mutation.done = true
	return affected, err
}

// MeshTunnelUsageDeleteOne is the builder for deleting a single MeshTunnelUsage entity.
type MeshTunnelUsageDeleteOne struct {
	mtud *MeshTunnelUsageDelete
}

// Where appends a list predicates to the MeshTunnelUsageDelete builder.
func (mtudo *MeshTunnelUsageDeleteOne) Where(ps ...predicate.MeshTunnelUsage) *MeshTunnelUsageDeleteOne {
	mtudo.mtud.mutation.Where(ps...)
	return mtudo
}

// Exec executes the deletion query.
func (mtudo *MeshTunnelUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := mtudo.mtud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{meshtunnelusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mtudo *MeshTunnelUsageDeleteOne) ExecX(ctx context.Context) {
	if err := mtudo.Exec(ctx); err != nil {
		panic(err)
	}
}
