// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshaclrevision"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/predicate"
)

// MeshACLRevisionQuery is the builder for querying MeshACLRevision entities.
type MeshACLRevisionQuery struct {
	config
	ctx        *QueryContext
	order      []meshaclrevision.OrderOption
	inters     []Interceptor
	predicates []predicate.MeshACLRevision
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeshACLRevisionQuery builder.
func (marq *MeshACLRevisionQuery) Where(ps ...predicate.MeshACLRevision) *MeshACLRevisionQuery {
	marq.predicates = append(marq.predicates, ps...)
	return marq
}

// Limit the number of records to be returned by this query.
func (marq *MeshACLRevisionQuery) Limit(limit int) *MeshACLRevisionQuery {
	marq.ctx.Limit = &limit
	return marq
}

// Offset to start from.
func (marq *MeshACLRevisionQuery) Offset(offset int) *MeshACLRevisionQuery {
	marq.ctx.Offset = &offset
	return marq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (marq *MeshACLRevisionQuery) Unique(unique bool) *MeshACLRevisionQuery {
	marq.ctx.Unique = &unique
	return marq
}

// Order specifies how the records should be ordered.
func (marq *MeshACLRevisionQuery) Order(o ...meshaclrevision.OrderOption) *MeshACLRevisionQuery {
	marq.order = append(marq.order, o...)
	return marq
}

// First returns the first MeshACLRevision entity from the query.
// Returns a *NotFoundError when no MeshACLRevision was found.
func (marq *MeshACLRevisionQuery) First(ctx context.Context) (*MeshACLRevision, error) {
	nodes, err := marq.Limit(1).All(setContextOp(ctx, marq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meshaclrevision.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) FirstX(ctx context.Context) *MeshACLRevision {
	node, err := marq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MeshACLRevision ID from the query.
// Returns a *NotFoundError when no MeshACLRevision ID was found.
func (marq *MeshACLRevisionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = marq.Limit(1).IDs(setContextOp(ctx, marq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meshaclrevision.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) FirstIDX(ctx context.Context) int {
	id, err := marq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MeshACLRevision entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MeshACLRevision entity is found.
// Returns a *NotFoundError when no MeshACLRevision entities are found.
func (marq *MeshACLRevisionQuery) Only(ctx context.Context) (*MeshACLRevision, error) {
	nodes, err := marq.Limit(2).All(setContextOp(ctx, marq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meshaclrevision.Label}
	default:
		return nil, &NotSingularError{meshaclrevision.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) OnlyX(ctx context.Context) *MeshACLRevision {
	node, err := marq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MeshACLRevision ID in the query.
// Returns a *NotSingularError when more than one MeshACLRevision ID is found.
// Returns a *NotFoundError when no entities are found.
func (marq *MeshACLRevisionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = marq.Limit(2).IDs(setContextOp(ctx, marq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meshaclrevision.Label}
	default:
		err = &NotSingularError{meshaclrevision.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) OnlyIDX(ctx context.Context) int {
	id, err := marq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MeshACLRevisions.
func (marq *MeshACLRevisionQuery) All(ctx context.Context) ([]*MeshACLRevision, error) {
	ctx = setContextOp(ctx, marq.ctx, ent.OpQueryAll)
	if err := marq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MeshACLRevision, *MeshACLRevisionQuery]()
	return withInterceptors[[]*MeshACLRevision](ctx, marq, qr, marq.inters)
}

// AllX is like All, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) AllX(ctx context.Context) []*MeshACLRevision {
	nodes, err := marq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MeshACLRevision IDs.
func (marq *MeshACLRevisionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if marq.ctx.Unique == nil && marq.path != nil {
		marq.Unique(true)
	}
	ctx = setContextOp(ctx, marq.ctx, ent.OpQueryIDs)
	if err = marq.Select(meshaclrevision.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) IDsX(ctx context.Context) []int {
	ids, err := marq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (marq *MeshACLRevisionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, marq.ctx, ent.OpQueryCount)
	if err := marq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, marq, querierCount[*MeshACLRevisionQuery](), marq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) CountX(ctx context.Context) int {
	count, err := marq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (marq *MeshACLRevisionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, marq.ctx, ent.OpQueryExist)
	switch _, err := marq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (marq *MeshACLRevisionQuery) ExistX(ctx context.Context) bool {
	exist, err := marq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeshACLRevisionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (marq *MeshACLRevisionQuery) Clone() *MeshACLRevisionQuery {
	if marq == nil {
		return nil
	}
	return &MeshACLRevisionQuery{
		config:     marq.config,
		ctx:        marq.ctx.Clone(),
		order:      append([]meshaclrevision.OrderOption{}, marq.order...),
		inters:     append([]Interceptor{}, marq.inters...),
		predicates: append([]predicate.MeshACLRevision{}, marq.predicates...),
		// clone intermediate query.
		sql:  marq.sql.Clone(),
		path: marq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MeshACLRevision.Query().
//		GroupBy(meshaclrevision.FieldMeshnetID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (marq *MeshACLRevisionQuery) GroupBy(field string, fields ...string) *MeshACLRevisionGroupBy {
	marq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeshACLRevisionGroupBy{build: marq}
	grbuild.flds = &marq.ctx.Fields
	grbuild.label = meshaclrevision.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MeshnetID int64 `json:"meshnet_id,omitempty"`
//	}
//
//	client.MeshACLRevision.Query().
//		Select(meshaclrevision.FieldMeshnetID).
//		Scan(ctx, &v)
func (marq *MeshACLRevisionQuery) Select(fields ...string) *MeshACLRevisionSelect {
	marq.ctx.Fields = append(marq.ctx.Fields, fields...)
	sbuild := &MeshACLRevisionSelect{MeshACLRevisionQuery: marq}
	sbuild.label = meshaclrevision.Label
	sbuild.flds, sbuild.scan = &marq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeshACLRevisionSelect configured with the given aggregations.
func (marq *MeshACLRevisionQuery) Aggregate(fns ...AggregateFunc) *MeshACLRevisionSelect {
	return marq.Select().Aggregate(fns...)
}

func (marq *MeshACLRevisionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range marq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, marq); err != nil {
				return err
			}
		}
	}
	for _, f := range marq.ctx.Fields {
		if !meshaclrevision.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if marq.path != nil {
		prev, err := marq.path(ctx)
		if err != nil {
			return err
		}
		marq.sql = prev
	}
	return nil
}

func (marq *MeshACLRevisionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MeshACLRevision, error) {
	var (
		nodes = []*MeshACLRevision{}
		_spec = marq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MeshACLRevision).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MeshACLRevision{config: marq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, marq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (marq *MeshACLRevisionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := marq.querySpec()
	_spec.Node.Columns = marq.ctx.Fields
	if len(marq.ctx.Fields) > 0 {
		_spec.Unique = marq.ctx.Unique != nil && *marq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, marq.driver, _spec)
}

func (marq *MeshACLRevisionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meshaclrevision.Table, meshaclrevision.Columns, sqlgraph.NewFieldSpec(meshaclrevision.FieldID, field.TypeInt))
	_spec.From = marq.sql
	if unique := marq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if marq.path != nil {
		_spec.Unique = true
	}
	if fields := marq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshaclrevision.FieldID)
		for i := range fields {
			if fields[i] != meshaclrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := marq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := marq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := marq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := marq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (marq *MeshACLRevisionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(marq.driver.Dialect())
	t1 := builder.Table(meshaclrevision.Table)
	columns := marq.ctx.Fields
	if len(columns) == 0 {
		columns = meshaclrevision.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if marq.sql != nil {
		selector = marq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if marq.ctx.Unique != nil && *marq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range marq.predicates {
		p(selector)
	}
	for _, p := range marq.order {
		p(selector)
	}
	if offset := marq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := marq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeshACLRevisionGroupBy is the group-by builder for MeshACLRevision entities.
type MeshACLRevisionGroupBy struct {
	selector
	build *MeshACLRevisionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (margb *MeshACLRevisionGroupBy) Aggregate(fns ...AggregateFunc) *MeshACLRevisionGroupBy {
	margb.fns = append(margb.fns, fns...)
	return margb
}

// Scan applies the selector query and scans the result into the given value.
func (margb *MeshACLRevisionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, margb.build.ctx, ent.OpQueryGroupBy)
	if err := margb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshACLRevisionQuery, *MeshACLRevisionGroupBy](ctx, margb.build, margb, margb.build.inters, v)
}

func (margb *MeshACLRevisionGroupBy) sqlScan(ctx context.Context, root *MeshACLRevisionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(margb.fns))
	for _, fn := range margb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*margb.flds)+len(margb.fns))
		for _, f := range *margb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*margb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := margb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeshACLRevisionSelect is the builder for selecting fields of MeshACLRevision entities.
type MeshACLRevisionSelect struct {
	*MeshACLRevisionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mars *MeshACLRevisionSelect) Aggregate(fns ...AggregateFunc) *MeshACLRevisionSelect {
	mars.fns = append(mars.fns, fns...)
	return mars
}

// Scan applies the selector query and scans the result into the given value.
func (mars *MeshACLRevisionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mars.ctx, ent.OpQuerySelect)
	if err := mars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshACLRevisionQuery, *MeshACLRevisionSelect](ctx, mars.MeshACLRevisionQuery, mars, mars.inters, v)
}

func (mars *MeshACLRevisionSelect) sqlScan(ctx context.Context, root *MeshACLRevisionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mars.fns))
	for _, fn := range mars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
