// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/coordsetting"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshacl"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshaclrevision"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshauthkey"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshconnrecord"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshnode"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshrelay"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshservice"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshsetting"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshtunnel"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/meshtunnelusage"
	"github.com/calabinet/calabi/apps/calabi-coord/internal/platform/store/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	coordsettingFields := schema.CoordSetting{}.Fields()
	_ = coordsettingFields
	// coordsettingDescKey is the schema descriptor for key field.
	coordsettingDescKey := coordsettingFields[0].Descriptor()
	// coordsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	coordsetting.KeyValidator = coordsettingDescKey.Validators[0].(func(string) error)
	// coordsettingDescValue is the schema descriptor for value field.
	coordsettingDescValue := coordsettingFields[1].Descriptor()
	// coordsetting.DefaultValue holds the default value on creation for the value field.
	coordsetting.DefaultValue = coordsettingDescValue.Default.(string)
	// coordsettingDescUpdatedAt is the schema descriptor for updated_at field.
	coordsettingDescUpdatedAt := coordsettingFields[2].Descriptor()
	// coordsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	coordsetting.DefaultUpdatedAt = coordsettingDescUpdatedAt.Default.(func() time.Time)
	// coordsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	coordsetting.UpdateDefaultUpdatedAt = coordsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	meshaclFields := schema.MeshACL{}.Fields()
	_ = meshaclFields
	// meshaclDescPolicyJSON is the schema descriptor for policy_json field.
	meshaclDescPolicyJSON := meshaclFields[1].Descriptor()
	// meshacl.DefaultPolicyJSON holds the default value on creation for the policy_json field.
	meshacl.DefaultPolicyJSON = meshaclDescPolicyJSON.Default.(string)
	// meshaclDescUpdatedAt is the schema descriptor for updated_at field.
	meshaclDescUpdatedAt := meshaclFields[2].Descriptor()
	// meshacl.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	meshacl.DefaultUpdatedAt = meshaclDescUpdatedAt.Default.(func() time.Time)
	// meshacl.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	meshacl.UpdateDefaultUpdatedAt = meshaclDescUpdatedAt.UpdateDefault.(func() time.Time)
	meshaclrevisionFields := schema.MeshACLRevision{}.Fields()
	_ = meshaclrevisionFields
	// meshaclrevisionDescPolicyJSON is the schema descriptor for policy_json field.
	meshaclrevisionDescPolicyJSON := meshaclrevisionFields[1].Descriptor()
	// meshaclrevision.DefaultPolicyJSON holds the default value on creation for the policy_json field.
	meshaclrevision.DefaultPolicyJSON = meshaclrevisionDescPolicyJSON.Default.(string)
	// meshaclrevisionDescActor is the schema descriptor for actor field.
	meshaclrevisionDescActor := meshaclrevisionFields[2].Descriptor()
	// meshaclrevision.DefaultActor holds the default value on creation for the actor field.
	meshaclrevision.DefaultActor = meshaclrevisionDescActor.Default.(string)
	// meshaclrevisionDescCreatedAt is the schema descriptor for created_at field.
	meshaclrevisionDescCreatedAt := meshaclrevisionFields[3].Descriptor()
	// meshaclrevision.DefaultCreatedAt holds the default value on creation for the created_at field.
	meshaclrevision.DefaultCreatedAt = meshaclrevisionDescCreatedAt.Default.(func() time.Time)
	meshauthkeyFields := schema.MeshAuthKey{}.Fields()
	_ = meshauthkeyFields
	// meshauthkeyDescHash is the schema descriptor for hash field.
	meshauthkeyDescHash := meshauthkeyFields[1].Descriptor()
	// meshauthkey.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	meshauthkey.HashValidator = meshauthkeyDescHash.Validators[0].(func(string) error)
	// meshauthkeyDescPrefix is the schema descriptor for prefix field.
	meshauthkeyDescPrefix := meshauthkeyFields[2].Descriptor()
	// meshauthkey.DefaultPrefix holds the default value on creation for the prefix field.
	meshauthkey.DefaultPrefix = meshauthkeyDescPrefix.Default.(string)
	// meshauthkeyDescTagsJSON is the schema descriptor for tags_json field.
	meshauthkeyDescTagsJSON := meshauthkeyFields[3].Descriptor()
	// meshauthkey.DefaultTagsJSON holds the default value on creation for the tags_json field.
	meshauthkey.DefaultTagsJSON = meshauthkeyDescTagsJSON.Default.(string)
	// meshauthkeyDescMaxUses is the schema descriptor for max_uses field.
	meshauthkeyDescMaxUses := meshauthkeyFields[4].Descriptor()
	// meshauthkey.DefaultMaxUses holds the default value on creation for the max_uses field.
	meshauthkey.DefaultMaxUses = meshauthkeyDescMaxUses.Default.(int)
	// meshauthkeyDescUses is the schema descriptor for uses field.
	meshauthkeyDescUses := meshauthkeyFields[5].Descriptor()
	// meshauthkey.DefaultUses holds the default value on creation for the uses field.
	meshauthkey.DefaultUses = meshauthkeyDescUses.Default.(int)
	// meshauthkeyDescNote is the schema descriptor for note field.
	meshauthkeyDescNote := meshauthkeyFields[8].Descriptor()
	// meshauthkey.DefaultNote holds the default value on creation for the note field.
	meshauthkey.DefaultNote = meshauthkeyDescNote.Default.(string)
	// meshauthkeyDescCreatedAt is the schema descriptor for created_at field.
	meshauthkeyDescCreatedAt := meshauthkeyFields[9].Descriptor()
	// meshauthkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	meshauthkey.DefaultCreatedAt = meshauthkeyDescCreatedAt.Default.(func() time.Time)
	meshconnrecordFields := schema.MeshConnRecord{}.Fields()
	_ = meshconnrecordFields
	// meshconnrecordDescBytesTx is the schema descriptor for bytes_tx field.
	meshconnrecordDescBytesTx := meshconnrecordFields[4].Descriptor()
	// meshconnrecord.DefaultBytesTx holds the default value on creation for the bytes_tx field.
	meshconnrecord.DefaultBytesTx = meshconnrecordDescBytesTx.Default.(int64)
	// meshconnrecordDescBytesRx is the schema descriptor for bytes_rx field.
	meshconnrecordDescBytesRx := meshconnrecordFields[5].Descriptor()
	// meshconnrecord.DefaultBytesRx holds the default value on creation for the bytes_rx field.
	meshconnrecord.DefaultBytesRx = meshconnrecordDescBytesRx.Default.(int64)
	// meshconnrecordDescPath is the schema descriptor for path field.
	meshconnrecordDescPath := meshconnrecordFields[6].Descriptor()
	// meshconnrecord.DefaultPath holds the default value on creation for the path field.
	meshconnrecord.DefaultPath = meshconnrecordDescPath.Default.(string)
	// meshconnrecordDescRelayBytesTx is the schema descriptor for relay_bytes_tx field.
	meshconnrecordDescRelayBytesTx := meshconnrecordFields[7].Descriptor()
	// meshconnrecord.DefaultRelayBytesTx holds the default value on creation for the relay_bytes_tx field.
	meshconnrecord.DefaultRelayBytesTx = meshconnrecordDescRelayBytesTx.Default.(int64)
	// meshconnrecordDescRelayBytesRx is the schema descriptor for relay_bytes_rx field.
	meshconnrecordDescRelayBytesRx := meshconnrecordFields[8].Descriptor()
	// meshconnrecord.DefaultRelayBytesRx holds the default value on creation for the relay_bytes_rx field.
	meshconnrecord.DefaultRelayBytesRx = meshconnrecordDescRelayBytesRx.Default.(int64)
	// meshconnrecordDescUpdatedAt is the schema descriptor for updated_at field.
	meshconnrecordDescUpdatedAt := meshconnrecordFields[9].Descriptor()
	// meshconnrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	meshconnrecord.DefaultUpdatedAt = meshconnrecordDescUpdatedAt.Default.(func() time.Time)
	// meshconnrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	meshconnrecord.UpdateDefaultUpdatedAt = meshconnrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	meshnodeFields := schema.MeshNode{}.Fields()
	_ = meshnodeFields
	// meshnodeDescNodeKey is the schema descriptor for node_key field.
	meshnodeDescNodeKey := meshnodeFields[1].Descriptor()
	// meshnode.NodeKeyValidator is a validator for the "node_key" field. It is called by the builders before save.
	meshnode.NodeKeyValidator = meshnodeDescNodeKey.Validators[0].(func(string) error)
	// meshnodeDescName is the schema descriptor for name field.
	meshnodeDescName := meshnodeFields[2].Descriptor()
	// meshnode.DefaultName holds the default value on creation for the name field.
	meshnode.DefaultName = meshnodeDescName.Default.(string)
	// meshnodeDescHostName is the schema descriptor for host_name field.
	meshnodeDescHostName := meshnodeFields[3].Descriptor()
	// meshnode.DefaultHostName holds the default value on creation for the host_name field.
	meshnode.DefaultHostName = meshnodeDescHostName.Default.(string)
	// meshnodeDescNamePinned is the schema descriptor for name_pinned field.
	meshnodeDescNamePinned := meshnodeFields[4].Descriptor()
	// meshnode.DefaultNamePinned holds the default value on creation for the name_pinned field.
	meshnode.DefaultNamePinned = meshnodeDescNamePinned.Default.(bool)
	// meshnodeDescDiscoKey is the schema descriptor for disco_key field.
	meshnodeDescDiscoKey := meshnodeFields[5].Descriptor()
	// meshnode.DefaultDiscoKey holds the default value on creation for the disco_key field.
	meshnode.DefaultDiscoKey = meshnodeDescDiscoKey.Default.(string)
	// meshnodeDescOverlay is the schema descriptor for overlay field.
	meshnodeDescOverlay := meshnodeFields[6].Descriptor()
	// meshnode.DefaultOverlay holds the default value on creation for the overlay field.
	meshnode.DefaultOverlay = meshnodeDescOverlay.Default.(string)
	// meshnodeDescDerpHome is the schema descriptor for derp_home field.
	meshnodeDescDerpHome := meshnodeFields[7].Descriptor()
	// meshnode.DefaultDerpHome holds the default value on creation for the derp_home field.
	meshnode.DefaultDerpHome = meshnodeDescDerpHome.Default.(string)
	// meshnodeDescEndpointsJSON is the schema descriptor for endpoints_json field.
	meshnodeDescEndpointsJSON := meshnodeFields[8].Descriptor()
	// meshnode.DefaultEndpointsJSON holds the default value on creation for the endpoints_json field.
	meshnode.DefaultEndpointsJSON = meshnodeDescEndpointsJSON.Default.(string)
	// meshnodeDescAdvertisedRoutesJSON is the schema descriptor for advertised_routes_json field.
	meshnodeDescAdvertisedRoutesJSON := meshnodeFields[9].Descriptor()
	// meshnode.DefaultAdvertisedRoutesJSON holds the default value on creation for the advertised_routes_json field.
	meshnode.DefaultAdvertisedRoutesJSON = meshnodeDescAdvertisedRoutesJSON.Default.(string)
	// meshnodeDescApprovedRoutesJSON is the schema descriptor for approved_routes_json field.
	meshnodeDescApprovedRoutesJSON := meshnodeFields[10].Descriptor()
	// meshnode.DefaultApprovedRoutesJSON holds the default value on creation for the approved_routes_json field.
	meshnode.DefaultApprovedRoutesJSON = meshnodeDescApprovedRoutesJSON.Default.(string)
	// meshnodeDescAliasedRoutesJSON is the schema descriptor for aliased_routes_json field.
	meshnodeDescAliasedRoutesJSON := meshnodeFields[11].Descriptor()
	// meshnode.DefaultAliasedRoutesJSON holds the default value on creation for the aliased_routes_json field.
	meshnode.DefaultAliasedRoutesJSON = meshnodeDescAliasedRoutesJSON.Default.(string)
	// meshnodeDescRouteAliasesJSON is the schema descriptor for route_aliases_json field.
	meshnodeDescRouteAliasesJSON := meshnodeFields[12].Descriptor()
	// meshnode.DefaultRouteAliasesJSON holds the default value on creation for the route_aliases_json field.
	meshnode.DefaultRouteAliasesJSON = meshnodeDescRouteAliasesJSON.Default.(string)
	// meshnodeDescRoutesReviewed is the schema descriptor for routes_reviewed field.
	meshnodeDescRoutesReviewed := meshnodeFields[13].Descriptor()
	// meshnode.DefaultRoutesReviewed holds the default value on creation for the routes_reviewed field.
	meshnode.DefaultRoutesReviewed = meshnodeDescRoutesReviewed.Default.(bool)
	// meshnodeDescOwnerUserID is the schema descriptor for owner_user_id field.
	meshnodeDescOwnerUserID := meshnodeFields[14].Descriptor()
	// meshnode.DefaultOwnerUserID holds the default value on creation for the owner_user_id field.
	meshnode.DefaultOwnerUserID = meshnodeDescOwnerUserID.Default.(int64)
	// meshnodeDescDeviceFingerprint is the schema descriptor for device_fingerprint field.
	meshnodeDescDeviceFingerprint := meshnodeFields[15].Descriptor()
	// meshnode.DefaultDeviceFingerprint holds the default value on creation for the device_fingerprint field.
	meshnode.DefaultDeviceFingerprint = meshnodeDescDeviceFingerprint.Default.(string)
	// meshnodeDescOs is the schema descriptor for os field.
	meshnodeDescOs := meshnodeFields[16].Descriptor()
	// meshnode.DefaultOs holds the default value on creation for the os field.
	meshnode.DefaultOs = meshnodeDescOs.Default.(string)
	// meshnodeDescTagsPinned is the schema descriptor for tags_pinned field.
	meshnodeDescTagsPinned := meshnodeFields[18].Descriptor()
	// meshnode.DefaultTagsPinned holds the default value on creation for the tags_pinned field.
	meshnode.DefaultTagsPinned = meshnodeDescTagsPinned.Default.(bool)
	// meshnodeDescTagsJSON is the schema descriptor for tags_json field.
	meshnodeDescTagsJSON := meshnodeFields[19].Descriptor()
	// meshnode.DefaultTagsJSON holds the default value on creation for the tags_json field.
	meshnode.DefaultTagsJSON = meshnodeDescTagsJSON.Default.(string)
	// meshnodeDescApproved is the schema descriptor for approved field.
	meshnodeDescApproved := meshnodeFields[20].Descriptor()
	// meshnode.DefaultApproved holds the default value on creation for the approved field.
	meshnode.DefaultApproved = meshnodeDescApproved.Default.(bool)
	// meshnodeDescDisabled is the schema descriptor for disabled field.
	meshnodeDescDisabled := meshnodeFields[21].Descriptor()
	// meshnode.DefaultDisabled holds the default value on creation for the disabled field.
	meshnode.DefaultDisabled = meshnodeDescDisabled.Default.(bool)
	// meshnodeDescEnrolledBy is the schema descriptor for enrolled_by field.
	meshnodeDescEnrolledBy := meshnodeFields[22].Descriptor()
	// meshnode.DefaultEnrolledBy holds the default value on creation for the enrolled_by field.
	meshnode.DefaultEnrolledBy = meshnodeDescEnrolledBy.Default.(string)
	// meshnodeDescSignedOut is the schema descriptor for signed_out field.
	meshnodeDescSignedOut := meshnodeFields[23].Descriptor()
	// meshnode.DefaultSignedOut holds the default value on creation for the signed_out field.
	meshnode.DefaultSignedOut = meshnodeDescSignedOut.Default.(bool)
	// meshnodeDescCreatedAt is the schema descriptor for created_at field.
	meshnodeDescCreatedAt := meshnodeFields[24].Descriptor()
	// meshnode.DefaultCreatedAt holds the default value on creation for the created_at field.
	meshnode.DefaultCreatedAt = meshnodeDescCreatedAt.Default.(func() time.Time)
	// meshnodeDescLastSeen is the schema descriptor for last_seen field.
	meshnodeDescLastSeen := meshnodeFields[25].Descriptor()
	// meshnode.DefaultLastSeen holds the default value on creation for the last_seen field.
	meshnode.DefaultLastSeen = meshnodeDescLastSeen.Default.(func() time.Time)
	// meshnode.UpdateDefaultLastSeen holds the default value on update for the last_seen field.
	meshnode.UpdateDefaultLastSeen = meshnodeDescLastSeen.UpdateDefault.(func() time.Time)
	meshrelayFields := schema.MeshRelay{}.Fields()
	_ = meshrelayFields
	// meshrelayDescDerpPort is the schema descriptor for derp_port field.
	meshrelayDescDerpPort := meshrelayFields[3].Descriptor()
	// meshrelay.DefaultDerpPort holds the default value on creation for the derp_port field.
	meshrelay.DefaultDerpPort = meshrelayDescDerpPort.Default.(int)
	// meshrelayDescStunPort is the schema descriptor for stun_port field.
	meshrelayDescStunPort := meshrelayFields[4].Descriptor()
	// meshrelay.DefaultStunPort holds the default value on creation for the stun_port field.
	meshrelay.DefaultStunPort = meshrelayDescStunPort.Default.(int)
	// meshrelayDescEnabled is the schema descriptor for enabled field.
	meshrelayDescEnabled := meshrelayFields[5].Descriptor()
	// meshrelay.DefaultEnabled holds the default value on creation for the enabled field.
	meshrelay.DefaultEnabled = meshrelayDescEnabled.Default.(bool)
	// meshrelayDescCreatedAt is the schema descriptor for created_at field.
	meshrelayDescCreatedAt := meshrelayFields[6].Descriptor()
	// meshrelay.DefaultCreatedAt holds the default value on creation for the created_at field.
	meshrelay.DefaultCreatedAt = meshrelayDescCreatedAt.Default.(func() time.Time)
	meshserviceFields := schema.MeshService{}.Fields()
	_ = meshserviceFields
	// meshserviceDescProto is the schema descriptor for proto field.
	meshserviceDescProto := meshserviceFields[3].Descriptor()
	// meshservice.DefaultProto holds the default value on creation for the proto field.
	meshservice.DefaultProto = meshserviceDescProto.Default.(string)
	// meshserviceDescTarget is the schema descriptor for target field.
	meshserviceDescTarget := meshserviceFields[5].Descriptor()
	// meshservice.DefaultTarget holds the default value on creation for the target field.
	meshservice.DefaultTarget = meshserviceDescTarget.Default.(string)
	// meshserviceDescNote is the schema descriptor for note field.
	meshserviceDescNote := meshserviceFields[6].Descriptor()
	// meshservice.DefaultNote holds the default value on creation for the note field.
	meshservice.DefaultNote = meshserviceDescNote.Default.(string)
	// meshserviceDescSource is the schema descriptor for source field.
	meshserviceDescSource := meshserviceFields[7].Descriptor()
	// meshservice.DefaultSource holds the default value on creation for the source field.
	meshservice.DefaultSource = meshserviceDescSource.Default.(string)
	// meshserviceDescApproved is the schema descriptor for approved field.
	meshserviceDescApproved := meshserviceFields[8].Descriptor()
	// meshservice.DefaultApproved holds the default value on creation for the approved field.
	meshservice.DefaultApproved = meshserviceDescApproved.Default.(bool)
	// meshserviceDescCreatedAt is the schema descriptor for created_at field.
	meshserviceDescCreatedAt := meshserviceFields[9].Descriptor()
	// meshservice.DefaultCreatedAt holds the default value on creation for the created_at field.
	meshservice.DefaultCreatedAt = meshserviceDescCreatedAt.Default.(func() time.Time)
	meshsettingFields := schema.MeshSetting{}.Fields()
	_ = meshsettingFields
	// meshsettingDescAliasAddrBudget is the schema descriptor for alias_addr_budget field.
	meshsettingDescAliasAddrBudget := meshsettingFields[1].Descriptor()
	// meshsetting.DefaultAliasAddrBudget holds the default value on creation for the alias_addr_budget field.
	meshsetting.DefaultAliasAddrBudget = meshsettingDescAliasAddrBudget.Default.(int)
	// meshsettingDescRequireDeviceApproval is the schema descriptor for require_device_approval field.
	meshsettingDescRequireDeviceApproval := meshsettingFields[2].Descriptor()
	// meshsetting.DefaultRequireDeviceApproval holds the default value on creation for the require_device_approval field.
	meshsetting.DefaultRequireDeviceApproval = meshsettingDescRequireDeviceApproval.Default.(bool)
	// meshsettingDescConnRecordsDisabled is the schema descriptor for conn_records_disabled field.
	meshsettingDescConnRecordsDisabled := meshsettingFields[3].Descriptor()
	// meshsetting.DefaultConnRecordsDisabled holds the default value on creation for the conn_records_disabled field.
	meshsetting.DefaultConnRecordsDisabled = meshsettingDescConnRecordsDisabled.Default.(bool)
	// meshsettingDescAutoApproveRoutes is the schema descriptor for auto_approve_routes field.
	meshsettingDescAutoApproveRoutes := meshsettingFields[4].Descriptor()
	// meshsetting.DefaultAutoApproveRoutes holds the default value on creation for the auto_approve_routes field.
	meshsetting.DefaultAutoApproveRoutes = meshsettingDescAutoApproveRoutes.Default.(bool)
	// meshsettingDescUpdatedAt is the schema descriptor for updated_at field.
	meshsettingDescUpdatedAt := meshsettingFields[5].Descriptor()
	// meshsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	meshsetting.DefaultUpdatedAt = meshsettingDescUpdatedAt.Default.(func() time.Time)
	// meshsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	meshsetting.UpdateDefaultUpdatedAt = meshsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	meshtunnelFields := schema.MeshTunnel{}.Fields()
	_ = meshtunnelFields
	// meshtunnelDescPublicAddr is the schema descriptor for public_addr field.
	meshtunnelDescPublicAddr := meshtunnelFields[4].Descriptor()
	// meshtunnel.DefaultPublicAddr holds the default value on creation for the public_addr field.
	meshtunnel.DefaultPublicAddr = meshtunnelDescPublicAddr.Default.(string)
	// meshtunnelDescLocalAddr is the schema descriptor for local_addr field.
	meshtunnelDescLocalAddr := meshtunnelFields[5].Descriptor()
	// meshtunnel.DefaultLocalAddr holds the default value on creation for the local_addr field.
	meshtunnel.DefaultLocalAddr = meshtunnelDescLocalAddr.Default.(string)
	// meshtunnelDescStatus is the schema descriptor for status field.
	meshtunnelDescStatus := meshtunnelFields[6].Descriptor()
	// meshtunnel.DefaultStatus holds the default value on creation for the status field.
	meshtunnel.DefaultStatus = meshtunnelDescStatus.Default.(string)
	meshtunnelusageFields := schema.MeshTunnelUsage{}.Fields()
	_ = meshtunnelusageFields
	// meshtunnelusageDescBytesIn is the schema descriptor for bytes_in field.
	meshtunnelusageDescBytesIn := meshtunnelusageFields[4].Descriptor()
	// meshtunnelusage.DefaultBytesIn holds the default value on creation for the bytes_in field.
	meshtunnelusage.DefaultBytesIn = meshtunnelusageDescBytesIn.Default.(int64)
	// meshtunnelusageDescBytesOut is the schema descriptor for bytes_out field.
	meshtunnelusageDescBytesOut := meshtunnelusageFields[5].Descriptor()
	// meshtunnelusage.DefaultBytesOut holds the default value on creation for the bytes_out field.
	meshtunnelusage.DefaultBytesOut = meshtunnelusageDescBytesOut.Default.(int64)
}
