// Code generated by ent, DO NOT EDIT.

package meshtunnelusage

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the meshtunnelusage type in the database.
	Label = "mesh_tunnel_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMeshnetID holds the string denoting the meshnet_id field in the database.
	FieldMeshnetID = "meshnet_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldHour holds the string denoting the hour field in the database.
	FieldHour = "hour"
	// FieldBytesIn holds the string denoting the bytes_in field in the database.
	FieldBytesIn = "bytes_in"
	// FieldBytesOut holds the string denoting the bytes_out field in the database.
	FieldBytesOut = "bytes_out"
	// Table holds the table name of the meshtunnelusage in the database.
	Table = "mesh_tunnel_usage"
)

// Columns holds all SQL columns for meshtunnelusage fields.
var Columns = []string{
	FieldID,
	FieldMeshnetID,
	FieldNodeID,
	FieldName,
	FieldHour,
	FieldBytesIn,
	FieldBytesOut,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBytesIn holds the default value on creation for the "bytes_in" field.
	DefaultBytesIn int64
	// DefaultBytesOut holds the default value on creation for the "bytes_out" field.
	DefaultBytesOut int64
)

// OrderOption defines the ordering options for the MeshTunnelUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMeshnetID orders the results by the meshnet_id field.
func ByMeshnetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeshnetID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByHour orders the results by the hour field.
func ByHour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHour, opts...).ToFunc()
}

// ByBytesIn orders the results by the bytes_in field.
func ByBytesIn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBytesIn, opts...).ToFunc()
}

// ByBytesOut orders the results by the bytes_out field.
func ByBytesOut(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBytesOut, opts...).ToFunc()
}
