// bff-edge is the public gRPC gateway that multi-region calabi-edges use
// to reach the control plane. Edges in the same Kubernetes cluster as
// the control plane can still dial each microservice's ClusterIP
// directly — bff-edge only matters for cross-region edges (cn-hangzhou
// ECS → cn-chengdu ACK control plane), where the control-plane svcs
// stay private and bff-edge fronts them on a single mTLS gRPC port.
//
// The wire shape mirrors what calabi-edge already calls on identity-svc /
// tunnel-svc / cert-svc / quota-svc / config-svc + a handful of
// NATS-subject pumps wrapped as server-streams (cert events, session
// evict, usage deny/allow). Reverse direction (edge → NATS publish of
// usage reports) is collapsed into a regular unary RPC.
//
// Authn: mTLS client cert, CN = "edge-{edge_node_id}-{region}". bff-edge
// parses the CN, looks the edge up in identity-svc, and injects the
// resolved edge_node_id into the request context. Every RPC handler
// overwrites the edge_node_id field on incoming requests with the
// authenticated id — body-supplied values are NEVER trusted, so an
// edge with a valid cert for edge_id=42 cannot impersonate edge_id=7.
//
// Versioning: append-only field tags; no renames. v1 frozen at first
// release.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: edgepb/bff_edge.proto

package edgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RenewEdgeCertRequest carries no fields on purpose: the edge's identity
// (org_id + edge_node_id) is taken from its authenticated mTLS client cert,
// never from the request body. See BFFEdge.RenewEdgeCert.
type RenewEdgeCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewEdgeCertRequest) Reset() {
	*x = RenewEdgeCertRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewEdgeCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewEdgeCertRequest) ProtoMessage() {}

func (x *RenewEdgeCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewEdgeCertRequest.ProtoReflect.Descriptor instead.
func (*RenewEdgeCertRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{0}
}

type SubscribeCertEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 = subscribe to all orgs.
	// Future: per-org scoping when edge knows which orgs it serves.
	OrgId         int64 `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeCertEventsRequest) Reset() {
	*x = SubscribeCertEventsRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeCertEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeCertEventsRequest) ProtoMessage() {}

func (x *SubscribeCertEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeCertEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeCertEventsRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeCertEventsRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

type CertEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "upsert" | "delete"
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Cluster-side NATS subject this event came from (e.g.
	// "calabi.cert.upsert.42"). Useful for edge-side debug logging.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Body is the raw JSON the NATS subscriber would have received.
	// The edge passes it straight to certclient.onUpsert / onDelete.
	BodyJson      []byte `protobuf:"bytes,3,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertEvent) Reset() {
	*x = CertEvent{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertEvent) ProtoMessage() {}

func (x *CertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertEvent.ProtoReflect.Descriptor instead.
func (*CertEvent) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{2}
}

func (x *CertEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CertEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CertEvent) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type SubscribeTunnelEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTunnelEventsRequest) Reset() {
	*x = SubscribeTunnelEventsRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTunnelEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTunnelEventsRequest) ProtoMessage() {}

func (x *SubscribeTunnelEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTunnelEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTunnelEventsRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{3}
}

type TunnelEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "created" | "updated" | "deleted"
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Subject       string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	BodyJson      []byte `protobuf:"bytes,3,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelEvent) Reset() {
	*x = TunnelEvent{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelEvent) ProtoMessage() {}

func (x *TunnelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelEvent.ProtoReflect.Descriptor instead.
func (*TunnelEvent) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TunnelEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TunnelEvent) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type SubscribeSessionEvictEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeSessionEvictEventsRequest) Reset() {
	*x = SubscribeSessionEvictEventsRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSessionEvictEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSessionEvictEventsRequest) ProtoMessage() {}

func (x *SubscribeSessionEvictEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSessionEvictEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeSessionEvictEventsRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{5}
}

type SessionEvictEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// calabi.session.evict.<client_id> message body. The edge already
	// parses {client_id, reason}.
	Subject       string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	BodyJson      []byte `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvictEvent) Reset() {
	*x = SessionEvictEvent{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvictEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvictEvent) ProtoMessage() {}

func (x *SessionEvictEvent) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvictEvent.ProtoReflect.Descriptor instead.
func (*SessionEvictEvent) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{6}
}

func (x *SessionEvictEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SessionEvictEvent) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type SubscribeUsageEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUsageEventsRequest) Reset() {
	*x = SubscribeUsageEventsRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUsageEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUsageEventsRequest) ProtoMessage() {}

func (x *SubscribeUsageEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUsageEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeUsageEventsRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{7}
}

type UsageEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "deny" | "allow"
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Subject       string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	BodyJson      []byte `protobuf:"bytes,3,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageEvent) Reset() {
	*x = UsageEvent{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageEvent) ProtoMessage() {}

func (x *UsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageEvent.ProtoReflect.Descriptor instead.
func (*UsageEvent) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{8}
}

func (x *UsageEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UsageEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UsageEvent) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

type UsageReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	OrgId    int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	BytesIn  int64                  `protobuf:"varint,2,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut int64                  `protobuf:"varint,3,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	// Edge-local timestamp when this 1-minute bucket closed.
	WindowCloseAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=window_close_at,json=windowCloseAt,proto3" json:"window_close_at,omitempty"`
	// tunnel_id the bytes are attributed to. 0 = unattributed
	// (standalone proxy / session-level fallback). bff-edge passes this
	// through verbatim onto the NATS report; metering-svc keys on it.
	TunnelId      int64 `protobuf:"varint,5,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{9}
}

func (x *UsageReport) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *UsageReport) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *UsageReport) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *UsageReport) GetWindowCloseAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowCloseAt
	}
	return nil
}

func (x *UsageReport) GetTunnelId() int64 {
	if x != nil {
		return x.TunnelId
	}
	return 0
}

type ReportUsageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// edge_node_id is OVERWRITTEN by bff-edge from the mTLS cert before
	// re-publishing — body value is ignored.
	EdgeNodeId    int64          `protobuf:"varint,1,opt,name=edge_node_id,json=edgeNodeId,proto3" json:"edge_node_id,omitempty"`
	Reports       []*UsageReport `protobuf:"bytes,2,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageRequest) Reset() {
	*x = ReportUsageRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageRequest) ProtoMessage() {}

func (x *ReportUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportUsageRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{10}
}

func (x *ReportUsageRequest) GetEdgeNodeId() int64 {
	if x != nil {
		return x.EdgeNodeId
	}
	return 0
}

func (x *ReportUsageRequest) GetReports() []*UsageReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ReportUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count of reports re-published. Diagnostic only.
	Published     int32 `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageResponse) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{11}
}

func (x *ReportUsageResponse) GetPublished() int32 {
	if x != nil {
		return x.Published
	}
	return 0
}

type RelayUsageReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Region code the bytes are attributed to, e.g. "self-hk-1". A BYOI node's
	// relay is self-hosted, so bff-edge requires the "self-" prefix and drops a
	// report that lacks it (defense against a report that would land in the cap).
	Region   string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	BytesIn  int64  `protobuf:"varint,3,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut int64  `protobuf:"varint,4,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	// Edge-local timestamp of this 1-minute running-total bucket. The reporter
	// re-sends the running total for the current minute; metering-svc MAX-merges.
	WindowCloseAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=window_close_at,json=windowCloseAt,proto3" json:"window_close_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayUsageReport) Reset() {
	*x = RelayUsageReport{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUsageReport) ProtoMessage() {}

func (x *RelayUsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUsageReport.ProtoReflect.Descriptor instead.
func (*RelayUsageReport) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{12}
}

func (x *RelayUsageReport) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *RelayUsageReport) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RelayUsageReport) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *RelayUsageReport) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *RelayUsageReport) GetWindowCloseAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowCloseAt
	}
	return nil
}

type ReportRelayUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*RelayUsageReport    `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRelayUsageRequest) Reset() {
	*x = ReportRelayUsageRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRelayUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRelayUsageRequest) ProtoMessage() {}

func (x *ReportRelayUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRelayUsageRequest.ProtoReflect.Descriptor instead.
func (*ReportRelayUsageRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{13}
}

func (x *ReportRelayUsageRequest) GetReports() []*RelayUsageReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ReportRelayUsageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count of reports re-published. Diagnostic only.
	Published     int32 `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRelayUsageResponse) Reset() {
	*x = ReportRelayUsageResponse{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRelayUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRelayUsageResponse) ProtoMessage() {}

func (x *ReportRelayUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRelayUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportRelayUsageResponse) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{14}
}

func (x *ReportRelayUsageResponse) GetPublished() int32 {
	if x != nil {
		return x.Published
	}
	return 0
}

type RegisterRelayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org_id is NOT carried — bff-edge derives the org from the mTLS cert, so a
	// node can only register a relay for its own org.
	Label         string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // region code = "self-"+label
	Host          string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`   // public host:… mesh nodes dial the relay at
	DerpPort      int32  `protobuf:"varint,3,opt,name=derp_port,json=derpPort,proto3" json:"derp_port,omitempty"`
	StunPort      int32  `protobuf:"varint,4,opt,name=stun_port,json=stunPort,proto3" json:"stun_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRelayRequest) Reset() {
	*x = RegisterRelayRequest{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRelayRequest) ProtoMessage() {}

func (x *RegisterRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRelayRequest.ProtoReflect.Descriptor instead.
func (*RegisterRelayRequest) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterRelayRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RegisterRelayRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterRelayRequest) GetDerpPort() int32 {
	if x != nil {
		return x.DerpPort
	}
	return 0
}

func (x *RegisterRelayRequest) GetStunPort() int32 {
	if x != nil {
		return x.StunPort
	}
	return 0
}

type RegisterRelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Region the relay landed under, e.g. "self-hk-1". Diagnostic.
	Region        string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRelayResponse) Reset() {
	*x = RegisterRelayResponse{}
	mi := &file_edgepb_bff_edge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRelayResponse) ProtoMessage() {}

func (x *RegisterRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edgepb_bff_edge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRelayResponse.ProtoReflect.Descriptor instead.
func (*RegisterRelayResponse) Descriptor() ([]byte, []int) {
	return file_edgepb_bff_edge_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterRelayResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_edgepb_bff_edge_proto protoreflect.FileDescriptor

const file_edgepb_bff_edge_proto_rawDesc = "" +
	"\n" +
	"\x15edgepb/bff_edge.proto\x12\x12calabi.v1.bff_edge\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15edgepb/messages.proto\"\x16\n" +
	"\x14RenewEdgeCertRequest\"3\n" +
	"\x1aSubscribeCertEventsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\"V\n" +
	"\tCertEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_json\x18\x03 \x01(\fR\bbodyJson\"\x1e\n" +
	"\x1cSubscribeTunnelEventsRequest\"X\n" +
	"\vTunnelEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_json\x18\x03 \x01(\fR\bbodyJson\"$\n" +
	"\"SubscribeSessionEvictEventsRequest\"J\n" +
	"\x11SessionEvictEvent\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\fR\bbodyJson\"\x1d\n" +
	"\x1bSubscribeUsageEventsRequest\"W\n" +
	"\n" +
	"UsageEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_json\x18\x03 \x01(\fR\bbodyJson\"\xbd\x01\n" +
	"\vUsageReport\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x19\n" +
	"\bbytes_in\x18\x02 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x03 \x01(\x03R\bbytesOut\x12B\n" +
	"\x0fwindow_close_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rwindowCloseAt\x12\x1b\n" +
	"\ttunnel_id\x18\x05 \x01(\x03R\btunnelId\"q\n" +
	"\x12ReportUsageRequest\x12 \n" +
	"\fedge_node_id\x18\x01 \x01(\x03R\n" +
	"edgeNodeId\x129\n" +
	"\areports\x18\x02 \x03(\v2\x1f.calabi.v1.bff_edge.UsageReportR\areports\"3\n" +
	"\x13ReportUsageResponse\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\x05R\tpublished\"\xbd\x01\n" +
	"\x10RelayUsageReport\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x19\n" +
	"\bbytes_in\x18\x03 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x04 \x01(\x03R\bbytesOut\x12B\n" +
	"\x0fwindow_close_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rwindowCloseAt\"Y\n" +
	"\x17ReportRelayUsageRequest\x12>\n" +
	"\areports\x18\x01 \x03(\v2$.calabi.v1.bff_edge.RelayUsageReportR\areports\"8\n" +
	"\x18ReportRelayUsageResponse\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\x05R\tpublished\"z\n" +
	"\x14RegisterRelayRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1b\n" +
	"\tderp_port\x18\x03 \x01(\x05R\bderpPort\x12\x1b\n" +
	"\tstun_port\x18\x04 \x01(\x05R\bstunPort\"/\n" +
	"\x15RegisterRelayResponse\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region2\xaf\x15\n" +
	"\aBFFEdge\x12d\n" +
	"\rValidateToken\x12(.calabi.v1.bff_edge.ValidateTokenRequest\x1a).calabi.v1.bff_edge.ValidateTokenResponse\x12m\n" +
	"\x10RegisterEdgeNode\x12+.calabi.v1.bff_edge.RegisterEdgeNodeRequest\x1a,.calabi.v1.bff_edge.RegisterEdgeNodeResponse\x12y\n" +
	"\x14ReportClientPresence\x12/.calabi.v1.bff_edge.ReportClientPresenceRequest\x1a0.calabi.v1.bff_edge.ReportClientPresenceResponse\x12p\n" +
	"\x11GetOrgOnlineCount\x12,.calabi.v1.bff_edge.GetOrgOnlineCountRequest\x1a-.calabi.v1.bff_edge.GetOrgOnlineCountResponse\x12X\n" +
	"\tListEdges\x12$.calabi.v1.bff_edge.ListEdgesRequest\x1a%.calabi.v1.bff_edge.ListEdgesResponse\x12S\n" +
	"\fCreateTunnel\x12'.calabi.v1.bff_edge.CreateTunnelRequest\x1a\x1a.calabi.v1.bff_edge.Tunnel\x12Q\n" +
	"\vClaimTunnel\x12&.calabi.v1.bff_edge.ClaimTunnelRequest\x1a\x1a.calabi.v1.bff_edge.Tunnel\x12a\n" +
	"\fReportStatus\x12'.calabi.v1.bff_edge.ReportStatusRequest\x1a(.calabi.v1.bff_edge.ReportStatusResponse\x12^\n" +
	"\vListTunnels\x12&.calabi.v1.bff_edge.ListTunnelsRequest\x1a'.calabi.v1.bff_edge.ListTunnelsResponse\x12y\n" +
	"\x14ListEdgeClaimedPorts\x12/.calabi.v1.bff_edge.ListEdgeClaimedPortsRequest\x1a0.calabi.v1.bff_edge.ListEdgeClaimedPortsResponse\x12a\n" +
	"\fDeleteTunnel\x12'.calabi.v1.bff_edge.DeleteTunnelRequest\x1a(.calabi.v1.bff_edge.DeleteTunnelResponse\x12R\n" +
	"\aResolve\x12\".calabi.v1.bff_edge.ResolveRequest\x1a#.calabi.v1.bff_edge.ResolveResponse\x12d\n" +
	"\rResolveOwners\x12(.calabi.v1.bff_edge.ResolveOwnersRequest\x1a).calabi.v1.bff_edge.ResolveOwnersResponse\x12d\n" +
	"\rReclaimTunnel\x12(.calabi.v1.bff_edge.ReclaimTunnelRequest\x1a).calabi.v1.bff_edge.ReclaimTunnelResponse\x12X\n" +
	"\tDrainEdge\x12$.calabi.v1.bff_edge.DrainEdgeRequest\x1a%.calabi.v1.bff_edge.DrainEdgeResponse\x12R\n" +
	"\aGetCert\x12\".calabi.v1.bff_edge.GetCertRequest\x1a#.calabi.v1.bff_edge.GetCertResponse\x12X\n" +
	"\tListCerts\x12$.calabi.v1.bff_edge.ListCertsRequest\x1a%.calabi.v1.bff_edge.ListCertsResponse\x12d\n" +
	"\rRenewEdgeCert\x12(.calabi.v1.bff_edge.RenewEdgeCertRequest\x1a).calabi.v1.bff_edge.IssueEdgeCertResponse\x12`\n" +
	"\x11GetEffectiveQuota\x12'.calabi.v1.bff_edge.GetEffectiveRequest\x1a\".calabi.v1.bff_edge.EffectiveQuota\x12Y\n" +
	"\x0fSubscribeConfig\x12\x1f.calabi.v1.bff_edge.EdgeMessage\x1a!.calabi.v1.bff_edge.ConfigMessage(\x010\x01\x12f\n" +
	"\x13SubscribeCertEvents\x12..calabi.v1.bff_edge.SubscribeCertEventsRequest\x1a\x1d.calabi.v1.bff_edge.CertEvent0\x01\x12l\n" +
	"\x15SubscribeTunnelEvents\x120.calabi.v1.bff_edge.SubscribeTunnelEventsRequest\x1a\x1f.calabi.v1.bff_edge.TunnelEvent0\x01\x12~\n" +
	"\x1bSubscribeSessionEvictEvents\x126.calabi.v1.bff_edge.SubscribeSessionEvictEventsRequest\x1a%.calabi.v1.bff_edge.SessionEvictEvent0\x01\x12i\n" +
	"\x14SubscribeUsageEvents\x12/.calabi.v1.bff_edge.SubscribeUsageEventsRequest\x1a\x1e.calabi.v1.bff_edge.UsageEvent0\x01\x12^\n" +
	"\vReportUsage\x12&.calabi.v1.bff_edge.ReportUsageRequest\x1a'.calabi.v1.bff_edge.ReportUsageResponse\x12m\n" +
	"\x10ReportRelayUsage\x12+.calabi.v1.bff_edge.ReportRelayUsageRequest\x1a,.calabi.v1.bff_edge.ReportRelayUsageResponse\x12d\n" +
	"\rRegisterRelay\x12(.calabi.v1.bff_edge.RegisterRelayRequest\x1a).calabi.v1.bff_edge.RegisterRelayResponseB7Z5github.com/calabi/calabi/pkg/edge-proto/edgepb;edgepbb\x06proto3"

var (
	file_edgepb_bff_edge_proto_rawDescOnce sync.Once
	file_edgepb_bff_edge_proto_rawDescData []byte
)

func file_edgepb_bff_edge_proto_rawDescGZIP() []byte {
	file_edgepb_bff_edge_proto_rawDescOnce.Do(func() {
		file_edgepb_bff_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edgepb_bff_edge_proto_rawDesc), len(file_edgepb_bff_edge_proto_rawDesc)))
	})
	return file_edgepb_bff_edge_proto_rawDescData
}

var file_edgepb_bff_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_edgepb_bff_edge_proto_goTypes = []any{
	(*RenewEdgeCertRequest)(nil),               // 0: calabi.v1.bff_edge.RenewEdgeCertRequest
	(*SubscribeCertEventsRequest)(nil),         // 1: calabi.v1.bff_edge.SubscribeCertEventsRequest
	(*CertEvent)(nil),                          // 2: calabi.v1.bff_edge.CertEvent
	(*SubscribeTunnelEventsRequest)(nil),       // 3: calabi.v1.bff_edge.SubscribeTunnelEventsRequest
	(*TunnelEvent)(nil),                        // 4: calabi.v1.bff_edge.TunnelEvent
	(*SubscribeSessionEvictEventsRequest)(nil), // 5: calabi.v1.bff_edge.SubscribeSessionEvictEventsRequest
	(*SessionEvictEvent)(nil),                  // 6: calabi.v1.bff_edge.SessionEvictEvent
	(*SubscribeUsageEventsRequest)(nil),        // 7: calabi.v1.bff_edge.SubscribeUsageEventsRequest
	(*UsageEvent)(nil),                         // 8: calabi.v1.bff_edge.UsageEvent
	(*UsageReport)(nil),                        // 9: calabi.v1.bff_edge.UsageReport
	(*ReportUsageRequest)(nil),                 // 10: calabi.v1.bff_edge.ReportUsageRequest
	(*ReportUsageResponse)(nil),                // 11: calabi.v1.bff_edge.ReportUsageResponse
	(*RelayUsageReport)(nil),                   // 12: calabi.v1.bff_edge.RelayUsageReport
	(*ReportRelayUsageRequest)(nil),            // 13: calabi.v1.bff_edge.ReportRelayUsageRequest
	(*ReportRelayUsageResponse)(nil),           // 14: calabi.v1.bff_edge.ReportRelayUsageResponse
	(*RegisterRelayRequest)(nil),               // 15: calabi.v1.bff_edge.RegisterRelayRequest
	(*RegisterRelayResponse)(nil),              // 16: calabi.v1.bff_edge.RegisterRelayResponse
	(*timestamppb.Timestamp)(nil),              // 17: google.protobuf.Timestamp
	(*ValidateTokenRequest)(nil),               // 18: calabi.v1.bff_edge.ValidateTokenRequest
	(*RegisterEdgeNodeRequest)(nil),            // 19: calabi.v1.bff_edge.RegisterEdgeNodeRequest
	(*ReportClientPresenceRequest)(nil),        // 20: calabi.v1.bff_edge.ReportClientPresenceRequest
	(*GetOrgOnlineCountRequest)(nil),           // 21: calabi.v1.bff_edge.GetOrgOnlineCountRequest
	(*ListEdgesRequest)(nil),                   // 22: calabi.v1.bff_edge.ListEdgesRequest
	(*CreateTunnelRequest)(nil),                // 23: calabi.v1.bff_edge.CreateTunnelRequest
	(*ClaimTunnelRequest)(nil),                 // 24: calabi.v1.bff_edge.ClaimTunnelRequest
	(*ReportStatusRequest)(nil),                // 25: calabi.v1.bff_edge.ReportStatusRequest
	(*ListTunnelsRequest)(nil),                 // 26: calabi.v1.bff_edge.ListTunnelsRequest
	(*ListEdgeClaimedPortsRequest)(nil),        // 27: calabi.v1.bff_edge.ListEdgeClaimedPortsRequest
	(*DeleteTunnelRequest)(nil),                // 28: calabi.v1.bff_edge.DeleteTunnelRequest
	(*ResolveRequest)(nil),                     // 29: calabi.v1.bff_edge.ResolveRequest
	(*ResolveOwnersRequest)(nil),               // 30: calabi.v1.bff_edge.ResolveOwnersRequest
	(*ReclaimTunnelRequest)(nil),               // 31: calabi.v1.bff_edge.ReclaimTunnelRequest
	(*DrainEdgeRequest)(nil),                   // 32: calabi.v1.bff_edge.DrainEdgeRequest
	(*GetCertRequest)(nil),                     // 33: calabi.v1.bff_edge.GetCertRequest
	(*ListCertsRequest)(nil),                   // 34: calabi.v1.bff_edge.ListCertsRequest
	(*GetEffectiveRequest)(nil),                // 35: calabi.v1.bff_edge.GetEffectiveRequest
	(*EdgeMessage)(nil),                        // 36: calabi.v1.bff_edge.EdgeMessage
	(*ValidateTokenResponse)(nil),              // 37: calabi.v1.bff_edge.ValidateTokenResponse
	(*RegisterEdgeNodeResponse)(nil),           // 38: calabi.v1.bff_edge.RegisterEdgeNodeResponse
	(*ReportClientPresenceResponse)(nil),       // 39: calabi.v1.bff_edge.ReportClientPresenceResponse
	(*GetOrgOnlineCountResponse)(nil),          // 40: calabi.v1.bff_edge.GetOrgOnlineCountResponse
	(*ListEdgesResponse)(nil),                  // 41: calabi.v1.bff_edge.ListEdgesResponse
	(*Tunnel)(nil),                             // 42: calabi.v1.bff_edge.Tunnel
	(*ReportStatusResponse)(nil),               // 43: calabi.v1.bff_edge.ReportStatusResponse
	(*ListTunnelsResponse)(nil),                // 44: calabi.v1.bff_edge.ListTunnelsResponse
	(*ListEdgeClaimedPortsResponse)(nil),       // 45: calabi.v1.bff_edge.ListEdgeClaimedPortsResponse
	(*DeleteTunnelResponse)(nil),               // 46: calabi.v1.bff_edge.DeleteTunnelResponse
	(*ResolveResponse)(nil),                    // 47: calabi.v1.bff_edge.ResolveResponse
	(*ResolveOwnersResponse)(nil),              // 48: calabi.v1.bff_edge.ResolveOwnersResponse
	(*ReclaimTunnelResponse)(nil),              // 49: calabi.v1.bff_edge.ReclaimTunnelResponse
	(*DrainEdgeResponse)(nil),                  // 50: calabi.v1.bff_edge.DrainEdgeResponse
	(*GetCertResponse)(nil),                    // 51: calabi.v1.bff_edge.GetCertResponse
	(*ListCertsResponse)(nil),                  // 52: calabi.v1.bff_edge.ListCertsResponse
	(*IssueEdgeCertResponse)(nil),              // 53: calabi.v1.bff_edge.IssueEdgeCertResponse
	(*EffectiveQuota)(nil),                     // 54: calabi.v1.bff_edge.EffectiveQuota
	(*ConfigMessage)(nil),                      // 55: calabi.v1.bff_edge.ConfigMessage
}
var file_edgepb_bff_edge_proto_depIdxs = []int32{
	17, // 0: calabi.v1.bff_edge.UsageReport.window_close_at:type_name -> google.protobuf.Timestamp
	9,  // 1: calabi.v1.bff_edge.ReportUsageRequest.reports:type_name -> calabi.v1.bff_edge.UsageReport
	17, // 2: calabi.v1.bff_edge.RelayUsageReport.window_close_at:type_name -> google.protobuf.Timestamp
	12, // 3: calabi.v1.bff_edge.ReportRelayUsageRequest.reports:type_name -> calabi.v1.bff_edge.RelayUsageReport
	18, // 4: calabi.v1.bff_edge.BFFEdge.ValidateToken:input_type -> calabi.v1.bff_edge.ValidateTokenRequest
	19, // 5: calabi.v1.bff_edge.BFFEdge.RegisterEdgeNode:input_type -> calabi.v1.bff_edge.RegisterEdgeNodeRequest
	20, // 6: calabi.v1.bff_edge.BFFEdge.ReportClientPresence:input_type -> calabi.v1.bff_edge.ReportClientPresenceRequest
	21, // 7: calabi.v1.bff_edge.BFFEdge.GetOrgOnlineCount:input_type -> calabi.v1.bff_edge.GetOrgOnlineCountRequest
	22, // 8: calabi.v1.bff_edge.BFFEdge.ListEdges:input_type -> calabi.v1.bff_edge.ListEdgesRequest
	23, // 9: calabi.v1.bff_edge.BFFEdge.CreateTunnel:input_type -> calabi.v1.bff_edge.CreateTunnelRequest
	24, // 10: calabi.v1.bff_edge.BFFEdge.ClaimTunnel:input_type -> calabi.v1.bff_edge.ClaimTunnelRequest
	25, // 11: calabi.v1.bff_edge.BFFEdge.ReportStatus:input_type -> calabi.v1.bff_edge.ReportStatusRequest
	26, // 12: calabi.v1.bff_edge.BFFEdge.ListTunnels:input_type -> calabi.v1.bff_edge.ListTunnelsRequest
	27, // 13: calabi.v1.bff_edge.BFFEdge.ListEdgeClaimedPorts:input_type -> calabi.v1.bff_edge.ListEdgeClaimedPortsRequest
	28, // 14: calabi.v1.bff_edge.BFFEdge.DeleteTunnel:input_type -> calabi.v1.bff_edge.DeleteTunnelRequest
	29, // 15: calabi.v1.bff_edge.BFFEdge.Resolve:input_type -> calabi.v1.bff_edge.ResolveRequest
	30, // 16: calabi.v1.bff_edge.BFFEdge.ResolveOwners:input_type -> calabi.v1.bff_edge.ResolveOwnersRequest
	31, // 17: calabi.v1.bff_edge.BFFEdge.ReclaimTunnel:input_type -> calabi.v1.bff_edge.ReclaimTunnelRequest
	32, // 18: calabi.v1.bff_edge.BFFEdge.DrainEdge:input_type -> calabi.v1.bff_edge.DrainEdgeRequest
	33, // 19: calabi.v1.bff_edge.BFFEdge.GetCert:input_type -> calabi.v1.bff_edge.GetCertRequest
	34, // 20: calabi.v1.bff_edge.BFFEdge.ListCerts:input_type -> calabi.v1.bff_edge.ListCertsRequest
	0,  // 21: calabi.v1.bff_edge.BFFEdge.RenewEdgeCert:input_type -> calabi.v1.bff_edge.RenewEdgeCertRequest
	35, // 22: calabi.v1.bff_edge.BFFEdge.GetEffectiveQuota:input_type -> calabi.v1.bff_edge.GetEffectiveRequest
	36, // 23: calabi.v1.bff_edge.BFFEdge.SubscribeConfig:input_type -> calabi.v1.bff_edge.EdgeMessage
	1,  // 24: calabi.v1.bff_edge.BFFEdge.SubscribeCertEvents:input_type -> calabi.v1.bff_edge.SubscribeCertEventsRequest
	3,  // 25: calabi.v1.bff_edge.BFFEdge.SubscribeTunnelEvents:input_type -> calabi.v1.bff_edge.SubscribeTunnelEventsRequest
	5,  // 26: calabi.v1.bff_edge.BFFEdge.SubscribeSessionEvictEvents:input_type -> calabi.v1.bff_edge.SubscribeSessionEvictEventsRequest
	7,  // 27: calabi.v1.bff_edge.BFFEdge.SubscribeUsageEvents:input_type -> calabi.v1.bff_edge.SubscribeUsageEventsRequest
	10, // 28: calabi.v1.bff_edge.BFFEdge.ReportUsage:input_type -> calabi.v1.bff_edge.ReportUsageRequest
	13, // 29: calabi.v1.bff_edge.BFFEdge.ReportRelayUsage:input_type -> calabi.v1.bff_edge.ReportRelayUsageRequest
	15, // 30: calabi.v1.bff_edge.BFFEdge.RegisterRelay:input_type -> calabi.v1.bff_edge.RegisterRelayRequest
	37, // 31: calabi.v1.bff_edge.BFFEdge.ValidateToken:output_type -> calabi.v1.bff_edge.ValidateTokenResponse
	38, // 32: calabi.v1.bff_edge.BFFEdge.RegisterEdgeNode:output_type -> calabi.v1.bff_edge.RegisterEdgeNodeResponse
	39, // 33: calabi.v1.bff_edge.BFFEdge.ReportClientPresence:output_type -> calabi.v1.bff_edge.ReportClientPresenceResponse
	40, // 34: calabi.v1.bff_edge.BFFEdge.GetOrgOnlineCount:output_type -> calabi.v1.bff_edge.GetOrgOnlineCountResponse
	41, // 35: calabi.v1.bff_edge.BFFEdge.ListEdges:output_type -> calabi.v1.bff_edge.ListEdgesResponse
	42, // 36: calabi.v1.bff_edge.BFFEdge.CreateTunnel:output_type -> calabi.v1.bff_edge.Tunnel
	42, // 37: calabi.v1.bff_edge.BFFEdge.ClaimTunnel:output_type -> calabi.v1.bff_edge.Tunnel
	43, // 38: calabi.v1.bff_edge.BFFEdge.ReportStatus:output_type -> calabi.v1.bff_edge.ReportStatusResponse
	44, // 39: calabi.v1.bff_edge.BFFEdge.ListTunnels:output_type -> calabi.v1.bff_edge.ListTunnelsResponse
	45, // 40: calabi.v1.bff_edge.BFFEdge.ListEdgeClaimedPorts:output_type -> calabi.v1.bff_edge.ListEdgeClaimedPortsResponse
	46, // 41: calabi.v1.bff_edge.BFFEdge.DeleteTunnel:output_type -> calabi.v1.bff_edge.DeleteTunnelResponse
	47, // 42: calabi.v1.bff_edge.BFFEdge.Resolve:output_type -> calabi.v1.bff_edge.ResolveResponse
	48, // 43: calabi.v1.bff_edge.BFFEdge.ResolveOwners:output_type -> calabi.v1.bff_edge.ResolveOwnersResponse
	49, // 44: calabi.v1.bff_edge.BFFEdge.ReclaimTunnel:output_type -> calabi.v1.bff_edge.ReclaimTunnelResponse
	50, // 45: calabi.v1.bff_edge.BFFEdge.DrainEdge:output_type -> calabi.v1.bff_edge.DrainEdgeResponse
	51, // 46: calabi.v1.bff_edge.BFFEdge.GetCert:output_type -> calabi.v1.bff_edge.GetCertResponse
	52, // 47: calabi.v1.bff_edge.BFFEdge.ListCerts:output_type -> calabi.v1.bff_edge.ListCertsResponse
	53, // 48: calabi.v1.bff_edge.BFFEdge.RenewEdgeCert:output_type -> calabi.v1.bff_edge.IssueEdgeCertResponse
	54, // 49: calabi.v1.bff_edge.BFFEdge.GetEffectiveQuota:output_type -> calabi.v1.bff_edge.EffectiveQuota
	55, // 50: calabi.v1.bff_edge.BFFEdge.SubscribeConfig:output_type -> calabi.v1.bff_edge.ConfigMessage
	2,  // 51: calabi.v1.bff_edge.BFFEdge.SubscribeCertEvents:output_type -> calabi.v1.bff_edge.CertEvent
	4,  // 52: calabi.v1.bff_edge.BFFEdge.SubscribeTunnelEvents:output_type -> calabi.v1.bff_edge.TunnelEvent
	6,  // 53: calabi.v1.bff_edge.BFFEdge.SubscribeSessionEvictEvents:output_type -> calabi.v1.bff_edge.SessionEvictEvent
	8,  // 54: calabi.v1.bff_edge.BFFEdge.SubscribeUsageEvents:output_type -> calabi.v1.bff_edge.UsageEvent
	11, // 55: calabi.v1.bff_edge.BFFEdge.ReportUsage:output_type -> calabi.v1.bff_edge.ReportUsageResponse
	14, // 56: calabi.v1.bff_edge.BFFEdge.ReportRelayUsage:output_type -> calabi.v1.bff_edge.ReportRelayUsageResponse
	16, // 57: calabi.v1.bff_edge.BFFEdge.RegisterRelay:output_type -> calabi.v1.bff_edge.RegisterRelayResponse
	31, // [31:58] is the sub-list for method output_type
	4,  // [4:31] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_edgepb_bff_edge_proto_init() }
func file_edgepb_bff_edge_proto_init() {
	if File_edgepb_bff_edge_proto != nil {
		return
	}
	file_edgepb_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edgepb_bff_edge_proto_rawDesc), len(file_edgepb_bff_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_edgepb_bff_edge_proto_goTypes,
		DependencyIndexes: file_edgepb_bff_edge_proto_depIdxs,
		MessageInfos:      file_edgepb_bff_edge_proto_msgTypes,
	}.Build()
	File_edgepb_bff_edge_proto = out.File
	file_edgepb_bff_edge_proto_goTypes = nil
	file_edgepb_bff_edge_proto_depIdxs = nil
}
