// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MeshACL is the predicate function for meshacl builders.
type MeshACL func(*sql.Selector)

// MeshACLRevision is the predicate function for meshaclrevision builders.
type MeshACLRevision func(*sql.Selector)

// MeshNode is the predicate function for meshnode builders.
type MeshNode func(*sql.Selector)

// MeshRelay is the predicate function for meshrelay builders.
type MeshRelay func(*sql.Selector)

// MeshService is the predicate function for meshservice builders.
type MeshService func(*sql.Selector)

// MeshSetting is the predicate function for meshsetting builders.
type MeshSetting func(*sql.Selector)
