// coord.proto — v0 of the node<->coordinator API for Calabi mesh.
//
// ⚠ DELIBERATELY NOT under the repo's top-level proto/ tree. The root buf module
// (proto/buf.yaml) generates EVERYTHING it sees into pkg/api — the control-plane
// module that is NEVER open-sourced. Generating the mesh coordination contract
// there would defeat the isolation invariant (see./doc.go). So this file lives
// inside the pkg/mesh-proto module with its OWN buf module + gen config, using
// LOCAL plugins (no network, no protoc). Regenerate with:
//
//   cd pkg/mesh-proto && buf generate
//
// -> meshpb/coord.pb.go + meshpb/coord_grpc.pb.go (package meshpb). Also wired
// as `make proto-mesh`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meshpb/coord.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64 (WireGuard-style) public keys. Private keys never leave the node.
	NodeKey  string `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	DiscoKey string `protobuf:"bytes,2,opt,name=disco_key,json=discoKey,proto3" json:"disco_key,omitempty"`
	// Human label used for MagicDNS (MESH.6): <name>.<meshnet>.mesh.calabi.net
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque auth-key/token proving the node may join a meshnet (verified by
	// identity-svc on the platform build; a static file on the community coord).
	AuthKey string `protobuf:"bytes,4,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	// Highest protocol version + capabilities the node speaks (see version.go).
	ProtocolVersion uint32   `protobuf:"varint,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Subnet routes this node advertises (CIDRs it can forward to, e.g.
	// "192.168.1.0/24"). The coordinator, once it approves them, adds them to this
	// node's allowed_ips in peers' netmaps so they route the CIDR here (MESH.7).
	AdvertisedRoutes []string `protobuf:"bytes,7,rep,name=advertised_routes,json=advertisedRoutes,proto3" json:"advertised_routes,omitempty"`
	// device_fingerprint is the daemon's per-install id (the same one it registers
	// with on the Publish side). A CLAIM, like name: it exists only so the console
	// can offer "open this machine's client details" and is never used for
	// authorization. The console resolves it against the org's own device list and
	// shows nothing when it doesn't match, so a bogus value costs a link, not
	// access. Empty from a daemon that has never registered a device.
	DeviceFingerprint string `protobuf:"bytes,8,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	// Services this node's OPERATOR declared in its config (name + proto + port).
	// A CLAIM, deliberately: a service name is an ACL selector, so a node that
	// could name its own services could name one that is granted access and pull
	// that traffic to itself. The coordinator therefore records these as PENDING
	// and an admin confirms them in the console before any rule matches — same
	// shape as advertised_routes above. Declared here so agent / IaC machines
	// need no console visit to propose what they offer.
	DeclaredServices []*DeclaredService `protobuf:"bytes,9,rep,name=declared_services,json=declaredServices,proto3" json:"declared_services,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_meshpb_coord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *RegisterNodeRequest) GetDiscoKey() string {
	if x != nil {
		return x.DiscoKey
	}
	return ""
}

func (x *RegisterNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterNodeRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *RegisterNodeRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RegisterNodeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterNodeRequest) GetAdvertisedRoutes() []string {
	if x != nil {
		return x.AdvertisedRoutes
	}
	return nil
}

func (x *RegisterNodeRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *RegisterNodeRequest) GetDeclaredServices() []*DeclaredService {
	if x != nil {
		return x.DeclaredServices
	}
	return nil
}

// DeclaredService is one entry of RegisterNodeRequest.declared_services.
type DeclaredService struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // MagicDNS-style label; it becomes an ACL "svc:" selector
	Proto string                 `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"` // "tcp" or "udp"
	// port is what mesh PEERS dial on this node's overlay address.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Note string `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"` // free text for the console; never interpreted
	// target is what the NODE ITSELF dials to reach the application, e.g.
	// "127.0.0.1:5432" or a box on its LAN. Empty means 127.0.0.1:<port>.
	//
	// The two differ for a reason worth stating: opening `port` in the packet
	// filter does nothing if the application is bound to loopback only, because a
	// peer's packet arrives on the tun interface addressed to the overlay address
	// and finds no socket there. Recording the target is also what lets a service
	// be published as a tunnel without asking for the address a second time — a
	// tunnel's local_addr IS this value.
	Target        string `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclaredService) Reset() {
	*x = DeclaredService{}
	mi := &file_meshpb_coord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclaredService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclaredService) ProtoMessage() {}

func (x *DeclaredService) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclaredService.ProtoReflect.Descriptor instead.
func (*DeclaredService) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{1}
}

func (x *DeclaredService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeclaredService) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *DeclaredService) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeclaredService) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *DeclaredService) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type RegisterNodeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Allocated overlay address, e.g. "100.64.0.5".
	OverlayAddr string `protobuf:"bytes,2,opt,name=overlay_addr,json=overlayAddr,proto3" json:"overlay_addr,omitempty"`
	// Negotiated working subset (intersection of node + coordinator caps).
	ProtocolVersion uint32   `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_meshpb_coord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterNodeResponse) GetOverlayAddr() string {
	if x != nil {
		return x.OverlayAddr
	}
	return ""
}

func (x *RegisterNodeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RegisterNodeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ServiceHealth is one service as the node itself sees it.
type ServiceHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// target_ok: the application answers where THIS MACHINE dials it.
	TargetOk bool `protobuf:"varint,2,opt,name=target_ok,json=targetOk,proto3" json:"target_ok,omitempty"`
	// mesh_ok: the machine can reach the service on its OWN overlay address, i.e.
	// the way a peer would. target_ok && !mesh_ok is the loopback-only case.
	MeshOk bool `protobuf:"varint,3,opt,name=mesh_ok,json=meshOk,proto3" json:"mesh_ok,omitempty"`
	// checked: false when the node could not test at all (a udp service, where a
	// connectionless dial proves nothing, or no overlay address yet). The two
	// booleans above are then meaningless — absence of a result is not a failure,
	// and rendering it as one would be worse than saying nothing.
	Checked       bool `protobuf:"varint,4,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_meshpb_coord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceHealth) GetTargetOk() bool {
	if x != nil {
		return x.TargetOk
	}
	return false
}

func (x *ServiceHealth) GetMeshOk() bool {
	if x != nil {
		return x.MeshOk
	}
	return false
}

func (x *ServiceHealth) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type UpdateNodeDeclarationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authenticated the same way RegisterNode is: the auth key resolves to the
	// meshnet, and node_key selects the node WITHIN it. A key that resolves to a
	// different meshnet therefore cannot reach this node at all.
	AuthKey          string             `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	NodeKey          string             `protobuf:"bytes,2,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	DeclaredServices []*DeclaredService `protobuf:"bytes,3,rep,name=declared_services,json=declaredServices,proto3" json:"declared_services,omitempty"`
	// Empty means "no change", not "clear it". A node reports "" both when it has
	// no Publish-side registration yet and when its config momentarily won't
	// read, and the second must not erase a good value.
	DeviceFingerprint string `protobuf:"bytes,4,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateNodeDeclarationsRequest) Reset() {
	*x = UpdateNodeDeclarationsRequest{}
	mi := &file_meshpb_coord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeDeclarationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeDeclarationsRequest) ProtoMessage() {}

func (x *UpdateNodeDeclarationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeDeclarationsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeDeclarationsRequest) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNodeDeclarationsRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *UpdateNodeDeclarationsRequest) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *UpdateNodeDeclarationsRequest) GetDeclaredServices() []*DeclaredService {
	if x != nil {
		return x.DeclaredServices
	}
	return nil
}

func (x *UpdateNodeDeclarationsRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

type UpdateNodeDeclarationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeDeclarationsResponse) Reset() {
	*x = UpdateNodeDeclarationsResponse{}
	mi := &file_meshpb_coord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeDeclarationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeDeclarationsResponse) ProtoMessage() {}

func (x *UpdateNodeDeclarationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeDeclarationsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeDeclarationsResponse) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNodeDeclarationsResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type ReportServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Services      []*ServiceHealth       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportServiceHealthRequest) Reset() {
	*x = ReportServiceHealthRequest{}
	mi := &file_meshpb_coord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportServiceHealthRequest) ProtoMessage() {}

func (x *ReportServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*ReportServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{6}
}

func (x *ReportServiceHealthRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReportServiceHealthRequest) GetServices() []*ServiceHealth {
	if x != nil {
		return x.Services
	}
	return nil
}

type ReportServiceHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportServiceHealthResponse) Reset() {
	*x = ReportServiceHealthResponse{}
	mi := &file_meshpb_coord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportServiceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportServiceHealthResponse) ProtoMessage() {}

func (x *ReportServiceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportServiceHealthResponse.ProtoReflect.Descriptor instead.
func (*ReportServiceHealthResponse) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{7}
}

type PullNetMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullNetMapRequest) Reset() {
	*x = PullNetMapRequest{}
	mi := &file_meshpb_coord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullNetMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullNetMapRequest) ProtoMessage() {}

func (x *PullNetMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullNetMapRequest.ProtoReflect.Descriptor instead.
func (*PullNetMapRequest) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{8}
}

func (x *PullNetMapRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// NetMap is the ACL-filtered view of the meshnet a single node is allowed to
// see. Peers the ACL denies are ABSENT (first layer of isolation).
type NetMap struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Self    *Peer                  `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Peers   []*Peer                `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	DerpMap *DERPMap               `protobuf:"bytes,3,opt,name=derp_map,json=derpMap,proto3" json:"derp_map,omitempty"`
	// Packet filter this node ENFORCES on inbound traffic (MESH.5b). The
	// coordinator compiles it from the meshnet's ACL for this node specifically:
	// "these sources may reach these ports OF MINE". Enforcement is on the
	// RECEIVING side on purpose — a sender that lies (or is compromised) still
	// can't get past the receiver's own copy of the rules.
	//
	// Empty list = allow nothing beyond what the netmap already permits at the
	// host level; a node that is meant to be fully open gets an explicit
	// allow-everything rule instead. (Clients that predate this field ignore it
	// and keep host-level filtering only.)
	PacketFilter []*FilterRule `protobuf:"bytes,4,rep,name=packet_filter,json=packetFilter,proto3" json:"packet_filter,omitempty"`
	// filter_enabled distinguishes the two very different meanings of an EMPTY
	// packet_filter:
	//
	//	false — this coordinator doesn't compile filters (an older build): the
	//	        node must NOT filter, or upgrading a client would cut its traffic.
	//	true  — the filter is authoritative: an empty list means "nothing may
	//	        reach me", which is what an ACL that names this node in no rule
	//	        actually says.
	//
	// A field that could be inferred from the list being empty would have to pick
	// one of those, and either choice is an outage for the other case.
	FilterEnabled bool `protobuf:"varint,5,opt,name=filter_enabled,json=filterEnabled,proto3" json:"filter_enabled,omitempty"`
	// relay_grant is the coordinator's signed authorization for THIS node to use
	// relays (R0'). Opaque here on purpose: the node forwards the bytes verbatim
	// to a relay, which verifies them with the coordinator's public key held as
	// static config — so a relay decides who may connect WITHOUT ever talking to
	// the control plane. Format and rules in./relaygrant.go.
	//
	// Empty means the node has no authorization to present. That is the normal
	// state on a coordinator that doesn't issue grants (relays then must not
	// require them), and it is also how an org over its traffic quota is cut off
	// from the platform's relays — note the coordinator downgrades the grant's
	// SCOPE rather than withholding it, so the org keeps the relays it runs
	// itself.
	//
	// Grants expire, so the coordinator re-sends the netmap well before they do;
	// a relay may also re-challenge a live link at any time.
	RelayGrant []byte `protobuf:"bytes,6,opt,name=relay_grant,json=relayGrant,proto3" json:"relay_grant,omitempty"`
	// self_services is the coordinator's registry of the services registered on
	// THIS node, sent so the node can self-check them (F3b).
	//
	// Needed because the registry is not only what the node declared. A manager
	// can enter a service in the console (F4a), and nothing else ever pushes that
	// back down — so without this field a console-authored service could never
	// show a reachability result at all. That is exactly the kind most likely to
	// be pointed at the wrong address, since nobody was standing at the machine
	// when it was entered.
	//
	// OBSERVATION ONLY, and the direction is worth being explicit about. This is
	// the coordinator handing a node addresses to dial, which sounds like it
	// widens what the control plane can make a machine do — it does not: an org
	// admin can already point that daemon anywhere via a tunnel's local_addr, and
	// a probe is strictly weaker (connect, then close, nothing forwarded).
	// Nothing here authorizes anything; the result is a badge on the node's own
	// row. Only this node's own services appear, and only APPROVED ones (the same
	// set the ACL sees) — a node's own unconfirmed declarations are already in its
	// config, so it checks those without being told.
	SelfServices  []*DeclaredService `protobuf:"bytes,7,rep,name=self_services,json=selfServices,proto3" json:"self_services,omitempty"` // MagicDNS records land here in MESH.6.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetMap) Reset() {
	*x = NetMap{}
	mi := &file_meshpb_coord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetMap) ProtoMessage() {}

func (x *NetMap) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetMap.ProtoReflect.Descriptor instead.
func (*NetMap) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{9}
}

func (x *NetMap) GetSelf() *Peer {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *NetMap) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NetMap) GetDerpMap() *DERPMap {
	if x != nil {
		return x.DerpMap
	}
	return nil
}

func (x *NetMap) GetPacketFilter() []*FilterRule {
	if x != nil {
		return x.PacketFilter
	}
	return nil
}

func (x *NetMap) GetFilterEnabled() bool {
	if x != nil {
		return x.FilterEnabled
	}
	return false
}

func (x *NetMap) GetRelayGrant() []byte {
	if x != nil {
		return x.RelayGrant
	}
	return nil
}

func (x *NetMap) GetSelfServices() []*DeclaredService {
	if x != nil {
		return x.SelfServices
	}
	return nil
}

// FilterRule allows traffic from any of src_cidrs to any of dst_ports on the
// receiving node. Ports are the node's OWN listening ports.
type FilterRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcCidrs      []string               `protobuf:"bytes,1,rep,name=src_cidrs,json=srcCidrs,proto3" json:"src_cidrs,omitempty"`
	DstPorts      []*PortRange           `protobuf:"bytes,2,rep,name=dst_ports,json=dstPorts,proto3" json:"dst_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRule) Reset() {
	*x = FilterRule{}
	mi := &file_meshpb_coord_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRule) ProtoMessage() {}

func (x *FilterRule) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRule.ProtoReflect.Descriptor instead.
func (*FilterRule) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{10}
}

func (x *FilterRule) GetSrcCidrs() []string {
	if x != nil {
		return x.SrcCidrs
	}
	return nil
}

func (x *FilterRule) GetDstPorts() []*PortRange {
	if x != nil {
		return x.DstPorts
	}
	return nil
}

// PortRange is an inclusive port span for one protocol. proto is "tcp", "udp",
// or "" for any; first=0,last=65535 means every port.
type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         uint32                 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last          uint32                 `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	Proto         string                 `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_meshpb_coord_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{11}
}

func (x *PortRange) GetFirst() uint32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *PortRange) GetLast() uint32 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *PortRange) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

type Peer struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeId      int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeKey     string                 `protobuf:"bytes,2,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	DiscoKey    string                 `protobuf:"bytes,3,opt,name=disco_key,json=discoKey,proto3" json:"disco_key,omitempty"`
	OverlayAddr string                 `protobuf:"bytes,4,opt,name=overlay_addr,json=overlayAddr,proto3" json:"overlay_addr,omitempty"`
	// Allowed IPs routed to this peer (its /32 + any subnet routes it advertises).
	AllowedIps []string `protobuf:"bytes,5,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	// Known candidate endpoints for direct connections (host:port).
	Endpoints []string `protobuf:"bytes,6,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// Region code of the peer's DERP home relay.
	DerpHome string `protobuf:"bytes,7,opt,name=derp_home,json=derpHome,proto3" json:"derp_home,omitempty"`
	// MagicDNS label — the node's name, resolved to its overlay IP by the
	// client-side resolver (MESH.6).
	Name          string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_meshpb_coord_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{12}
}

func (x *Peer) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Peer) GetNodeKey() string {
	if x != nil {
		return x.NodeKey
	}
	return ""
}

func (x *Peer) GetDiscoKey() string {
	if x != nil {
		return x.DiscoKey
	}
	return ""
}

func (x *Peer) GetOverlayAddr() string {
	if x != nil {
		return x.OverlayAddr
	}
	return ""
}

func (x *Peer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *Peer) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Peer) GetDerpHome() string {
	if x != nil {
		return x.DerpHome
	}
	return ""
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DERPMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*DERPRegion          `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPMap) Reset() {
	*x = DERPMap{}
	mi := &file_meshpb_coord_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPMap) ProtoMessage() {}

func (x *DERPMap) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPMap.ProtoReflect.Descriptor instead.
func (*DERPMap) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{13}
}

func (x *DERPMap) GetRegions() []*DERPRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

type DERPRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // e.g. "lax", "sgp"
	Nodes         []*DERPNode            `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPRegion) Reset() {
	*x = DERPRegion{}
	mi := &file_meshpb_coord_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPRegion) ProtoMessage() {}

func (x *DERPRegion) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPRegion.ProtoReflect.Descriptor instead.
func (*DERPRegion) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{14}
}

func (x *DERPRegion) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DERPRegion) GetNodes() []*DERPNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type DERPNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	DerpPort      int32                  `protobuf:"varint,2,opt,name=derp_port,json=derpPort,proto3" json:"derp_port,omitempty"`
	StunPort      int32                  `protobuf:"varint,3,opt,name=stun_port,json=stunPort,proto3" json:"stun_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DERPNode) Reset() {
	*x = DERPNode{}
	mi := &file_meshpb_coord_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DERPNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DERPNode) ProtoMessage() {}

func (x *DERPNode) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DERPNode.ProtoReflect.Descriptor instead.
func (*DERPNode) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{15}
}

func (x *DERPNode) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *DERPNode) GetDerpPort() int32 {
	if x != nil {
		return x.DerpPort
	}
	return 0
}

func (x *DERPNode) GetStunPort() int32 {
	if x != nil {
		return x.StunPort
	}
	return 0
}

type ReportEndpointsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoints []string               `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // host:port candidates
	// Region code of the relay the node measured as its LOWEST-latency home
	// (MESH.4 B2b). The node picks it by probing each region's STUN endpoint from
	// the DERP map; the coordinator accepts it only if the region exists in the
	// map it published, and distributes it to peers as this node's derp_home so
	// they relay via the closest hop. Empty = no change (keep the current home).
	HomeRegion    string `protobuf:"bytes,3,opt,name=home_region,json=homeRegion,proto3" json:"home_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEndpointsRequest) Reset() {
	*x = ReportEndpointsRequest{}
	mi := &file_meshpb_coord_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEndpointsRequest) ProtoMessage() {}

func (x *ReportEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ReportEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{16}
}

func (x *ReportEndpointsRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ReportEndpointsRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ReportEndpointsRequest) GetHomeRegion() string {
	if x != nil {
		return x.HomeRegion
	}
	return ""
}

type ReportEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEndpointsResponse) Reset() {
	*x = ReportEndpointsResponse{}
	mi := &file_meshpb_coord_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEndpointsResponse) ProtoMessage() {}

func (x *ReportEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshpb_coord_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ReportEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_meshpb_coord_proto_rawDescGZIP(), []int{17}
}

var File_meshpb_coord_proto protoreflect.FileDescriptor

const file_meshpb_coord_proto_rawDesc = "" +
	"\n" +
	"\x12meshpb/coord.proto\x12\x0ecalabi.mesh.v1\"\xf5\x02\n" +
	"\x13RegisterNodeRequest\x12\x19\n" +
	"\bnode_key\x18\x01 \x01(\tR\anodeKey\x12\x1b\n" +
	"\tdisco_key\x18\x02 \x01(\tR\bdiscoKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bauth_key\x18\x04 \x01(\tR\aauthKey\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12+\n" +
	"\x11advertised_routes\x18\a \x03(\tR\x10advertisedRoutes\x12-\n" +
	"\x12device_fingerprint\x18\b \x01(\tR\x11deviceFingerprint\x12L\n" +
	"\x11declared_services\x18\t \x03(\v2\x1f.calabi.mesh.v1.DeclaredServiceR\x10declaredServices\"{\n" +
	"\x0fDeclaredService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\"\xa1\x01\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12!\n" +
	"\foverlay_addr\x18\x02 \x01(\tR\voverlayAddr\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"s\n" +
	"\rServiceHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttarget_ok\x18\x02 \x01(\bR\btargetOk\x12\x17\n" +
	"\amesh_ok\x18\x03 \x01(\bR\x06meshOk\x12\x18\n" +
	"\achecked\x18\x04 \x01(\bR\achecked\"\xd2\x01\n" +
	"\x1dUpdateNodeDeclarationsRequest\x12\x19\n" +
	"\bauth_key\x18\x01 \x01(\tR\aauthKey\x12\x19\n" +
	"\bnode_key\x18\x02 \x01(\tR\anodeKey\x12L\n" +
	"\x11declared_services\x18\x03 \x03(\v2\x1f.calabi.mesh.v1.DeclaredServiceR\x10declaredServices\x12-\n" +
	"\x12device_fingerprint\x18\x04 \x01(\tR\x11deviceFingerprint\"9\n" +
	"\x1eUpdateNodeDeclarationsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"p\n" +
	"\x1aReportServiceHealthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x129\n" +
	"\bservices\x18\x02 \x03(\v2\x1d.calabi.mesh.v1.ServiceHealthR\bservices\"\x1d\n" +
	"\x1bReportServiceHealthResponse\",\n" +
	"\x11PullNetMapRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\xe1\x02\n" +
	"\x06NetMap\x12(\n" +
	"\x04self\x18\x01 \x01(\v2\x14.calabi.mesh.v1.PeerR\x04self\x12*\n" +
	"\x05peers\x18\x02 \x03(\v2\x14.calabi.mesh.v1.PeerR\x05peers\x122\n" +
	"\bderp_map\x18\x03 \x01(\v2\x17.calabi.mesh.v1.DERPMapR\aderpMap\x12?\n" +
	"\rpacket_filter\x18\x04 \x03(\v2\x1a.calabi.mesh.v1.FilterRuleR\fpacketFilter\x12%\n" +
	"\x0efilter_enabled\x18\x05 \x01(\bR\rfilterEnabled\x12\x1f\n" +
	"\vrelay_grant\x18\x06 \x01(\fR\n" +
	"relayGrant\x12D\n" +
	"\rself_services\x18\a \x03(\v2\x1f.calabi.mesh.v1.DeclaredServiceR\fselfServices\"a\n" +
	"\n" +
	"FilterRule\x12\x1b\n" +
	"\tsrc_cidrs\x18\x01 \x03(\tR\bsrcCidrs\x126\n" +
	"\tdst_ports\x18\x02 \x03(\v2\x19.calabi.mesh.v1.PortRangeR\bdstPorts\"K\n" +
	"\tPortRange\x12\x14\n" +
	"\x05first\x18\x01 \x01(\rR\x05first\x12\x12\n" +
	"\x04last\x18\x02 \x01(\rR\x04last\x12\x14\n" +
	"\x05proto\x18\x03 \x01(\tR\x05proto\"\xea\x01\n" +
	"\x04Peer\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x19\n" +
	"\bnode_key\x18\x02 \x01(\tR\anodeKey\x12\x1b\n" +
	"\tdisco_key\x18\x03 \x01(\tR\bdiscoKey\x12!\n" +
	"\foverlay_addr\x18\x04 \x01(\tR\voverlayAddr\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x03(\tR\n" +
	"allowedIps\x12\x1c\n" +
	"\tendpoints\x18\x06 \x03(\tR\tendpoints\x12\x1b\n" +
	"\tderp_home\x18\a \x01(\tR\bderpHome\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\"?\n" +
	"\aDERPMap\x124\n" +
	"\aregions\x18\x01 \x03(\v2\x1a.calabi.mesh.v1.DERPRegionR\aregions\"P\n" +
	"\n" +
	"DERPRegion\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12.\n" +
	"\x05nodes\x18\x02 \x03(\v2\x18.calabi.mesh.v1.DERPNodeR\x05nodes\"a\n" +
	"\bDERPNode\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x1b\n" +
	"\tderp_port\x18\x02 \x01(\x05R\bderpPort\x12\x1b\n" +
	"\tstun_port\x18\x03 \x01(\x05R\bstunPort\"p\n" +
	"\x16ReportEndpointsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x12\x1f\n" +
	"\vhome_region\x18\x03 \x01(\tR\n" +
	"homeRegion\"\x19\n" +
	"\x17ReportEndpointsResponse2\x80\x04\n" +
	"\vCoordinator\x12Y\n" +
	"\fRegisterNode\x12#.calabi.mesh.v1.RegisterNodeRequest\x1a$.calabi.mesh.v1.RegisterNodeResponse\x12I\n" +
	"\n" +
	"PullNetMap\x12!.calabi.mesh.v1.PullNetMapRequest\x1a\x16.calabi.mesh.v1.NetMap0\x01\x12b\n" +
	"\x0fReportEndpoints\x12&.calabi.mesh.v1.ReportEndpointsRequest\x1a'.calabi.mesh.v1.ReportEndpointsResponse\x12w\n" +
	"\x16UpdateNodeDeclarations\x12-.calabi.mesh.v1.UpdateNodeDeclarationsRequest\x1a..calabi.mesh.v1.UpdateNodeDeclarationsResponse\x12n\n" +
	"\x13ReportServiceHealth\x12*.calabi.mesh.v1.ReportServiceHealthRequest\x1a+.calabi.mesh.v1.ReportServiceHealthResponseB7Z5github.com/calabi/calabi/pkg/mesh-proto/meshpb;meshpbb\x06proto3"

var (
	file_meshpb_coord_proto_rawDescOnce sync.Once
	file_meshpb_coord_proto_rawDescData []byte
)

func file_meshpb_coord_proto_rawDescGZIP() []byte {
	file_meshpb_coord_proto_rawDescOnce.Do(func() {
		file_meshpb_coord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshpb_coord_proto_rawDesc), len(file_meshpb_coord_proto_rawDesc)))
	})
	return file_meshpb_coord_proto_rawDescData
}

var file_meshpb_coord_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_meshpb_coord_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),            // 0: calabi.mesh.v1.RegisterNodeRequest
	(*DeclaredService)(nil),                // 1: calabi.mesh.v1.DeclaredService
	(*RegisterNodeResponse)(nil),           // 2: calabi.mesh.v1.RegisterNodeResponse
	(*ServiceHealth)(nil),                  // 3: calabi.mesh.v1.ServiceHealth
	(*UpdateNodeDeclarationsRequest)(nil),  // 4: calabi.mesh.v1.UpdateNodeDeclarationsRequest
	(*UpdateNodeDeclarationsResponse)(nil), // 5: calabi.mesh.v1.UpdateNodeDeclarationsResponse
	(*ReportServiceHealthRequest)(nil),     // 6: calabi.mesh.v1.ReportServiceHealthRequest
	(*ReportServiceHealthResponse)(nil),    // 7: calabi.mesh.v1.ReportServiceHealthResponse
	(*PullNetMapRequest)(nil),              // 8: calabi.mesh.v1.PullNetMapRequest
	(*NetMap)(nil),                         // 9: calabi.mesh.v1.NetMap
	(*FilterRule)(nil),                     // 10: calabi.mesh.v1.FilterRule
	(*PortRange)(nil),                      // 11: calabi.mesh.v1.PortRange
	(*Peer)(nil),                           // 12: calabi.mesh.v1.Peer
	(*DERPMap)(nil),                        // 13: calabi.mesh.v1.DERPMap
	(*DERPRegion)(nil),                     // 14: calabi.mesh.v1.DERPRegion
	(*DERPNode)(nil),                       // 15: calabi.mesh.v1.DERPNode
	(*ReportEndpointsRequest)(nil),         // 16: calabi.mesh.v1.ReportEndpointsRequest
	(*ReportEndpointsResponse)(nil),        // 17: calabi.mesh.v1.ReportEndpointsResponse
}
var file_meshpb_coord_proto_depIdxs = []int32{
	1,  // 0: calabi.mesh.v1.RegisterNodeRequest.declared_services:type_name -> calabi.mesh.v1.DeclaredService
	1,  // 1: calabi.mesh.v1.UpdateNodeDeclarationsRequest.declared_services:type_name -> calabi.mesh.v1.DeclaredService
	3,  // 2: calabi.mesh.v1.ReportServiceHealthRequest.services:type_name -> calabi.mesh.v1.ServiceHealth
	12, // 3: calabi.mesh.v1.NetMap.self:type_name -> calabi.mesh.v1.Peer
	12, // 4: calabi.mesh.v1.NetMap.peers:type_name -> calabi.mesh.v1.Peer
	13, // 5: calabi.mesh.v1.NetMap.derp_map:type_name -> calabi.mesh.v1.DERPMap
	10, // 6: calabi.mesh.v1.NetMap.packet_filter:type_name -> calabi.mesh.v1.FilterRule
	1,  // 7: calabi.mesh.v1.NetMap.self_services:type_name -> calabi.mesh.v1.DeclaredService
	11, // 8: calabi.mesh.v1.FilterRule.dst_ports:type_name -> calabi.mesh.v1.PortRange
	14, // 9: calabi.mesh.v1.DERPMap.regions:type_name -> calabi.mesh.v1.DERPRegion
	15, // 10: calabi.mesh.v1.DERPRegion.nodes:type_name -> calabi.mesh.v1.DERPNode
	0,  // 11: calabi.mesh.v1.Coordinator.RegisterNode:input_type -> calabi.mesh.v1.RegisterNodeRequest
	8,  // 12: calabi.mesh.v1.Coordinator.PullNetMap:input_type -> calabi.mesh.v1.PullNetMapRequest
	16, // 13: calabi.mesh.v1.Coordinator.ReportEndpoints:input_type -> calabi.mesh.v1.ReportEndpointsRequest
	4,  // 14: calabi.mesh.v1.Coordinator.UpdateNodeDeclarations:input_type -> calabi.mesh.v1.UpdateNodeDeclarationsRequest
	6,  // 15: calabi.mesh.v1.Coordinator.ReportServiceHealth:input_type -> calabi.mesh.v1.ReportServiceHealthRequest
	2,  // 16: calabi.mesh.v1.Coordinator.RegisterNode:output_type -> calabi.mesh.v1.RegisterNodeResponse
	9,  // 17: calabi.mesh.v1.Coordinator.PullNetMap:output_type -> calabi.mesh.v1.NetMap
	17, // 18: calabi.mesh.v1.Coordinator.ReportEndpoints:output_type -> calabi.mesh.v1.ReportEndpointsResponse
	5,  // 19: calabi.mesh.v1.Coordinator.UpdateNodeDeclarations:output_type -> calabi.mesh.v1.UpdateNodeDeclarationsResponse
	7,  // 20: calabi.mesh.v1.Coordinator.ReportServiceHealth:output_type -> calabi.mesh.v1.ReportServiceHealthResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_meshpb_coord_proto_init() }
func file_meshpb_coord_proto_init() {
	if File_meshpb_coord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshpb_coord_proto_rawDesc), len(file_meshpb_coord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshpb_coord_proto_goTypes,
		DependencyIndexes: file_meshpb_coord_proto_depIdxs,
		MessageInfos:      file_meshpb_coord_proto_msgTypes,
	}.Build()
	File_meshpb_coord_proto = out.File
	file_meshpb_coord_proto_goTypes = nil
	file_meshpb_coord_proto_depIdxs = nil
}
