// coord.proto — v0 of the node<->coordinator API for Calabi mesh.
//
// ⚠ DELIBERATELY NOT under the repo's top-level proto/ tree. The root buf module
// (proto/buf.yaml) generates EVERYTHING it sees into pkg/api — the control-plane
// module that is NEVER open-sourced. Generating the mesh coordination contract
// there would defeat the isolation invariant (see./doc.go). So this file lives
// inside the pkg/mesh-proto module with its OWN buf module + gen config, using
// LOCAL plugins (no network, no protoc). Regenerate with:
//
//   cd pkg/mesh-proto && buf generate
//
// -> meshpb/coord.pb.go + meshpb/coord_grpc.pb.go (package meshpb). Also wired
// as `make proto-mesh`.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: meshpb/coord.proto

package meshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordinator_RegisterNode_FullMethodName           = "/calabi.mesh.v1.Coordinator/RegisterNode"
	Coordinator_GetRegisterChallenge_FullMethodName   = "/calabi.mesh.v1.Coordinator/GetRegisterChallenge"
	Coordinator_SignOut_FullMethodName                = "/calabi.mesh.v1.Coordinator/SignOut"
	Coordinator_ListNodes_FullMethodName              = "/calabi.mesh.v1.Coordinator/ListNodes"
	Coordinator_ReportTunnels_FullMethodName          = "/calabi.mesh.v1.Coordinator/ReportTunnels"
	Coordinator_ListTunnels_FullMethodName            = "/calabi.mesh.v1.Coordinator/ListTunnels"
	Coordinator_GetUsage_FullMethodName               = "/calabi.mesh.v1.Coordinator/GetUsage"
	Coordinator_OpenViewSession_FullMethodName        = "/calabi.mesh.v1.Coordinator/OpenViewSession"
	Coordinator_GetEdgeAccess_FullMethodName          = "/calabi.mesh.v1.Coordinator/GetEdgeAccess"
	Coordinator_PullNetMap_FullMethodName             = "/calabi.mesh.v1.Coordinator/PullNetMap"
	Coordinator_ReportEndpoints_FullMethodName        = "/calabi.mesh.v1.Coordinator/ReportEndpoints"
	Coordinator_UpdateNodeDeclarations_FullMethodName = "/calabi.mesh.v1.Coordinator/UpdateNodeDeclarations"
	Coordinator_ReportServiceHealth_FullMethodName    = "/calabi.mesh.v1.Coordinator/ReportServiceHealth"
	Coordinator_ReportConnections_FullMethodName      = "/calabi.mesh.v1.Coordinator/ReportConnections"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Coordinator is the mesh control plane ("the brains"). Nodes authenticate out
// of band (identity-svc auth key / interactive login) and then speak only this
// API. The coordinator sees METADATA (keys, endpoints, the netmap) but never
// node<->node payload — that is WireGuard end-to-end encrypted.
type CoordinatorClient interface {
	// RegisterNode enrolls a node into its meshnet (= org): the coordinator
	// records its public keys, allocates an overlay IP (IPAM), and returns the
	// node's identity within the mesh.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// GetRegisterChallenge hands a node a one-time challenge that RegisterNode
	// requires it to answer with its node private key (mesh protocol v2). An org
	// credential says which meshnet the caller belongs to; only this proof says
	// which DEVICE it is, so knowing a node key - public within an org - is no
	// longer enough to enroll it or take its record over.
	GetRegisterChallenge(ctx context.Context, in *GetRegisterChallengeRequest, opts ...grpc.CallOption) (*GetRegisterChallengeResponse, error)
	// SignOut ends this node's ability to re-register by proof alone (node_reauth,
	// see RegisterNodeRequest.node_id): until it next enrolls with an auth key, the
	// coordinator refuses to take it back on its node key. The node's record, its
	// overlay address and its seat stay. Called on sign-out, best effort.
	SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error)
	// ListNodes lists the caller's meshnet — every device, reachable from the
	// caller or not, with whether it is online — for a self-hosted coordinator's
	// own apps: the phone's device list. A coordinator whose credentials come
	// from an identity service answers PermissionDenied: there, device lists are
	// served by the platform's API, which is where who may see what is decided.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// ReportTunnels uploads the reverse tunnels this node's daemon serves, for a
	// self-hosted coordinator's apps: the whole current list, which replaces the one reported before, and
	// the bytes each tunnel carried since the node's last accepted report.
	// Information only — a tunnel grants nothing in the mesh, so nothing here
	// needs approving. PermissionDenied on a coordinator whose credentials come
	// from an identity service: the platform keeps its tunnels in its own services.
	ReportTunnels(ctx context.Context, in *ReportTunnelsRequest, opts ...grpc.CallOption) (*ReportTunnelsResponse, error)
	// ListTunnels lists what every node of the caller's meshnet last reported
	// with ReportTunnels. Self-hosted only, like ListNodes.
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	// GetUsage is the traffic the caller's meshnet sent through this server —
	// its tunnels, and mesh traffic its relays carried; a direct path never
	// touches the server — plus its device count. Self-hosted only.
	GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error)
	// OpenViewSession proves the node key exactly as RegisterNode does (a
	// challenge from GetRegisterChallenge with node_id and node_key, no auth key),
	// and returns a token that ListNodes, ListTunnels and GetUsage accept for a
	// few minutes. It neither replaces the node's live session nor makes it
	// online: it is how a phone shows its server while it is not connected.
	// Self-hosted only.
	OpenViewSession(ctx context.Context, in *OpenViewSessionRequest, opts ...grpc.CallOption) (*OpenViewSessionResponse, error)
	// GetEdgeAccess is what a node needs to serve tunnels through this server's
	// edge: where the edge is, how
	// to trust its certificate, and a grant the edge accepts — the same signed,
	// short-lived statement relays accept, since one calabi-edge is both. Takes a
	// live session's token or a view token, so a device whose mesh is switched off
	// still serves tunnels. A disabled, signed-out or deleted node gets nothing.
	// Self-hosted only.
	GetEdgeAccess(ctx context.Context, in *GetEdgeAccessRequest, opts ...grpc.CallOption) (*GetEdgeAccessResponse, error)
	// PullNetMap is a long-lived server stream. The coordinator pushes a fresh
	// NetMap whenever topology or ACL changes, so the node reprograms its
	// WireGuard peers live without reconnecting.
	PullNetMap(ctx context.Context, in *PullNetMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetMap], error)
	// ReportEndpoints uploads the node's freshly discovered candidate endpoints
	// (local interfaces + STUN-reflexive) and, once measured, the relay region it
	// is closest to. The coordinator relays both to peers via their NetMap so hole
	// punching can begin and relayed traffic takes the nearest hop (MESH.4).
	ReportEndpoints(ctx context.Context, in *ReportEndpointsRequest, opts ...grpc.CallOption) (*ReportEndpointsResponse, error)
	// UpdateNodeDeclarations changes what an ALREADY-ENROLLED node declares about
	// itself, without re-enrolling it.
	//
	// Declarations used to travel only on RegisterNode, so editing a service list
	// meant tearing the session down and building it back up: new WireGuard
	// config, re-dialled relays, re-punched direct paths, and a home-relay flap —
	// seconds of disrupted traffic for a metadata edit that changes no addresses.
	//
	// It is deliberately NOT a general "update the node" call. Only the fields a
	// node merely ASSERTS about itself live here, and each is recorded exactly as
	// RegisterNode records it (declarations stay pending until a human confirms
	// them; the fingerprint stays display-only). Anything an admin can pin — name,
	// tags, route approvals — is out of scope: those are decisions ABOUT the node,
	// and a node must not be able to move them.
	//
	// FailedPrecondition when the node key isn't enrolled in this meshnet, so a
	// caller that raced a wipe falls back to RegisterNode instead of silently
	// doing nothing.
	UpdateNodeDeclarations(ctx context.Context, in *UpdateNodeDeclarationsRequest, opts ...grpc.CallOption) (*UpdateNodeDeclarationsResponse, error)
	// ReportServiceHealth uploads what a node OBSERVES about the services it
	// declares — not what it claims about them.
	//
	// It answers the question the console otherwise cannot: an admin writes a rule
	// naming a service, confirms it, and it still does not work. The usual cause
	// is that the application is bound to 127.0.0.1 only, so opening the port in
	// the packet filter changes nothing — a peer's packet arrives on the tun
	// interface addressed to the overlay address and finds no socket. The node is
	// the only party that can tell the two cases apart, by dialing BOTH its own
	// target and its own overlay address.
	//
	// Observation, deliberately, not configuration: nothing here grants anything,
	// so a node lying costs it a wrong badge on its own row. The coordinator keeps
	// only the CURRENT value and does not persist it — a history of which port
	// answered when is exactly the kind of record says not to accumulate.
	ReportServiceHealth(ctx context.Context, in *ReportServiceHealthRequest, opts ...grpc.CallOption) (*ReportServiceHealthResponse, error)
	// ReportConnections uploads WHO this node exchanged traffic with in a window:
	// the peer, when, how many bytes each way, and whether the path was direct or
	// relayed. It is the data-plane half of an audit trail — the control-plane
	// half (who changed a rule, who approved a device) already lives in
	// audit-svc's hash chain.
	//
	// This REVISES the "current value, never a time series" rule in and the revision is deliberately
	// narrow. What that rule was protecting is spelled out there: a sequence of a
	// laptop's ENDPOINT ADDRESSES is a location trail, because a public IP reverse
	// -resolves to a place and an ISP. So endpoints are still current-value only,
	// and this message carries none — no endpoint, no public IP, no port. A peer
	// pair plus a byte count is an access trail, which is the thing an enterprise
	// buyer is asking for when they ask for audit.
	//
	// Still metadata, never content: the coordinator's promise that it cannot
	// what flows between nodes is unchanged, and nothing here comes close to it.
	//
	// SELF-REPORTED, like every other declaration. A compromised endpoint can
	// under-report its own connections, so this is observational evidence and not
	// proof — the same status as endpoint telemetry everywhere else. Say so in the
	// console rather than letting a reader assume it is tamper-proof.
	ReportConnections(ctx context.Context, in *ReportConnectionsRequest, opts ...grpc.CallOption) (*ReportConnectionsResponse, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, Coordinator_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetRegisterChallenge(ctx context.Context, in *GetRegisterChallengeRequest, opts ...grpc.CallOption) (*GetRegisterChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegisterChallengeResponse)
	err := c.cc.Invoke(ctx, Coordinator_GetRegisterChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignOutResponse)
	err := c.cc.Invoke(ctx, Coordinator_SignOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Coordinator_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ReportTunnels(ctx context.Context, in *ReportTunnelsRequest, opts ...grpc.CallOption) (*ReportTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTunnelsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ReportTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageResponse)
	err := c.cc.Invoke(ctx, Coordinator_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) OpenViewSession(ctx context.Context, in *OpenViewSessionRequest, opts ...grpc.CallOption) (*OpenViewSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenViewSessionResponse)
	err := c.cc.Invoke(ctx, Coordinator_OpenViewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetEdgeAccess(ctx context.Context, in *GetEdgeAccessRequest, opts ...grpc.CallOption) (*GetEdgeAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeAccessResponse)
	err := c.cc.Invoke(ctx, Coordinator_GetEdgeAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PullNetMap(ctx context.Context, in *PullNetMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NetMap], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Coordinator_ServiceDesc.Streams[0], Coordinator_PullNetMap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullNetMapRequest, NetMap]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_PullNetMapClient = grpc.ServerStreamingClient[NetMap]

func (c *coordinatorClient) ReportEndpoints(ctx context.Context, in *ReportEndpointsRequest, opts ...grpc.CallOption) (*ReportEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportEndpointsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ReportEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) UpdateNodeDeclarations(ctx context.Context, in *UpdateNodeDeclarationsRequest, opts ...grpc.CallOption) (*UpdateNodeDeclarationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeDeclarationsResponse)
	err := c.cc.Invoke(ctx, Coordinator_UpdateNodeDeclarations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ReportServiceHealth(ctx context.Context, in *ReportServiceHealthRequest, opts ...grpc.CallOption) (*ReportServiceHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportServiceHealthResponse)
	err := c.cc.Invoke(ctx, Coordinator_ReportServiceHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ReportConnections(ctx context.Context, in *ReportConnectionsRequest, opts ...grpc.CallOption) (*ReportConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportConnectionsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ReportConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility.
//
// Coordinator is the mesh control plane ("the brains"). Nodes authenticate out
// of band (identity-svc auth key / interactive login) and then speak only this
// API. The coordinator sees METADATA (keys, endpoints, the netmap) but never
// node<->node payload — that is WireGuard end-to-end encrypted.
type CoordinatorServer interface {
	// RegisterNode enrolls a node into its meshnet (= org): the coordinator
	// records its public keys, allocates an overlay IP (IPAM), and returns the
	// node's identity within the mesh.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// GetRegisterChallenge hands a node a one-time challenge that RegisterNode
	// requires it to answer with its node private key (mesh protocol v2). An org
	// credential says which meshnet the caller belongs to; only this proof says
	// which DEVICE it is, so knowing a node key - public within an org - is no
	// longer enough to enroll it or take its record over.
	GetRegisterChallenge(context.Context, *GetRegisterChallengeRequest) (*GetRegisterChallengeResponse, error)
	// SignOut ends this node's ability to re-register by proof alone (node_reauth,
	// see RegisterNodeRequest.node_id): until it next enrolls with an auth key, the
	// coordinator refuses to take it back on its node key. The node's record, its
	// overlay address and its seat stay. Called on sign-out, best effort.
	SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error)
	// ListNodes lists the caller's meshnet — every device, reachable from the
	// caller or not, with whether it is online — for a self-hosted coordinator's
	// own apps: the phone's device list. A coordinator whose credentials come
	// from an identity service answers PermissionDenied: there, device lists are
	// served by the platform's API, which is where who may see what is decided.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// ReportTunnels uploads the reverse tunnels this node's daemon serves, for a
	// self-hosted coordinator's apps: the whole current list, which replaces the one reported before, and
	// the bytes each tunnel carried since the node's last accepted report.
	// Information only — a tunnel grants nothing in the mesh, so nothing here
	// needs approving. PermissionDenied on a coordinator whose credentials come
	// from an identity service: the platform keeps its tunnels in its own services.
	ReportTunnels(context.Context, *ReportTunnelsRequest) (*ReportTunnelsResponse, error)
	// ListTunnels lists what every node of the caller's meshnet last reported
	// with ReportTunnels. Self-hosted only, like ListNodes.
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	// GetUsage is the traffic the caller's meshnet sent through this server —
	// its tunnels, and mesh traffic its relays carried; a direct path never
	// touches the server — plus its device count. Self-hosted only.
	GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error)
	// OpenViewSession proves the node key exactly as RegisterNode does (a
	// challenge from GetRegisterChallenge with node_id and node_key, no auth key),
	// and returns a token that ListNodes, ListTunnels and GetUsage accept for a
	// few minutes. It neither replaces the node's live session nor makes it
	// online: it is how a phone shows its server while it is not connected.
	// Self-hosted only.
	OpenViewSession(context.Context, *OpenViewSessionRequest) (*OpenViewSessionResponse, error)
	// GetEdgeAccess is what a node needs to serve tunnels through this server's
	// edge: where the edge is, how
	// to trust its certificate, and a grant the edge accepts — the same signed,
	// short-lived statement relays accept, since one calabi-edge is both. Takes a
	// live session's token or a view token, so a device whose mesh is switched off
	// still serves tunnels. A disabled, signed-out or deleted node gets nothing.
	// Self-hosted only.
	GetEdgeAccess(context.Context, *GetEdgeAccessRequest) (*GetEdgeAccessResponse, error)
	// PullNetMap is a long-lived server stream. The coordinator pushes a fresh
	// NetMap whenever topology or ACL changes, so the node reprograms its
	// WireGuard peers live without reconnecting.
	PullNetMap(*PullNetMapRequest, grpc.ServerStreamingServer[NetMap]) error
	// ReportEndpoints uploads the node's freshly discovered candidate endpoints
	// (local interfaces + STUN-reflexive) and, once measured, the relay region it
	// is closest to. The coordinator relays both to peers via their NetMap so hole
	// punching can begin and relayed traffic takes the nearest hop (MESH.4).
	ReportEndpoints(context.Context, *ReportEndpointsRequest) (*ReportEndpointsResponse, error)
	// UpdateNodeDeclarations changes what an ALREADY-ENROLLED node declares about
	// itself, without re-enrolling it.
	//
	// Declarations used to travel only on RegisterNode, so editing a service list
	// meant tearing the session down and building it back up: new WireGuard
	// config, re-dialled relays, re-punched direct paths, and a home-relay flap —
	// seconds of disrupted traffic for a metadata edit that changes no addresses.
	//
	// It is deliberately NOT a general "update the node" call. Only the fields a
	// node merely ASSERTS about itself live here, and each is recorded exactly as
	// RegisterNode records it (declarations stay pending until a human confirms
	// them; the fingerprint stays display-only). Anything an admin can pin — name,
	// tags, route approvals — is out of scope: those are decisions ABOUT the node,
	// and a node must not be able to move them.
	//
	// FailedPrecondition when the node key isn't enrolled in this meshnet, so a
	// caller that raced a wipe falls back to RegisterNode instead of silently
	// doing nothing.
	UpdateNodeDeclarations(context.Context, *UpdateNodeDeclarationsRequest) (*UpdateNodeDeclarationsResponse, error)
	// ReportServiceHealth uploads what a node OBSERVES about the services it
	// declares — not what it claims about them.
	//
	// It answers the question the console otherwise cannot: an admin writes a rule
	// naming a service, confirms it, and it still does not work. The usual cause
	// is that the application is bound to 127.0.0.1 only, so opening the port in
	// the packet filter changes nothing — a peer's packet arrives on the tun
	// interface addressed to the overlay address and finds no socket. The node is
	// the only party that can tell the two cases apart, by dialing BOTH its own
	// target and its own overlay address.
	//
	// Observation, deliberately, not configuration: nothing here grants anything,
	// so a node lying costs it a wrong badge on its own row. The coordinator keeps
	// only the CURRENT value and does not persist it — a history of which port
	// answered when is exactly the kind of record says not to accumulate.
	ReportServiceHealth(context.Context, *ReportServiceHealthRequest) (*ReportServiceHealthResponse, error)
	// ReportConnections uploads WHO this node exchanged traffic with in a window:
	// the peer, when, how many bytes each way, and whether the path was direct or
	// relayed. It is the data-plane half of an audit trail — the control-plane
	// half (who changed a rule, who approved a device) already lives in
	// audit-svc's hash chain.
	//
	// This REVISES the "current value, never a time series" rule in and the revision is deliberately
	// narrow. What that rule was protecting is spelled out there: a sequence of a
	// laptop's ENDPOINT ADDRESSES is a location trail, because a public IP reverse
	// -resolves to a place and an ISP. So endpoints are still current-value only,
	// and this message carries none — no endpoint, no public IP, no port. A peer
	// pair plus a byte count is an access trail, which is the thing an enterprise
	// buyer is asking for when they ask for audit.
	//
	// Still metadata, never content: the coordinator's promise that it cannot
	// what flows between nodes is unchanged, and nothing here comes close to it.
	//
	// SELF-REPORTED, like every other declaration. A compromised endpoint can
	// under-report its own connections, so this is observational evidence and not
	// proof — the same status as endpoint telemetry everywhere else. Say so in the
	// console rather than letting a reader assume it is tamper-proof.
	ReportConnections(context.Context, *ReportConnectionsRequest) (*ReportConnectionsResponse, error)
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCoordinatorServer) GetRegisterChallenge(context.Context, *GetRegisterChallengeRequest) (*GetRegisterChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegisterChallenge not implemented")
}
func (UnimplementedCoordinatorServer) SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignOut not implemented")
}
func (UnimplementedCoordinatorServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedCoordinatorServer) ReportTunnels(context.Context, *ReportTunnelsRequest) (*ReportTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTunnels not implemented")
}
func (UnimplementedCoordinatorServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedCoordinatorServer) GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedCoordinatorServer) OpenViewSession(context.Context, *OpenViewSessionRequest) (*OpenViewSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenViewSession not implemented")
}
func (UnimplementedCoordinatorServer) GetEdgeAccess(context.Context, *GetEdgeAccessRequest) (*GetEdgeAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgeAccess not implemented")
}
func (UnimplementedCoordinatorServer) PullNetMap(*PullNetMapRequest, grpc.ServerStreamingServer[NetMap]) error {
	return status.Error(codes.Unimplemented, "method PullNetMap not implemented")
}
func (UnimplementedCoordinatorServer) ReportEndpoints(context.Context, *ReportEndpointsRequest) (*ReportEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEndpoints not implemented")
}
func (UnimplementedCoordinatorServer) UpdateNodeDeclarations(context.Context, *UpdateNodeDeclarationsRequest) (*UpdateNodeDeclarationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNodeDeclarations not implemented")
}
func (UnimplementedCoordinatorServer) ReportServiceHealth(context.Context, *ReportServiceHealthRequest) (*ReportServiceHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportServiceHealth not implemented")
}
func (UnimplementedCoordinatorServer) ReportConnections(context.Context, *ReportConnectionsRequest) (*ReportConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportConnections not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}
func (UnimplementedCoordinatorServer) testEmbeddedByValue()                     {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetRegisterChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisterChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetRegisterChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_GetRegisterChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetRegisterChallenge(ctx, req.(*GetRegisterChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_SignOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).SignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ReportTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ReportTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportTunnels(ctx, req.(*ReportTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetUsage(ctx, req.(*GetUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_OpenViewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenViewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).OpenViewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_OpenViewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).OpenViewSession(ctx, req.(*OpenViewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetEdgeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetEdgeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_GetEdgeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetEdgeAccess(ctx, req.(*GetEdgeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PullNetMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullNetMapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServer).PullNetMap(m, &grpc.GenericServerStream[PullNetMapRequest, NetMap]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_PullNetMapServer = grpc.ServerStreamingServer[NetMap]

func _Coordinator_ReportEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ReportEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportEndpoints(ctx, req.(*ReportEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_UpdateNodeDeclarations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeDeclarationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).UpdateNodeDeclarations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_UpdateNodeDeclarations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).UpdateNodeDeclarations(ctx, req.(*UpdateNodeDeclarationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ReportServiceHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportServiceHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportServiceHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ReportServiceHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportServiceHealth(ctx, req.(*ReportServiceHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ReportConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ReportConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportConnections(ctx, req.(*ReportConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calabi.mesh.v1.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _Coordinator_RegisterNode_Handler,
		},
		{
			MethodName: "GetRegisterChallenge",
			Handler:    _Coordinator_GetRegisterChallenge_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Coordinator_SignOut_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Coordinator_ListNodes_Handler,
		},
		{
			MethodName: "ReportTunnels",
			Handler:    _Coordinator_ReportTunnels_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _Coordinator_ListTunnels_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _Coordinator_GetUsage_Handler,
		},
		{
			MethodName: "OpenViewSession",
			Handler:    _Coordinator_OpenViewSession_Handler,
		},
		{
			MethodName: "GetEdgeAccess",
			Handler:    _Coordinator_GetEdgeAccess_Handler,
		},
		{
			MethodName: "ReportEndpoints",
			Handler:    _Coordinator_ReportEndpoints_Handler,
		},
		{
			MethodName: "UpdateNodeDeclarations",
			Handler:    _Coordinator_UpdateNodeDeclarations_Handler,
		},
		{
			MethodName: "ReportServiceHealth",
			Handler:    _Coordinator_ReportServiceHealth_Handler,
		},
		{
			MethodName: "ReportConnections",
			Handler:    _Coordinator_ReportConnections_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullNetMap",
			Handler:       _Coordinator_PullNetMap_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "meshpb/coord.proto",
}
