// Code generated by ent, DO NOT EDIT.

package meshaclrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the meshaclrevision type in the database.
	Label = "mesh_acl_revision"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMeshnetID holds the string denoting the meshnet_id field in the database.
	FieldMeshnetID = "meshnet_id"
	// FieldPolicyJSON holds the string denoting the policy_json field in the database.
	FieldPolicyJSON = "policy_json"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the meshaclrevision in the database.
	Table = "mesh_acl_revisions"
)

// Columns holds all SQL columns for meshaclrevision fields.
var Columns = []string{
	FieldID,
	FieldMeshnetID,
	FieldPolicyJSON,
	FieldActor,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPolicyJSON holds the default value on creation for the "policy_json" field.
	DefaultPolicyJSON string
	// DefaultActor holds the default value on creation for the "actor" field.
	DefaultActor string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the MeshACLRevision queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMeshnetID orders the results by the meshnet_id field.
func ByMeshnetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeshnetID, opts...).ToFunc()
}

// ByPolicyJSON orders the results by the policy_json field.
func ByPolicyJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyJSON, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
