// Code generated by ent, DO NOT EDIT.

package meshservice

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the meshservice type in the database.
	Label = "mesh_service"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMeshnetID holds the string denoting the meshnet_id field in the database.
	FieldMeshnetID = "meshnet_id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProto holds the string denoting the proto field in the database.
	FieldProto = "proto"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldApproved holds the string denoting the approved field in the database.
	FieldApproved = "approved"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the meshservice in the database.
	Table = "mesh_services"
)

// Columns holds all SQL columns for meshservice fields.
var Columns = []string{
	FieldID,
	FieldMeshnetID,
	FieldNodeID,
	FieldName,
	FieldProto,
	FieldPort,
	FieldTarget,
	FieldNote,
	FieldSource,
	FieldApproved,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProto holds the default value on creation for the "proto" field.
	DefaultProto string
	// DefaultTarget holds the default value on creation for the "target" field.
	DefaultTarget string
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultApproved holds the default value on creation for the "approved" field.
	DefaultApproved bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the MeshService queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMeshnetID orders the results by the meshnet_id field.
func ByMeshnetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeshnetID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProto orders the results by the proto field.
func ByProto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProto, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByApproved orders the results by the approved field.
func ByApproved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApproved, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
